import FastPoly.Polynomial.PeelMonic
import FastPoly.Polynomial.SquareGadget

/-!
# Division by a known monic polynomial

`lem:monic-division` of the paper: if `F = Q·D + Rr` with `D` monic and known and
`natDegree Rr < natDegree D`, then all coefficients of the quotient `Q` and the remainder
`Rr` are polynomially recoverable from the coefficients of `F` — the quotient causally from
the top (`[x^j]Q` needs only `[x^{a+j}]F, …, [x^{a+b}]F`), the remainder from the full window.

The quotient part is the `t = b + 1` case of `coeff_mem_of_mul_monic_add`.
-/

namespace FastPoly

open Polynomial Algebra

variable {R A : Type*} [CommRing R] [CommRing A] [Algebra R A]

/-- **Division by a monic polynomial** (`lem:monic-division`), quotient part:
`[x^j]Q` lies in the algebra generated by `K` and `[x^i]F` for `a + j ≤ i ≤ a + b`. -/
theorem coeff_quot_mem (K : Subalgebra R A) {F Q D Rr : A[X]}
    (hD : D.Monic) {a b : ℕ} (ha : D.natDegree = a) (ha1 : 1 ≤ a)
    (hDK : ∀ j, D.coeff j ∈ K)
    (hQ : Q.natDegree ≤ b) (hR : Rr.natDegree < a)
    (hF : F = Q * D + Rr) :
    ∀ j, j ≤ b → Q.coeff j ∈
      K ⊔ adjoin R ((fun i => F.coeff i) '' Set.Icc (a + j) (a + b)) := by
  intro j hj
  have hpeel := coeff_mem_of_mul_monic_add K hD hDK ha hQ
    (le_refl (b + 1)) ha1 (by omega : Rr.natDegree ≤ a + b - (b + 1)) hF (b - j) (by omega)
  rw [show b - (b - j) = j by omega] at hpeel
  refine SetLike.le_def.1 (sup_le_sup_left (adjoin_mono ?_) K) hpeel
  rintro _ ⟨s', hs', rfl⟩
  exact ⟨a + b - s', Set.mem_Icc.2 (by simp at hs'; omega), by congr 1⟩

/-- **Division by a monic polynomial** (`lem:monic-division`), remainder part:
each `[x^j]Rr` lies in the algebra generated by `K` and all `[x^i]F`, `i ≤ a + b`. -/
theorem coeff_rem_mem (K : Subalgebra R A) {F Q D Rr : A[X]}
    (hD : D.Monic) {a b : ℕ} (ha : D.natDegree = a) (ha1 : 1 ≤ a)
    (hDK : ∀ j, D.coeff j ∈ K)
    (hQ : Q.natDegree ≤ b) (hR : Rr.natDegree < a)
    (hF : F = Q * D + Rr) :
    ∀ j, Rr.coeff j ∈ K ⊔ adjoin R ((fun i => F.coeff i) '' Set.Iic (a + b)) := by
  intro j
  set V := K ⊔ adjoin R ((fun i => F.coeff i) '' Set.Iic (a + b)) with hV
  have hKV : K ≤ V := le_sup_left
  have hQmem : ∀ i, Q.coeff i ∈ V := by
    intro i
    rcases Nat.lt_or_ge b i with hib | hib
    · rw [coeff_eq_zero_of_natDegree_lt (by omega)]
      exact Subalgebra.zero_mem _
    · refine SetLike.le_def.1 (sup_le_sup_left (adjoin_mono ?_) K)
        (coeff_quot_mem K hD ha ha1 hDK hQ hR hF i hib)
      rintro _ ⟨i', hi', rfl⟩
      exact ⟨i', Set.mem_Iic.2 (by simp at hi'; omega), rfl⟩
  have hkey : Rr.coeff j = F.coeff j - (Q * D).coeff j := by
    rw [hF, coeff_add]; ring
  rw [hkey]
  refine Subalgebra.sub_mem _ ?_ (coeff_mul_mem V hQmem (fun i => hKV (hDK i)) j)
  rcases Nat.lt_or_ge (a + b) j with hjb | hjb
  · have h1 : (Q * D).natDegree ≤ b + a := le_trans natDegree_mul_le (by omega)
    rw [hF, coeff_eq_zero_of_natDegree_lt
      (lt_of_le_of_lt (natDegree_add_le _ _) (max_lt (by omega) (by omega)))]
    exact Subalgebra.zero_mem _
  · exact (le_sup_right : adjoin R _ ≤ V) (subset_adjoin ⟨j, Set.mem_Iic.2 hjb, rfl⟩)

end FastPoly
