import FastPoly.Recover.Context
import FastPoly.Polynomial.TopWindow

/-!
# Top-window division by a known monic factor

`lem:peel-monic-factor` of the paper: if `P = B·A + E` with `A` monic and known, and the
error `E` lives below the top `t` coefficients of the product, then the top `t` coefficients
of `B` are polynomially recoverable from the corresponding top coefficients of `P` —
causally: `[x^{b-s}]B` needs only `[x^{a+b-s'}]P` for `s' ≤ s`.

The engine is `coeff_mul_monic` (multiplication by a known monic polynomial is unitriangular
on top windows) and a descending induction identical in shape to the scalar certificate
theorem; the ℕ-indexed window makes a direct induction cleaner than instantiating the
`Fin`-indexed engine.
-/

namespace FastPoly

open Polynomial Algebra Finset

variable {R A : Type*} [CommRing R] [CommRing A] [Algebra R A]

/-- **Top-window division by a monic factor** (`lem:peel-monic-factor`).
If `P = B·M + E` with `M` monic of degree `a` whose coefficients lie in the known context
`K`, `natDegree B ≤ b`, `t ≤ b + 1`, `1 ≤ a`, and `natDegree E ≤ a + b - t`, then for every `s < t`
the coefficient `[x^{b-s}]B` lies in the algebra generated by `K` and the coefficients
`[x^{a+b-s'}]P` for `s' ≤ s`. -/
theorem coeff_mem_of_mul_monic_add (K : Subalgebra R A) {M B E P : A[X]}
    (hM : M.Monic) (hMK : ∀ j, M.coeff j ∈ K)
    {a b t : ℕ} (ha : M.natDegree = a) (hb : B.natDegree ≤ b) (ht : t ≤ b + 1) (ha1 : 1 ≤ a)
    (hE : E.natDegree ≤ a + b - t)
    (hP : P = B * M + E) :
    ∀ s, s < t → B.coeff (b - s) ∈
      K ⊔ adjoin R ((fun s' => P.coeff (a + b - s')) '' Set.Iic s) := by
  intro s hs
  induction s using Nat.strong_induction_on with
  | _ s ih =>
    -- the observation: [x^{a+b-s}]P = [x^{b-s}]B + ∑_{j<a} M_j · B_{a+b-s-j}
    have hEcoeff : E.coeff (a + b - s) = 0 := by
      apply coeff_eq_zero_of_natDegree_lt
      omega
    have hobs : P.coeff (a + b - s) =
        B.coeff (b - s) + ∑ j ∈ range a, M.coeff j * B.coeff (a + (b - s) - j) := by
      have h1 : a + b - s = M.natDegree + (b - s) := by omega
      rw [hP, coeff_add, hEcoeff, add_zero, h1, coeff_mul_monic B M hM, ha]
    -- solve for the unknown coefficient
    have key : B.coeff (b - s) =
        P.coeff (a + b - s) - ∑ j ∈ range a, M.coeff j * B.coeff (a + (b - s) - j) := by
      rw [hobs]; ring
    rw [key]
    refine Subalgebra.sub_mem _ ?_ (Subalgebra.sum_mem _ fun j hj => ?_)
    · -- the observation itself is visible at cutoff s
      exact (le_sup_right :
          adjoin R ((fun s' => P.coeff (a + b - s')) '' Set.Iic s) ≤ _)
        (subset_adjoin ⟨s, Set.self_mem_Iic, rfl⟩)
    · -- each summand: a known coefficient of M times a higher coefficient of B
      have hjA : j < a := mem_range.1 hj
      refine Subalgebra.mul_mem _ ((le_sup_left : K ≤ _) (hMK j)) ?_
      by_cases hhigh : b < a + (b - s) - j
      · -- above the degree of B: the coefficient vanishes
        rw [coeff_eq_zero_of_natDegree_lt (lt_of_le_of_lt hb hhigh)]
        exact Subalgebra.zero_mem _
      · -- inside the window: an earlier unknown, recovered by the induction hypothesis
        push_neg at hhigh
        set s' := s - (a - j) with hs'
        have hidx : a + (b - s) - j = b - s' := by omega
        have hs's : s' < s := by omega
        have hmem := ih s' hs's (lt_trans hs's hs)
        rw [hidx]
        refine SetLike.le_def.1 (sup_le_sup_left (adjoin_mono (Set.image_mono ?_)) K) hmem
        exact Set.Iic_subset_Iic.2 (le_of_lt hs's)

end FastPoly
