import FastPoly.Polynomial.CausalShell

/-!
# The square gadget `x·S² + (S+δ)²` with a boundary error

`lem:square-gadget` / `lem:square-gadget-boundary` of the paper: from
`G = x·S² + (S+δ)² + E` with `S` monic of degree `d ≥ 1`, `natDegree E ≤ d` and the boundary
coefficient `[x^d]E` known, one recovers all coefficients of `S` and the scalar shift `δ`
(using that `2` is a unit).  This is the workhorse of the `8k+3` and `8k+7` induction steps.

The proof delegates to the relative causal-shell decoder
`coeff_mem_of_square_gadget_relative`, instantiated at the constant algebra family
`V := K ⊔ adjoin R {[x^i]G : d ≤ i ≤ 2d+1}` (with a trivial subsingleton case, since the
relative engine assumes `Nontrivial A`).
-/

namespace FastPoly

open Polynomial Algebra Finset

variable {R A : Type*} [CommRing R] [CommRing A] [Algebra R A]

/-- A coefficient of a product lies in any subalgebra containing all coefficients of both
factors. -/
theorem coeff_mul_mem (S : Subalgebra R A) {p q : A[X]}
    (hp : ∀ j, p.coeff j ∈ S) (hq : ∀ j, q.coeff j ∈ S) (k : ℕ) :
    (p * q).coeff k ∈ S := by
  rw [coeff_mul]
  exact Subalgebra.sum_mem _ fun x _ => Subalgebra.mul_mem _ (hp x.1) (hq x.2)

/-- **Square gadget with a boundary error** (`lem:square-gadget-boundary`;
`lem:square-gadget` is the case `E = 0`).
If `G = X·S² + (S+δ)² + E` with `S` monic of degree `d ≥ 1`, `natDegree E ≤ d`,
`[x^d]E` in the known context `K`, and `2` a unit in `R`, then every coefficient of `S`
and the shift `δ` lie in the algebra generated by `K` and `[x^i]G` for `d ≤ i ≤ 2d+1`. -/
theorem square_gadget_mem (K : Subalgebra R A) {S E G : A[X]} {δ : A} {d : ℕ}
    (hS : S.Monic) (hd : S.natDegree = d) (hd1 : 1 ≤ d)
    (hE : E.natDegree ≤ d) (hEb : E.coeff d ∈ K) (h2 : IsUnit (2 : R))
    (hG : G = X * S ^ 2 + (S + C δ) ^ 2 + E) :
    (∀ j, S.coeff j ∈ K ⊔ adjoin R ((fun i => G.coeff i) '' Set.Icc d (2*d+1))) ∧
      δ ∈ K ⊔ adjoin R ((fun i => G.coeff i) '' Set.Icc d (2*d+1)) := by
  set V := K ⊔ adjoin R ((fun i => G.coeff i) '' Set.Icc d (2*d+1)) with hV
  rcases subsingleton_or_nontrivial A with hA | hA
  · have hall : ∀ x : A, x ∈ V := fun x => by
      rw [Subsingleton.elim x (0 : A)]
      exact Subalgebra.zero_mem _
    exact ⟨fun j => hall _, hall _⟩
  · have hKV : K ≤ V := le_sup_left
    have hGmem : ∀ i, d ≤ i → i ≤ 2*d + 1 → G.coeff i ∈ V := fun i h1 h2' =>
      (le_sup_right : adjoin R _ ≤ V) (subset_adjoin ⟨i, Set.mem_Icc.2 ⟨h1, h2'⟩, rfl⟩)
    obtain ⟨hSmem, hδmem⟩ := coeff_mem_of_square_gadget_relative (fun _ => V)
      (fun _ _ _ => le_rfl) hS hd hd1 h2
      (fun i h1 h2' => hGmem i h1 (by omega))
      (fun i hi => coeff_eq_zero_of_natDegree_lt (by omega))
      (hKV hEb) hG
    exact ⟨fun j => hSmem j, hδmem⟩

end FastPoly
