import Mathlib.RingTheory.Noetherian.Orzech
import Mathlib.RingTheory.Polynomial.Basic

/-!
# Polynomial decoders give automorphisms

This file is deliberately outside the core recovery framework.  The core statements only
say that the input parameters belong to the algebra generated by the visible coefficients.
At the free polynomial-ring instantiation, that statement says that the coordinate
substitution is surjective.  A surjective endomorphism of a Noetherian ring is injective,
so the substitution is an automorphism.

The injectivity argument below is elementary and explicit: the kernels of the iterates
form an increasing chain; after the chain stabilizes, surjectivity forces the first kernel
to vanish.  No Jacobian criterion is used.
-/

namespace FastPoly

open Function

universe u v

section NoetherianEndomorphism

variable {R : Type u} {B : Type v} [CommRing R] [CommRing B] [Algebra R B]

/-- The `n`-fold composite of an algebra endomorphism. -/
def algHomIterate (f : B →ₐ[R] B) : ℕ → B →ₐ[R] B
  | 0 => AlgHom.id R B
  | n + 1 => f.comp (algHomIterate f n)

@[simp] theorem algHomIterate_zero (f : B →ₐ[R] B) :
    algHomIterate f 0 = AlgHom.id R B := rfl

@[simp] theorem algHomIterate_succ_apply (f : B →ₐ[R] B) (n : ℕ) (x : B) :
    algHomIterate f (n + 1) x = f (algHomIterate f n x) := rfl

private theorem algHomIterate_ker_mono (f : B →ₐ[R] B) (n : ℕ) :
    RingHom.ker (algHomIterate f n).toRingHom ≤
      RingHom.ker (algHomIterate f (n + 1)).toRingHom := by
  intro x hx
  rw [RingHom.mem_ker] at hx ⊢
  change algHomIterate f n x = 0 at hx
  change algHomIterate f (n + 1) x = 0
  rw [algHomIterate_succ_apply, hx, map_zero]

/-- The increasing chain of kernels of the iterates of an algebra endomorphism. -/
def algHomIterateKer (f : B →ₐ[R] B) : ℕ →o Ideal B :=
  ⟨fun n => RingHom.ker (algHomIterate f n).toRingHom,
    monotone_nat_of_le_succ (algHomIterate_ker_mono f)⟩

private theorem algHomIterate_surjective (f : B →ₐ[R] B) (hf : Surjective f) :
    ∀ n, Surjective (algHomIterate f n)
  | 0 => by
      intro x
      exact ⟨x, rfl⟩
  | n + 1 => hf.comp (algHomIterate_surjective f hf n)

/-- A surjective algebra endomorphism of a Noetherian ring is injective. -/
theorem AlgHom.injective_of_surjective_of_isNoetherianRing [IsNoetherianRing B]
    (f : B →ₐ[R] B) (hf : Surjective f) : Injective f := by
  obtain ⟨n, hn⟩ :=
    (monotone_stabilizes_iff_noetherian.mpr (inferInstance : IsNoetherian B B))
      (algHomIterateKer f)
  have hstab : algHomIterateKer f n = algHomIterateKer f (n + 1) :=
    hn (n + 1) (Nat.le_succ n)
  intro x y hxy
  have hker : f (x - y) = 0 := by rw [map_sub, hxy, sub_self]
  obtain ⟨z, hz⟩ := algHomIterate_surjective f hf n (x - y)
  have hzsucc : z ∈ algHomIterateKer f (n + 1) := by
    change z ∈ RingHom.ker (algHomIterate f (n + 1)).toRingHom
    rw [RingHom.mem_ker]
    change algHomIterate f (n + 1) z = 0
    rw [algHomIterate_succ_apply, hz, hker]
  have hzn : z ∈ algHomIterateKer f n := by
    rw [hstab]
    exact hzsucc
  have hz0 : algHomIterate f n z = 0 := RingHom.mem_ker.mp hzn
  have hsub : x - y = 0 := by rw [← hz, hz0]
  exact sub_eq_zero.mp hsub

/-- A surjective algebra endomorphism of a Noetherian ring is bijective. -/
theorem AlgHom.bijective_of_surjective_of_isNoetherianRing [IsNoetherianRing B]
    (f : B →ₐ[R] B) (hf : Surjective f) : Bijective f :=
  ⟨AlgHom.injective_of_surjective_of_isNoetherianRing f hf, hf⟩

end NoetherianEndomorphism

section MvPolynomial

variable {R : Type u} [CommRing R]
variable {σ : Type v}

/-- Polynomial recovery of every coordinate makes substitution by `c` surjective. -/
theorem MvPolynomial.aeval_surjective_of_decodable (c : σ → MvPolynomial σ R)
    (hdecode : ∀ i, MvPolynomial.X i ∈ Algebra.adjoin R (Set.range c)) :
    Surjective (MvPolynomial.aeval (R := R) c) := by
  apply (AlgHom.range_eq_top (MvPolynomial.aeval (R := R) c)).mp
  rw [← Algebra.adjoin_range_eq_range_aeval R c]
  apply top_unique
  rw [← MvPolynomial.adjoin_range_X]
  apply Algebra.adjoin_le
  intro x hx
  obtain ⟨i, hi⟩ := hx
  rw [← hi]
  exact hdecode i

/-- Polynomial recovery of every coordinate makes substitution by `c` bijective. -/
theorem MvPolynomial.aeval_bijective_of_decodable (c : σ → MvPolynomial σ R)
    [IsNoetherianRing R] [Finite σ]
    (hdecode : ∀ i, MvPolynomial.X i ∈ Algebra.adjoin R (Set.range c)) :
    Bijective (MvPolynomial.aeval (R := R) c) := by
  apply AlgHom.bijective_of_surjective_of_isNoetherianRing (R := R)
  exact MvPolynomial.aeval_surjective_of_decodable c hdecode

/-- The coordinate automorphism supplied by an explicit polynomial decoder. -/
noncomputable def MvPolynomial.algEquivOfDecodable (c : σ → MvPolynomial σ R)
    [IsNoetherianRing R] [Finite σ]
    (hdecode : ∀ i, MvPolynomial.X i ∈ Algebra.adjoin R (Set.range c)) :
    MvPolynomial σ R ≃ₐ[R] MvPolynomial σ R :=
  AlgEquiv.ofBijective (MvPolynomial.aeval c)
    (MvPolynomial.aeval_bijective_of_decodable c hdecode)

end MvPolynomial

end FastPoly
