import FastPoly.Automorphism
import FastPoly.Recover.Context

/-!
# Free polynomial-ring instantiation

The recovery framework is stated over an abstract algebra.  This file supplies the final,
non-vacuous specialization: parameters are the coordinate variables in a free polynomial
ring.  For a monic polynomial of degree `n`, all coefficients generate the same algebra as
the `n` nonleading coefficients.  Thus a decoder for the parameters makes the actual
coefficient substitution an automorphism.
-/

namespace FastPoly

open Polynomial Algebra Function

universe u v

section CoefficientAlgebra

variable {R : Type u} {A : Type v} [CommRing R] [CommRing A] [Algebra R A]

/-- With no side information, every visible coefficient expression belongs to the algebra
generated by all coefficients.  This is the bridge from the abstract `Vis` semantics to
the usual coordinate-ring statement. -/
theorem Vis_bot_le_coeff_adjoin (P : A[X]) (G : Finset ℕ) (t : ℕ) :
    Vis R (⊥ : Subalgebra R A) P G t ≤
      Algebra.adjoin R (Set.range fun j : ℕ => P.coeff j) :=
  Vis_le bot_le fun i _ _ => Algebra.subset_adjoin ⟨i, rfl⟩

/-- Combining two monic degree-`d` components produces a monic degree-`d+1`
polynomial. -/
theorem combined_good_of_monic [Nontrivial A] {P₁ P₂ : A[X]} {d : ℕ}
    (hP₁ : P₁.Monic) (hd₁ : P₁.natDegree = d)
    (hP₂ : P₂.Monic) (hd₂ : P₂.natDegree = d) :
    (combined P₁ P₂).Monic ∧ (combined P₁ P₂).natDegree = d + 1 := by
  have hXm : (X * P₁).Monic := monic_X.mul hP₁
  have hXd : (X * P₁).natDegree = d + 1 := by
    rw [monic_X.natDegree_mul hP₁, natDegree_X, hd₁]
    omega
  have hlt : P₂.degree < (X * P₁).degree := by
    rw [degree_eq_natDegree hP₂.ne_zero, degree_eq_natDegree hXm.ne_zero, hd₂, hXd]
    exact_mod_cast Nat.lt_succ_self d
  change (X * P₁ + P₂).Monic ∧ (X * P₁ + P₂).natDegree = d + 1
  exact ⟨hXm.add_of_left hlt,
    by rw [natDegree_eq_of_degree_eq (degree_add_eq_left_of_degree_lt hlt), hXd]⟩

/-- The combined polynomial of a compatible pair has the expected monicity and degree. -/
theorem CompatiblePair.combined_good [Nontrivial A] {K : Subalgebra R A}
    {P₁ P₂ : A[X]} {d : ℕ} {G : Finset ℕ} (h : CompatiblePair K P₁ P₂ d G) :
    (combined P₁ P₂).Monic ∧ (combined P₁ P₂).natDegree = d + 1 :=
  combined_good_of_monic h.monic₁ h.natDegree₁ h.monic₂ h.natDegree₂

/-- A monic degree-`n` polynomial has no algebraically relevant coefficient outside its
`n` nonleading rows: row `n` is `1`, and every higher row is `0`. -/
theorem monic_coeff_adjoin_eq_fin {P : A[X]} {n : ℕ} (hP : P.Monic)
    (hd : P.natDegree = n) :
    Algebra.adjoin R (Set.range fun j : ℕ => P.coeff j) =
      Algebra.adjoin R (Set.range fun i : Fin n => P.coeff i) := by
  apply le_antisymm
  · apply Algebra.adjoin_le
    intro x hx
    obtain ⟨j, hjx⟩ := hx
    rw [← hjx]
    change P.coeff j ∈ Algebra.adjoin R (Set.range fun i : Fin n => P.coeff i)
    by_cases hj : j < n
    · exact Algebra.subset_adjoin ⟨⟨j, hj⟩, rfl⟩
    · rcases eq_or_lt_of_le (Nat.le_of_not_gt hj) with hEq | hlt
      · subst j
        rw [← hd, hP.coeff_natDegree]
        exact Subalgebra.one_mem _
      · have hz : P.coeff j = 0 := coeff_eq_zero_of_natDegree_lt (by omega)
        rw [hz]
        exact Subalgebra.zero_mem _
  · apply Algebra.adjoin_le
    intro x hx
    obtain ⟨i, hix⟩ := hx
    rw [← hix]
    change P.coeff i.1 ∈ Algebra.adjoin R (Set.range fun j : ℕ => P.coeff j)
    exact Algebra.subset_adjoin ⟨i.1, rfl⟩

end CoefficientAlgebra

section FreeParameters

variable {R : Type u} [CommRing R] [IsNoetherianRing R]
variable {n : ℕ}

/-- If the coordinate variables are recoverable from the coefficients of a monic
degree-`n` polynomial, substitution by its `n` nonleading coefficients is bijective. -/
theorem coefficient_aeval_bijective_of_monic_decodable
    (P : (MvPolynomial (Fin n) R)[X]) (hP : P.Monic) (hd : P.natDegree = n)
    (hdecode : ∀ i : Fin n,
      MvPolynomial.X i ∈ Algebra.adjoin R (Set.range fun j : ℕ => P.coeff j)) :
    Bijective (MvPolynomial.aeval (R := R) (fun i : Fin n => P.coeff i)) := by
  apply MvPolynomial.aeval_bijective_of_decodable
  intro i
  rw [← monic_coeff_adjoin_eq_fin (R := R) hP hd]
  exact hdecode i

/-- `Vis`-shaped version of `coefficient_aeval_bijective_of_monic_decodable`, ready to
consume an unconditional decoder from the construction theorem. -/
theorem coefficient_aeval_bijective_of_monic_Vis
    (P : (MvPolynomial (Fin n) R)[X]) (hP : P.Monic) (hd : P.natDegree = n)
    (G : Finset ℕ) (t : ℕ)
    (hdecode : ∀ i : Fin n,
      MvPolynomial.X i ∈ Vis R (⊥ : Subalgebra R (MvPolynomial (Fin n) R)) P G t) :
    Bijective (MvPolynomial.aeval (R := R) (fun i : Fin n => P.coeff i)) := by
  apply coefficient_aeval_bijective_of_monic_decodable P hP hd
  intro i
  exact Vis_bot_le_coeff_adjoin P G t (hdecode i)

/-- The coefficient automorphism induced by a decoded monic polynomial family. -/
noncomputable def coefficientAlgEquivOfMonicDecodable
    (P : (MvPolynomial (Fin n) R)[X]) (hP : P.Monic) (hd : P.natDegree = n)
    (hdecode : ∀ i : Fin n,
      MvPolynomial.X i ∈ Algebra.adjoin R (Set.range fun j : ℕ => P.coeff j)) :
    MvPolynomial (Fin n) R ≃ₐ[R] MvPolynomial (Fin n) R :=
  AlgEquiv.ofBijective (MvPolynomial.aeval (fun i : Fin n => P.coeff i))
    (coefficient_aeval_bijective_of_monic_decodable P hP hd hdecode)

end FreeParameters

end FastPoly
