import FastPoly.Examples.BarQ15Structural
import FastPoly.Examples.BarQGeneral
import FastPoly.Section6.Dispatch

/-!
# The barred-gadget dispatch endpoint

This file discharges `BarredGadgets`, the only abstract gadget hypothesis used by
the odd-degree dispatch.  There are exactly two branches:

* `m = 1` uses the optimized finite degree-15 circuit;
* `m >= 2` uses the uniform `barQ_{8m+7}` circuit and its explicit decoder.

Both decoders are relative to the subalgebra generated by the supplied quadratic
and quartic coefficients.  No Jacobian or search argument is used.
-/

namespace FastPoly

open Polynomial Algebra

variable {R A : Type*} [CommRing R] [CommRing A] [Algebra R A]

/-- The finite degree-15 decoder, recast in the `BarredGadgets` relative form. -/
private theorem barQ15_param_mem {V : Subalgebra R A} (H₂ H₄ : A[X])
    (θ : ℕ → A)
    (hH₂V : ∀ j, H₂.coeff j ∈ V) (hH₄V : ∀ j, H₄.coeff j ∈ V)
    (hQV : ∀ j, (BarQ15.barQ15 (H₂.coeff 0) (H₂.coeff 1)
      (H₄.coeff 0) (H₄.coeff 1) (H₄.coeff 2) (H₄.coeff 3) θ).coeff j ∈ V) :
    ∀ t, t < 15 → θ t ∈ V := by
  have hraw := BarQ15.barQ15_recover (R := R) V
    (H₂.coeff 0) (H₂.coeff 1)
    (H₄.coeff 0) (H₄.coeff 1) (H₄.coeff 2) (H₄.coeff 3) θ
    (hH₂V 0) (hH₂V 1) (hH₄V 0) (hH₄V 1) (hH₄V 2) (hH₄V 3)
  have hcollapse : BarQ15.barQ15Alg V
      (H₂.coeff 0) (H₂.coeff 1)
      (H₄.coeff 0) (H₄.coeff 1) (H₄.coeff 2) (H₄.coeff 3) θ ≤ V := by
    rw [BarQ15.barQ15Alg]
    exact sup_le le_rfl (adjoin_le (by rintro _ ⟨j, rfl⟩; exact hQV j))
  exact fun t ht => hcollapse (hraw t ht)

/-- Explicit realization of every barred gadget required below `cap`.

The admissibility assumption is intentionally stated only once, at the cap.  In
the uniform branch the decoder restricts it to the much smaller interval
`1,...,m`; the finite base does not need it at all.
-/
theorem barredGadgets_of_admissible [Nontrivial A] (cap : ℕ)
    (hadm : ∀ n : ℕ, 1 ≤ n → n ≤ cap → IsUnit (((n : ℕ) : ℤ) : R)) :
    BarredGadgets (R := R) (A := A) cap := by
  intro H2 H4 hH2m hH2d hH4m hH4d m hm1 hmcap theta
  by_cases hmone : m = 1
  · subst m
    let Q := BarQ15.barQ15 (H2.coeff 0) (H2.coeff 1)
      (H4.coeff 0) (H4.coeff 1) (H4.coeff 2) (H4.coeff 3) theta
    obtain ⟨hQm, hQd⟩ := BarQ15.barQ15_good (A := A)
      (H2.coeff 0) (H2.coeff 1)
      (H4.coeff 0) (H4.coeff 1) (H4.coeff 2) (H4.coeff 3) theta
    refine ⟨Q, hQm, ?_, ?_⟩
    · simpa only [Q] using hQd
    · intro V hH2V hH4V hQV t ht
      exact barQ15_param_mem H2 H4 theta hH2V hH4V
        (by simpa only [Q] using hQV) t (by omega)
  · have hm2 : 2 ≤ m := by omega
    let Q := BarQGeneral.gadget H2 H4 m theta
    obtain ⟨hQm, hQd⟩ := BarQGeneral.gadget_good hH2m hH2d hH4m hH4d m
      (by omega) theta
    refine ⟨Q, hQm, ?_, ?_⟩
    · simpa only [Q] using hQd
    · intro V hH2V hH4V hQV
      have hadm' : ∀ n : ℕ, 1 ≤ n → n ≤ m → IsUnit (((n : ℕ) : ℤ) : R) := by
        intro n hn1 hnm
        exact hadm n hn1 (by omega)
      exact BarQGeneral.gadget_recover hH2m hH2d hH4m hH4d m hm2 theta hadm'
        hH2V hH4V (by simpa only [Q] using hQV)

end FastPoly
