import FastPoly.Examples.Char2Triangular
import FastPoly.Examples.Char2Coefficients
import FastPoly.Examples.Char2Ring
import FastPoly.Cost.MultiplicationProgram
import Mathlib.Tactic.IntervalCases
import Mathlib.Tactic.FinCases
import FastPoly.Examples.Char2Frobenius

/-! Generated by tools/gen_char2_lean.py. Every identity is checked by Lean.
The website's degree-7 circuit, with explicit normalized coordinates.
Preprocessing is outside the online multiplication count. -/

namespace FastPoly.Char2Degree7
open Polynomial Char2Certificate

set_option maxRecDepth 8192
set_option maxHeartbeats 1000000
set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.unusedSectionVars false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

variable {F : Type*} [Field F] [CharP F 2] [PerfectRing F 2]

/-- Literal fixed shared circuit; its count is computed from syntax. -/
def circuit : Cost.Circuit F ℕ 1 :=
  .bind (.mul (.input (0)) (.add (.input (0)) (.input (1)))) (
  .bind (.mul (.add (.input (Sum.inl (0))) (.input (Sum.inl (2)))) (.add (.input (Sum.inr 0)) (.input (Sum.inl (3))))) (
  .bind (.mul (.input (Sum.inr 0)) (.add (.input (Sum.inr 0)) (.input (Sum.inl (Sum.inl (4)))))) (
  .bind (.mul (.add (.input (Sum.inl (Sum.inl (Sum.inl (0))))) (.input (Sum.inl (Sum.inl (Sum.inl (5)))))) (.add (.add (.input (Sum.inl (Sum.inl (Sum.inr 0)))) (.input (Sum.inr 0))) (.input (Sum.inl (Sum.inl (Sum.inl (6))))))) (
  (.add (.input (Sum.inr 0)) (.input (Sum.inl (Sum.inl (Sum.inl (Sum.inl (7)))))))))))

theorem multiplication_count : (circuit (F := F)).gates.multiplications = 4 := rfl

def program : Cost.MultiplicationProgram F ℕ 1 4 :=
  ⟨circuit, multiplication_count⟩

def offset_0 (q : ℕ → F) : F := q 1 + q 4

def offset_1 (q : ℕ → F) : F := q 4

def offset_2 (q : ℕ → F) : F := q 3 + q 1 * q 4 + (q 4) ^ 2

def offset_3 (q : ℕ → F) : F := q 2

def offset_4 (q : ℕ → F) : F := q 0

def offset_5 (q : ℕ → F) : F := q 5

def offset_6 (q : ℕ → F) : F := q 6

def offsets (q : ℕ → F) : ℕ → F
  | 0 => offset_0 q
  | 1 => offset_1 q
  | 2 => offset_2 q
  | 3 => offset_3 q
  | 4 => offset_4 q
  | 5 => offset_5 q
  | 6 => offset_6 q
  | _ + 7 => 0

def row_y_1 (q : ℕ → F) : F := q 1 + q 4

noncomputable def wire_y (a : ℕ → F) : F[X] := (X) * (X + C (a 0))

noncomputable def normal_y (q : ℕ → F) : F[X] :=
  C (row_y_1 q) * X ^ 1 +
    X ^ 2

theorem normal_y_degree (q : ℕ → F) : (normal_y q).natDegree ≤ 2 := by
  unfold normal_y
  exact (natDegree_add_le_of_degree_le (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega)) (le_trans (natDegree_X_pow_le _) (by omega)))

theorem wire_y_offsets (q : ℕ → F) : wire_y (offsets q) = normal_y q := by
  rw [wire_y]
  apply bounded_ext (d := 2)
  · exact le_trans natDegree_mul_le (Nat.add_le_add
      (show _ ≤ 1 from (by simp only [natDegree_X]; omega))
      (show _ ≤ 1 from (natDegree_add_le_of_degree_le (by simp only [natDegree_X]; omega) (by simp only [natDegree_C]; omega))))
  · exact normal_y_degree q
  · intro k hk
    interval_cases k <;>
      rw [coeff_mul] <;>
        (try simp only [Finset.Nat.sum_antidiagonal_eq_sum_range_succ_mk,
          Finset.sum_range_succ, Finset.sum_range_zero]) <;>
        norm_num only [normal_y,
          coeff_add, coeff_C_mul_X_pow, coeff_X_pow, coeff_X, coeff_C,
          ite_true, ite_false, zero_add, add_zero, zero_mul, mul_zero, one_mul, mul_one] <;>
        (try simp only [offsets, row_y_1, offset_0]) <;>
        ring_char2

def row_z_0 (q : ℕ → F) : F := q 3 * q 4 + q 1 * (q 4) ^ 2 + (q 4) ^ 3

def row_z_1 (q : ℕ → F) : F := q 3

def row_z_2 (q : ℕ → F) : F := q 1

noncomputable def wire_z (a : ℕ → F) : F[X] := (X + C (a 1)) * (wire_y a + C (a 2))

noncomputable def normal_z (q : ℕ → F) : F[X] :=
  C (row_z_0 q) +
    C (row_z_1 q) * X ^ 1 +
    C (row_z_2 q) * X ^ 2 +
    X ^ 3

theorem normal_z_degree (q : ℕ → F) : (normal_z q).natDegree ≤ 3 := by
  unfold normal_z
  exact (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (by simp only [natDegree_C]; omega) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_X_pow_le _) (by omega)))

theorem wire_z_offsets (q : ℕ → F) : wire_z (offsets q) = normal_z q := by
  rw [wire_z, wire_y_offsets]
  apply bounded_ext (d := 3)
  · exact le_trans natDegree_mul_le (Nat.add_le_add
      (show _ ≤ 1 from (natDegree_add_le_of_degree_le (by simp only [natDegree_X]; omega) (by simp only [natDegree_C]; omega)))
      (show _ ≤ 2 from (natDegree_add_le_of_degree_le (le_trans (normal_y_degree q) (by omega)) (by simp only [natDegree_C]; omega))))
  · exact normal_z_degree q
  · intro k hk
    interval_cases k <;>
      rw [coeff_mul] <;>
        (try simp only [Finset.Nat.sum_antidiagonal_eq_sum_range_succ_mk,
          Finset.sum_range_succ, Finset.sum_range_zero]) <;>
        norm_num only [normal_z, normal_y,
          coeff_add, coeff_C_mul_X_pow, coeff_X_pow, coeff_X, coeff_C,
          ite_true, ite_false, zero_add, add_zero, zero_mul, mul_zero, one_mul, mul_one] <;>
        (try simp only [offsets, row_z_0, row_z_1, row_z_2, row_y_1, offset_1, offset_2]) <;>
        ring_char2

def row_t_0 (q : ℕ → F) : F := q 2 * q 3 * q 4 + q 1 * q 2 * (q 4) ^ 2 + q 2 * (q 4) ^ 3 + (q 3) ^ 2 * (q 4) ^ 2 + (q 1) ^ 2 * (q 4) ^ 4 + (q 4) ^ 6

def row_t_1 (q : ℕ → F) : F := q 2 * q 3

def row_t_2 (q : ℕ → F) : F := q 1 * q 2 + (q 3) ^ 2

def row_t_3 (q : ℕ → F) : F := q 2

def row_t_4 (q : ℕ → F) : F := (q 1) ^ 2

noncomputable def wire_t (a : ℕ → F) : F[X] := (wire_z a) * (wire_z a + C (a 3))

noncomputable def normal_t (q : ℕ → F) : F[X] :=
  C (row_t_0 q) +
    C (row_t_1 q) * X ^ 1 +
    C (row_t_2 q) * X ^ 2 +
    C (row_t_3 q) * X ^ 3 +
    C (row_t_4 q) * X ^ 4 +
    X ^ 6

theorem normal_t_degree (q : ℕ → F) : (normal_t q).natDegree ≤ 6 := by
  unfold normal_t
  exact (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (by simp only [natDegree_C]; omega) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_X_pow_le _) (by omega)))

theorem wire_t_offsets (q : ℕ → F) : wire_t (offsets q) = normal_t q := by
  rw [wire_t, wire_z_offsets]
  apply bounded_ext (d := 6)
  · exact le_trans natDegree_mul_le (Nat.add_le_add
      (show _ ≤ 3 from (le_trans (normal_z_degree q) (by omega)))
      (show _ ≤ 3 from (natDegree_add_le_of_degree_le (le_trans (normal_z_degree q) (by omega)) (by simp only [natDegree_C]; omega))))
  · exact normal_t_degree q
  · intro k hk
    interval_cases k <;>
      rw [coeff_mul] <;>
        (try simp only [Finset.Nat.sum_antidiagonal_eq_sum_range_succ_mk,
          Finset.sum_range_succ, Finset.sum_range_zero]) <;>
        norm_num only [normal_t, normal_z,
          coeff_add, coeff_C_mul_X_pow, coeff_X_pow, coeff_X, coeff_C,
          ite_true, ite_false, zero_add, add_zero, zero_mul, mul_zero, one_mul, mul_one] <;>
        (try simp only [offsets, row_t_0, row_t_1, row_t_2, row_t_3, row_t_4, row_z_0, row_z_1, row_z_2, offset_3]) <;>
        ring_char2

def row_u_0 (q : ℕ → F) : F := q 0 * q 5 + q 0 * q 2 * q 3 * q 4 + q 0 * q 1 * q 2 * (q 4) ^ 2 + q 0 * q 2 * (q 4) ^ 3 + q 0 * (q 3) ^ 2 * (q 4) ^ 2 + q 0 * (q 1) ^ 2 * (q 4) ^ 4 + q 0 * (q 4) ^ 6

def row_u_1 (q : ℕ → F) : F := q 5 + q 0 * q 1 + q 0 * q 4 + q 0 * q 2 * q 3 + q 2 * q 3 * q 4 + q 1 * q 2 * (q 4) ^ 2 + q 2 * (q 4) ^ 3 + (q 3) ^ 2 * (q 4) ^ 2 + (q 1) ^ 2 * (q 4) ^ 4 + (q 4) ^ 6

def row_u_2 (q : ℕ → F) : F := q 0 + q 1 + q 4 + q 2 * q 3 + q 0 * q 1 * q 2 + q 0 * (q 3) ^ 2

def row_u_3 (q : ℕ → F) : F := 1 + q 0 * q 2 + q 1 * q 2 + (q 3) ^ 2

def row_u_4 (q : ℕ → F) : F := q 2 + q 0 * (q 1) ^ 2

def row_u_5 (q : ℕ → F) : F := (q 1) ^ 2

def row_u_6 (q : ℕ → F) : F := q 0

noncomputable def wire_u (a : ℕ → F) : F[X] := (X + C (a 4)) * (wire_y a + wire_t a + C (a 5))

noncomputable def normal_u (q : ℕ → F) : F[X] :=
  C (row_u_0 q) +
    C (row_u_1 q) * X ^ 1 +
    C (row_u_2 q) * X ^ 2 +
    C (row_u_3 q) * X ^ 3 +
    C (row_u_4 q) * X ^ 4 +
    C (row_u_5 q) * X ^ 5 +
    C (row_u_6 q) * X ^ 6 +
    X ^ 7

theorem normal_u_degree (q : ℕ → F) : (normal_u q).natDegree ≤ 7 := by
  unfold normal_u
  exact (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (by simp only [natDegree_C]; omega) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_X_pow_le _) (by omega)))

theorem wire_u_offsets (q : ℕ → F) : wire_u (offsets q) = normal_u q := by
  rw [wire_u, wire_y_offsets, wire_t_offsets]
  apply bounded_ext (d := 7)
  · exact le_trans natDegree_mul_le (Nat.add_le_add
      (show _ ≤ 1 from (natDegree_add_le_of_degree_le (by simp only [natDegree_X]; omega) (by simp only [natDegree_C]; omega)))
      (show _ ≤ 6 from (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (le_trans (normal_y_degree q) (by omega)) (le_trans (normal_t_degree q) (by omega))) (by simp only [natDegree_C]; omega))))
  · exact normal_u_degree q
  · intro k hk
    interval_cases k <;>
      rw [coeff_mul] <;>
        (try simp only [Finset.Nat.sum_antidiagonal_eq_sum_range_succ_mk,
          Finset.sum_range_succ, Finset.sum_range_zero]) <;>
        norm_num only [normal_u, normal_y, normal_t,
          coeff_add, coeff_C_mul_X_pow, coeff_X_pow, coeff_X, coeff_C,
          ite_true, ite_false, zero_add, add_zero, zero_mul, mul_zero, one_mul, mul_one] <;>
        (try simp only [offsets, row_u_0, row_u_1, row_u_2, row_u_3, row_u_4, row_u_5, row_u_6, row_y_1, row_t_0, row_t_1, row_t_2, row_t_3, row_t_4, offset_4, offset_5]) <;>
        ring_char2

noncomputable def polynomial (a : ℕ → F) : F[X] := wire_u a + C (a 6)

theorem program_eval (a : ℕ → F) :
    (program (F := F)).circuit.eval (fun i => if i = 0 then X else C (a (i-1))) 0 = polynomial a := rfl

def tail_0 (q : ℕ → F) : F := 0

def tail_1 (q : ℕ → F) : F := 0

def tail_2 (q : ℕ → F) : F := q 0 * (q 1) ^ 2

def tail_3 (q : ℕ → F) : F := 1 + q 0 * q 2 + q 1 * q 2

def tail_4 (q : ℕ → F) : F := q 0 + q 1 + q 2 * q 3 + q 0 * q 1 * q 2 + q 0 * (q 3) ^ 2

def tail_5 (q : ℕ → F) : F := q 0 * q 1 + q 0 * q 4 + q 0 * q 2 * q 3 + q 2 * q 3 * q 4 + q 1 * q 2 * (q 4) ^ 2 + q 2 * (q 4) ^ 3 + (q 3) ^ 2 * (q 4) ^ 2 + (q 1) ^ 2 * (q 4) ^ 4 + (q 4) ^ 6

def tail_6 (q : ℕ → F) : F := q 0 * q 5 + q 0 * q 2 * q 3 * q 4 + q 0 * q 1 * q 2 * (q 4) ^ 2 + q 0 * q 2 * (q 4) ^ 3 + q 0 * (q 3) ^ 2 * (q 4) ^ 2 + q 0 * (q 1) ^ 2 * (q 4) ^ 4 + q 0 * (q 4) ^ 6

def tail (i : ℕ) (q : ℕ → F) : F :=
  match i with
  | 0 => tail_0 q
  | 1 => tail_1 q
  | 2 => tail_2 q
  | 3 => tail_3 q
  | 4 => tail_4 q
  | 5 => tail_5 q
  | 6 => tail_6 q
  | _ + 7 => 0

theorem tail_causal : Causal 7 (tail (F := F)) := by
  intro i hi q r h
  interval_cases i
  · simp only [tail, tail_0]
  · simp only [tail, tail_1]
  · simp only [tail, tail_2, h 0 (by omega), h 1 (by omega)]
  · simp only [tail, tail_3, h 0 (by omega), h 1 (by omega), h 2 (by omega)]
  · simp only [tail, tail_4, h 0 (by omega), h 1 (by omega), h 2 (by omega), h 3 (by omega)]
  · simp only [tail, tail_5, h 0 (by omega), h 1 (by omega), h 2 (by omega), h 3 (by omega), h 4 (by omega)]
  · simp only [tail, tail_6, h 0 (by omega), h 1 (by omega), h 2 (by omega), h 3 (by omega), h 4 (by omega), h 5 (by omega)]

noncomputable def pivot (i : ℕ) : F ≃ F :=
  match i with
  | 1 => frobeniusPivot 1
  | 3 => frobeniusPivot 1
  | _ => Equiv.refl F


def rows : Fin 7 ≃ Fin 7 where
  toFun := ![6, 5, 4, 3, 2, 1, 0]
  invFun := ![6, 5, 4, 3, 2, 1, 0]
  left_inv i := by fin_cases i <;> rfl
  right_inv i := by fin_cases i <;> rfl

noncomputable def coefficients : (Fin 7 → F) ≃ (Fin 7 → F) :=
  coefficientEquiv pivot tail tail_causal rows

noncomputable def family (q : Fin 7 → F) : F[X] := polynomial (offsets (extendFin q))

theorem family_normal (q : Fin 7 → F) :
    family q = monicOfCoefficients (coefficients q) := by
  rw [family, polynomial, wire_u_offsets]
  simp only [monicOfCoefficients, Finset.sum_range_succ, Finset.sum_range_zero]
  change _ = X ^ 7 + (0 + C (pivot 6 (extendFin q 6) + tail 6 (extendFin q)) * X ^ 0 + C (pivot 5 (extendFin q 5) + tail 5 (extendFin q)) * X ^ 1 + C (pivot 4 (extendFin q 4) + tail 4 (extendFin q)) * X ^ 2 + C (pivot 3 (extendFin q 3) + tail 3 (extendFin q)) * X ^ 3 + C (pivot 2 (extendFin q 2) + tail 2 (extendFin q)) * X ^ 4 + C (pivot 1 (extendFin q 1) + tail 1 (extendFin q)) * X ^ 5 + C (pivot 0 (extendFin q 0) + tail 0 (extendFin q)) * X ^ 6)
  apply bounded_ext (d := 7)
  · exact (natDegree_add_le_of_degree_le (le_trans (normal_u_degree (extendFin q)) (by omega)) (by simp only [natDegree_C]; omega))
  · exact (natDegree_add_le_of_degree_le (le_trans (natDegree_X_pow_le _) (by omega)) (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (by simp only [natDegree_zero]; omega) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))))
  · intro k hk
    interval_cases k <;>
      norm_num only [normal_u,
        coeff_add, coeff_C_mul_X_pow, coeff_X_pow, coeff_C, coeff_zero,
        ite_true, ite_false, zero_add, add_zero, zero_mul, mul_zero, one_mul, mul_one] <;>
      (try simp only [offsets, offset_6, tail, tail_0, tail_1, tail_2, tail_3, tail_4, tail_5, tail_6, pivot, Equiv.refl_apply, frobeniusPivot_apply, Nat.reducePow, row_u_0, row_u_1, row_u_2, row_u_3, row_u_4, row_u_5, row_u_6]) <;>
      ring_char2

theorem evaluation_bijective (x : Fin 7 → F) (hx : Function.Injective x) :
    Function.Bijective (fun q => fun i => (family q).eval (x i)) :=
  Char2Certificate.evaluation_bijective (by omega) _ tail tail_causal rows family family_normal x hx

/-- Preprocessed gate offsets for any requested monic polynomial. -/
noncomputable def decode (c : Fin 7 → F) : ℕ → F := offsets (extendFin (coefficients.symm c))

theorem decode_correct (c : Fin 7 → F) :
    polynomial (decode c) = monicOfCoefficients c := by
  have h := family_normal (coefficients.symm c)
  simpa only [family, decode, Equiv.apply_symm_apply] using h

/-- The same literal counted circuit realizes every prescribed coefficient vector. -/
theorem program_decode_correct (c : Fin 7 → F) :
    (program (F := F)).circuit.eval
      (fun i => if i = 0 then X else C (decode c (i-1))) 0 = monicOfCoefficients c :=
  (program_eval (decode c)).trans (decode_correct c)

end FastPoly.Char2Degree7
