import FastPoly.Examples.Char2Triangular
import FastPoly.Examples.Char2Coefficients
import FastPoly.Examples.Char2Ring
import FastPoly.Cost.MultiplicationProgram
import Mathlib.Tactic.IntervalCases
import Mathlib.Tactic.FinCases

/-! Generated by tools/gen_char2_lean.py. Every identity is checked by Lean.
The website's degree-15 circuit, with explicit normalized coordinates.
Preprocessing is outside the online multiplication count. -/

namespace FastPoly.Char2Degree15
open Polynomial Char2Certificate

set_option maxRecDepth 8192
set_option maxHeartbeats 1000000
set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.unusedSectionVars false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

variable {F : Type*} [Field F] [CharP F 2]

/-- Literal fixed shared circuit; its count is computed from syntax. -/
def circuit : Cost.Circuit F ℕ 1 :=
  .bind (.mul (.input (0)) (.input (0))) (
  .bind (.mul (.add (.input (Sum.inr 0)) (.input (Sum.inl (1)))) (.add (.add (.input (Sum.inl (0))) (.input (Sum.inr 0))) (.input (Sum.inl (2))))) (
  .bind (.mul (.add (.input (Sum.inl (Sum.inl (0)))) (.input (Sum.inl (Sum.inl (3))))) (.add (.input (Sum.inr 0)) (.input (Sum.inl (Sum.inl (4)))))) (
  .bind (.mul (.add (.add (.input (Sum.inl (Sum.inl (Sum.inr 0)))) (.input (Sum.inr 0))) (.input (Sum.inl (Sum.inl (Sum.inl (5)))))) (.add (.add (.input (Sum.inl (Sum.inr 0))) (.input (Sum.inr 0))) (.input (Sum.inl (Sum.inl (Sum.inl (6))))))) (
  .bind (.mul (.add (.add (.input (Sum.inl (Sum.inl (Sum.inl (Sum.inl (0)))))) (.input (Sum.inl (Sum.inl (Sum.inr 0))))) (.input (Sum.inl (Sum.inl (Sum.inl (Sum.inl (7))))))) (.add (.input (Sum.inl (Sum.inl (Sum.inr 0)))) (.input (Sum.inl (Sum.inl (Sum.inl (Sum.inl (8)))))))) (
  .bind (.mul (.add (.add (.add (.input (Sum.inl (Sum.inl (Sum.inl (Sum.inl (Sum.inl (0))))))) (.input (Sum.inl (Sum.inl (Sum.inl (Sum.inl (Sum.inr 0))))))) (.input (Sum.inl (Sum.inl (Sum.inl (Sum.inr 0)))))) (.input (Sum.inl (Sum.inl (Sum.inl (Sum.inl (Sum.inl (9)))))))) (.add (.add (.input (Sum.inl (Sum.inl (Sum.inl (Sum.inl (Sum.inr 0)))))) (.input (Sum.inr 0))) (.input (Sum.inl (Sum.inl (Sum.inl (Sum.inl (Sum.inl (10))))))))) (
  .bind (.mul (.add (.input (Sum.inl (Sum.inl (Sum.inl (Sum.inl (Sum.inr 0)))))) (.input (Sum.inl (Sum.inl (Sum.inl (Sum.inl (Sum.inl (Sum.inl (11))))))))) (.add (.input (Sum.inl (Sum.inr 0))) (.input (Sum.inl (Sum.inl (Sum.inl (Sum.inl (Sum.inl (Sum.inl (12)))))))))) (
  .bind (.mul (.add (.input (Sum.inl (Sum.inl (Sum.inl (Sum.inl (Sum.inr 0)))))) (.input (Sum.inl (Sum.inl (Sum.inl (Sum.inl (Sum.inl (Sum.inl (Sum.inl (13)))))))))) (.add (.input (Sum.inl (Sum.inl (Sum.inl (Sum.inr 0))))) (.input (Sum.inl (Sum.inl (Sum.inl (Sum.inl (Sum.inl (Sum.inl (Sum.inl (14))))))))))) (
  (.add (.add (.add (.input (Sum.inl (Sum.inl (Sum.inr 0)))) (.input (Sum.inl (Sum.inr 0)))) (.input (Sum.inr 0))) (.input (Sum.inl (Sum.inl (Sum.inl (Sum.inl (Sum.inl (Sum.inl (Sum.inl (Sum.inl (15)))))))))))))))))))

theorem multiplication_count : (circuit (F := F)).gates.multiplications = 8 := rfl

def program : Cost.MultiplicationProgram F ℕ 1 8 :=
  ⟨circuit, multiplication_count⟩

def offset_0 (q : ℕ → F) : F := q 2

def offset_1 (q : ℕ → F) : F := q 1 + q 2

def offset_2 (q : ℕ → F) : F := q 0

def offset_3 (q : ℕ → F) : F := q 3

def offset_4 (q : ℕ → F) : F := q 4 + q 5 + q 7

def offset_5 (q : ℕ → F) : F := q 5

def offset_6 (q : ℕ → F) : F := q 8 + q 11

def offset_7 (q : ℕ → F) : F := q 11

def offset_8 (q : ℕ → F) : F := q 6 + q 12 + q 13

def offset_9 (q : ℕ → F) : F := q 13

def offset_10 (q : ℕ → F) : F := q 12 + q 13

def offset_11 (q : ℕ → F) : F := q 10 + q 13

def offset_12 (q : ℕ → F) : F := q 7

def offset_13 (q : ℕ → F) : F := q 9

def offset_14 (q : ℕ → F) : F := q 14

def offsets (q : ℕ → F) : ℕ → F
  | 0 => offset_0 q
  | 1 => offset_1 q
  | 2 => offset_2 q
  | 3 => offset_3 q
  | 4 => offset_4 q
  | 5 => offset_5 q
  | 6 => offset_6 q
  | 7 => offset_7 q
  | 8 => offset_8 q
  | 9 => offset_9 q
  | 10 => offset_10 q
  | 11 => offset_11 q
  | 12 => offset_12 q
  | 13 => offset_13 q
  | 14 => offset_14 q
  | _ + 15 => 0

noncomputable def wire_y (a : ℕ → F) : F[X] := (X) * (X)

noncomputable def normal_y (q : ℕ → F) : F[X] :=
  X ^ 2

theorem normal_y_degree (q : ℕ → F) : (normal_y q).natDegree ≤ 2 := by
  unfold normal_y
  exact (le_trans (natDegree_X_pow_le _) (by omega))

theorem wire_y_offsets (q : ℕ → F) : wire_y (offsets q) = normal_y q := by
  rw [wire_y]
  apply bounded_ext (d := 2)
  · exact le_trans natDegree_mul_le (Nat.add_le_add
      (show _ ≤ 1 from (by simp only [natDegree_X]; omega))
      (show _ ≤ 1 from (by simp only [natDegree_X]; omega)))
  · exact normal_y_degree q
  · intro k hk
    interval_cases k <;>
      rw [coeff_mul] <;>
        (try simp only [Finset.Nat.sum_antidiagonal_eq_sum_range_succ_mk,
          Finset.sum_range_succ, Finset.sum_range_zero]) <;>
        norm_num only [normal_y,
          coeff_add, coeff_C_mul_X_pow, coeff_X_pow, coeff_X, coeff_C,
          ite_true, ite_false, zero_add, add_zero, zero_mul, mul_zero, one_mul, mul_one] <;>
        (try simp only [offsets]) <;>
        ring_char2

def row_z_0 (q : ℕ → F) : F := q 1 * q 2 + (q 2) ^ 2

def row_z_1 (q : ℕ → F) : F := q 2

def row_z_2 (q : ℕ → F) : F := q 1

noncomputable def wire_z (a : ℕ → F) : F[X] := (wire_y a + C (a 0)) * (X + wire_y a + C (a 1))

noncomputable def normal_z (q : ℕ → F) : F[X] :=
  C (row_z_0 q) +
    C (row_z_1 q) * X ^ 1 +
    C (row_z_2 q) * X ^ 2 +
    X ^ 3 +
    X ^ 4

theorem normal_z_degree (q : ℕ → F) : (normal_z q).natDegree ≤ 4 := by
  unfold normal_z
  exact (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (by simp only [natDegree_C]; omega) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_X_pow_le _) (by omega))) (le_trans (natDegree_X_pow_le _) (by omega)))

theorem wire_z_offsets (q : ℕ → F) : wire_z (offsets q) = normal_z q := by
  rw [wire_z, wire_y_offsets]
  apply bounded_ext (d := 4)
  · exact le_trans natDegree_mul_le (Nat.add_le_add
      (show _ ≤ 2 from (natDegree_add_le_of_degree_le (le_trans (normal_y_degree q) (by omega)) (by simp only [natDegree_C]; omega)))
      (show _ ≤ 2 from (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (by simp only [natDegree_X]; omega) (le_trans (normal_y_degree q) (by omega))) (by simp only [natDegree_C]; omega))))
  · exact normal_z_degree q
  · intro k hk
    interval_cases k <;>
      rw [coeff_mul] <;>
        (try simp only [Finset.Nat.sum_antidiagonal_eq_sum_range_succ_mk,
          Finset.sum_range_succ, Finset.sum_range_zero]) <;>
        norm_num only [normal_z, normal_y,
          coeff_add, coeff_C_mul_X_pow, coeff_X_pow, coeff_X, coeff_C,
          ite_true, ite_false, zero_add, add_zero, zero_mul, mul_zero, one_mul, mul_one] <;>
        (try simp only [offsets, row_z_0, row_z_1, row_z_2, offset_0, offset_1]) <;>
        ring_char2

def row_t_0 (q : ℕ → F) : F := q 0 * q 3 + q 0 * q 1 * q 2 + q 0 * (q 2) ^ 2

def row_t_1 (q : ℕ → F) : F := q 3 + q 0 * q 2 + q 1 * q 2 + (q 2) ^ 2

def row_t_2 (q : ℕ → F) : F := q 2 + q 0 * q 1

def row_t_3 (q : ℕ → F) : F := q 0 + q 1

def row_t_4 (q : ℕ → F) : F := 1 + q 0

noncomputable def wire_t (a : ℕ → F) : F[X] := (X + C (a 2)) * (wire_z a + C (a 3))

noncomputable def normal_t (q : ℕ → F) : F[X] :=
  C (row_t_0 q) +
    C (row_t_1 q) * X ^ 1 +
    C (row_t_2 q) * X ^ 2 +
    C (row_t_3 q) * X ^ 3 +
    C (row_t_4 q) * X ^ 4 +
    X ^ 5

theorem normal_t_degree (q : ℕ → F) : (normal_t q).natDegree ≤ 5 := by
  unfold normal_t
  exact (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (by simp only [natDegree_C]; omega) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_X_pow_le _) (by omega)))

theorem wire_t_offsets (q : ℕ → F) : wire_t (offsets q) = normal_t q := by
  rw [wire_t, wire_z_offsets]
  apply bounded_ext (d := 5)
  · exact le_trans natDegree_mul_le (Nat.add_le_add
      (show _ ≤ 1 from (natDegree_add_le_of_degree_le (by simp only [natDegree_X]; omega) (by simp only [natDegree_C]; omega)))
      (show _ ≤ 4 from (natDegree_add_le_of_degree_le (le_trans (normal_z_degree q) (by omega)) (by simp only [natDegree_C]; omega))))
  · exact normal_t_degree q
  · intro k hk
    interval_cases k <;>
      rw [coeff_mul] <;>
        (try simp only [Finset.Nat.sum_antidiagonal_eq_sum_range_succ_mk,
          Finset.sum_range_succ, Finset.sum_range_zero]) <;>
        norm_num only [normal_t, normal_z,
          coeff_add, coeff_C_mul_X_pow, coeff_X_pow, coeff_X, coeff_C,
          ite_true, ite_false, zero_add, add_zero, zero_mul, mul_zero, one_mul, mul_one] <;>
        (try simp only [offsets, row_t_0, row_t_1, row_t_2, row_t_3, row_t_4, row_z_0, row_z_1, row_z_2, offset_2, offset_3]) <;>
        ring_char2

def row_u_0 (q : ℕ → F) : F := q 4 * q 5 + q 5 * q 7 + (q 5) ^ 2 + q 0 * q 3 * q 4 + q 0 * q 3 * q 7 + q 1 * q 2 * q 4 + q 1 * q 2 * q 5 + q 1 * q 2 * q 7 + (q 2) ^ 2 * q 4 + (q 2) ^ 2 * q 5 + (q 2) ^ 2 * q 7 + q 0 * q 1 * q 2 * q 3 + q 0 * q 1 * q 2 * q 4 + q 0 * q 1 * q 2 * q 7 + q 0 * (q 2) ^ 2 * q 3 + q 0 * (q 2) ^ 2 * q 4 + q 0 * (q 2) ^ 2 * q 7 + (q 0) ^ 2 * (q 3) ^ 2 + q 0 * (q 1) ^ 2 * (q 2) ^ 2 + q 0 * (q 2) ^ 4 + (q 0) ^ 2 * (q 1) ^ 2 * (q 2) ^ 2 + (q 0) ^ 2 * (q 2) ^ 4

def row_u_1 (q : ℕ → F) : F := q 2 * q 4 + q 2 * q 5 + q 2 * q 7 + q 3 * q 4 + q 3 * q 7 + q 0 * q 2 * q 3 + q 0 * q 2 * q 4 + q 0 * q 2 * q 7 + q 1 * q 2 * q 3 + q 1 * q 2 * q 4 + q 1 * q 2 * q 7 + (q 2) ^ 2 * q 3 + (q 2) ^ 2 * q 4 + (q 2) ^ 2 * q 7 + (q 1) ^ 2 * (q 2) ^ 2 + (q 2) ^ 4

def row_u_2 (q : ℕ → F) : F := q 5 + q 0 * q 3 + q 1 * q 2 + q 1 * q 4 + q 1 * q 5 + q 1 * q 7 + q 2 * q 3 + q 2 * q 4 + q 2 * q 7 + (q 2) ^ 2 + (q 3) ^ 2 + q 0 * q 1 * q 2 + q 0 * q 1 * q 3 + q 0 * q 1 * q 4 + q 0 * q 1 * q 7 + (q 0) ^ 2 * (q 2) ^ 2 + (q 1) ^ 2 * (q 2) ^ 2 + (q 2) ^ 4

def row_u_3 (q : ℕ → F) : F := q 2 + q 3 + q 4 + q 5 + q 7 + q 0 * q 2 + q 0 * q 3 + q 0 * q 4 + q 0 * q 7 + q 1 * q 2 + q 1 * q 3 + q 1 * q 4 + q 1 * q 7

def row_u_4 (q : ℕ → F) : F := q 1 + q 2 + q 3 + q 5 + q 0 * q 1 + q 0 * q 3 + q 0 * q 4 + q 0 * q 7 + (q 2) ^ 2 + q 0 * (q 1) ^ 2 + (q 0) ^ 2 * (q 1) ^ 2

def row_u_5 (q : ℕ → F) : F := 1 + q 0 + q 1 + q 3 + q 4 + q 7 + (q 1) ^ 2

def row_u_6 (q : ℕ → F) : F := (q 0) ^ 2 + (q 1) ^ 2

def row_u_8 (q : ℕ → F) : F := 1 + q 0 + (q 0) ^ 2

noncomputable def wire_u (a : ℕ → F) : F[X] := (wire_y a + wire_t a + C (a 4)) * (wire_z a + wire_t a + C (a 5))

noncomputable def normal_u (q : ℕ → F) : F[X] :=
  C (row_u_0 q) +
    C (row_u_1 q) * X ^ 1 +
    C (row_u_2 q) * X ^ 2 +
    C (row_u_3 q) * X ^ 3 +
    C (row_u_4 q) * X ^ 4 +
    C (row_u_5 q) * X ^ 5 +
    C (row_u_6 q) * X ^ 6 +
    C (row_u_8 q) * X ^ 8 +
    X ^ 9 +
    X ^ 10

theorem normal_u_degree (q : ℕ → F) : (normal_u q).natDegree ≤ 10 := by
  unfold normal_u
  exact (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (by simp only [natDegree_C]; omega) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_X_pow_le _) (by omega))) (le_trans (natDegree_X_pow_le _) (by omega)))

theorem wire_u_offsets (q : ℕ → F) : wire_u (offsets q) = normal_u q := by
  rw [wire_u, wire_y_offsets, wire_t_offsets, wire_z_offsets]
  apply bounded_ext (d := 10)
  · exact le_trans natDegree_mul_le (Nat.add_le_add
      (show _ ≤ 5 from (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (le_trans (normal_y_degree q) (by omega)) (le_trans (normal_t_degree q) (by omega))) (by simp only [natDegree_C]; omega)))
      (show _ ≤ 5 from (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (le_trans (normal_z_degree q) (by omega)) (le_trans (normal_t_degree q) (by omega))) (by simp only [natDegree_C]; omega))))
  · exact normal_u_degree q
  · intro k hk
    interval_cases k <;>
      rw [coeff_mul] <;>
        (try simp only [Finset.Nat.sum_antidiagonal_eq_sum_range_succ_mk,
          Finset.sum_range_succ, Finset.sum_range_zero]) <;>
        norm_num only [normal_u, normal_y, normal_t, normal_z,
          coeff_add, coeff_C_mul_X_pow, coeff_X_pow, coeff_X, coeff_C,
          ite_true, ite_false, zero_add, add_zero, zero_mul, mul_zero, one_mul, mul_one] <;>
        (try simp only [offsets, row_u_0, row_u_1, row_u_2, row_u_3, row_u_4, row_u_5, row_u_6, row_u_8, row_t_0, row_t_1, row_t_2, row_t_3, row_t_4, row_z_0, row_z_1, row_z_2, offset_4, offset_5]) <;>
        ring_char2

def row_v_0 (q : ℕ → F) : F := q 8 * q 11 + (q 11) ^ 2 + q 1 * q 2 * q 8 + (q 2) ^ 2 * q 8 + (q 1) ^ 2 * (q 2) ^ 2 + (q 2) ^ 4

def row_v_1 (q : ℕ → F) : F := q 11 + q 1 * q 2 + q 2 * q 8 + (q 2) ^ 2

def row_v_2 (q : ℕ → F) : F := q 2 + q 1 * q 8 + (q 2) ^ 2

def row_v_3 (q : ℕ → F) : F := q 1 + q 8

def row_v_4 (q : ℕ → F) : F := 1 + q 8 + (q 1) ^ 2

noncomputable def wire_v (a : ℕ → F) : F[X] := (X + wire_z a + C (a 6)) * (wire_z a + C (a 7))

noncomputable def normal_v (q : ℕ → F) : F[X] :=
  C (row_v_0 q) +
    C (row_v_1 q) * X ^ 1 +
    C (row_v_2 q) * X ^ 2 +
    C (row_v_3 q) * X ^ 3 +
    C (row_v_4 q) * X ^ 4 +
    X ^ 5 +
    X ^ 6 +
    X ^ 8

theorem normal_v_degree (q : ℕ → F) : (normal_v q).natDegree ≤ 8 := by
  unfold normal_v
  exact (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (by simp only [natDegree_C]; omega) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_X_pow_le _) (by omega))) (le_trans (natDegree_X_pow_le _) (by omega))) (le_trans (natDegree_X_pow_le _) (by omega)))

theorem wire_v_offsets (q : ℕ → F) : wire_v (offsets q) = normal_v q := by
  rw [wire_v, wire_z_offsets]
  apply bounded_ext (d := 8)
  · exact le_trans natDegree_mul_le (Nat.add_le_add
      (show _ ≤ 4 from (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (by simp only [natDegree_X]; omega) (le_trans (normal_z_degree q) (by omega))) (by simp only [natDegree_C]; omega)))
      (show _ ≤ 4 from (natDegree_add_le_of_degree_le (le_trans (normal_z_degree q) (by omega)) (by simp only [natDegree_C]; omega))))
  · exact normal_v_degree q
  · intro k hk
    interval_cases k <;>
      rw [coeff_mul] <;>
        (try simp only [Finset.Nat.sum_antidiagonal_eq_sum_range_succ_mk,
          Finset.sum_range_succ, Finset.sum_range_zero]) <;>
        norm_num only [normal_v, normal_z,
          coeff_add, coeff_C_mul_X_pow, coeff_X_pow, coeff_X, coeff_C,
          ite_true, ite_false, zero_add, add_zero, zero_mul, mul_zero, one_mul, mul_one] <;>
        (try simp only [offsets, row_v_0, row_v_1, row_v_2, row_v_3, row_v_4, row_z_0, row_z_1, row_z_2, offset_6, offset_7]) <;>
        ring_char2

def row_w_0 (q : ℕ → F) : F := (q 6 * q 13 + q 12 * q 13 + (q 13) ^ 2 + (q 2) ^ 2 * q 13 + q 6 * q 8 * q 11 + q 6 * (q 11) ^ 2 + q 8 * q 11 * q 12 + q 8 * q 11 * q 13 + (q 11) ^ 2 * q 12 + (q 11) ^ 2 * q 13 + (q 2) ^ 2 * q 6 * q 8 + (q 2) ^ 2 * q 8 * q 11 + (q 2) ^ 2 * q 8 * q 12 + (q 2) ^ 2 * q 8 * q 13 + (q 2) ^ 2 * (q 11) ^ 2 + (q 2) ^ 4 * q 6 + (q 2) ^ 4 * q 8 + (q 2) ^ 4 * q 12 + (q 2) ^ 4 * q 13 + (q 2) ^ 6) + ((q 2 * q 13 + q 2 * q 6 * q 8 + q 2 * q 8 * q 11 + q 2 * q 8 * q 12 + q 2 * q 8 * q 13 + q 2 * (q 11) ^ 2 + (q 2) ^ 5) * q 1) + (((q 2) ^ 2 * q 6 + (q 2) ^ 2 * q 8 + (q 2) ^ 2 * q 12 + (q 2) ^ 2 * q 13 + (q 2) ^ 4) * (q 1) ^ 2) + (((q 2) ^ 3) * (q 1) ^ 3)

def row_w_1 (q : ℕ → F) : F := q 13 + q 2 * q 13 + q 6 * q 11 + q 8 * q 11 + q 11 * q 12 + q 11 * q 13 + (q 11) ^ 2 + q 1 * q 2 * q 6 + q 1 * q 2 * q 8 + q 1 * q 2 * q 11 + q 1 * q 2 * q 12 + q 1 * q 2 * q 13 + q 2 * q 6 * q 8 + q 2 * q 8 * q 11 + q 2 * q 8 * q 12 + q 2 * q 8 * q 13 + q 2 * (q 11) ^ 2 + (q 2) ^ 2 * q 6 + (q 2) ^ 2 * q 8 + (q 2) ^ 2 * q 11 + (q 2) ^ 2 * q 12 + (q 2) ^ 2 * q 13 + (q 1) ^ 2 * (q 2) ^ 3 + (q 2) ^ 5

def row_w_2 (q : ℕ → F) : F := q 6 + q 11 + q 12 + q 1 * q 13 + q 2 * q 6 + q 2 * q 8 + q 2 * q 11 + q 2 * q 12 + q 2 * q 13 + q 8 * q 11 + (q 11) ^ 2 + q 1 * q 2 * q 8 + q 1 * q 6 * q 8 + q 1 * q 8 * q 11 + q 1 * q 8 * q 12 + q 1 * q 8 * q 13 + q 1 * (q 11) ^ 2 + (q 2) ^ 2 * q 6 + (q 2) ^ 2 * q 12 + (q 2) ^ 2 * q 13 + q 1 * (q 2) ^ 3 + (q 1) ^ 2 * (q 2) ^ 2 + q 1 * (q 2) ^ 4 + (q 1) ^ 3 * (q 2) ^ 2

def row_w_3 (q : ℕ → F) : F := 1 + q 11 + q 13 + q 1 * q 2 + q 1 * q 6 + q 1 * q 8 + q 1 * q 11 + q 1 * q 12 + q 1 * q 13 + q 2 * q 8 + (q 2) ^ 2 + q 6 * q 8 + q 8 * q 11 + q 8 * q 12 + q 8 * q 13 + (q 11) ^ 2 + (q 2) ^ 3 + (q 1) ^ 2 * (q 2) ^ 2 + (q 2) ^ 4

def row_w_4 (q : ℕ → F) : F := 1 + q 2 + q 6 + q 8 + q 11 + q 12 + q 1 * q 8 + (q 2) ^ 2 + q 6 * q 8 + q 8 * q 11 + q 8 * q 12 + q 8 * q 13 + (q 11) ^ 2 + q 1 * (q 2) ^ 2 + (q 1) ^ 2 * q 6 + (q 1) ^ 2 * q 8 + (q 1) ^ 2 * q 12 + (q 1) ^ 2 * q 13 + (q 1) ^ 3 * q 2 + (q 2) ^ 4

def row_w_5 (q : ℕ → F) : F := q 1 + q 6 + q 11 + q 12 + q 13 + (q 2) ^ 2 + (q 1) ^ 2 * q 2

def row_w_6 (q : ℕ → F) : F := 1 + q 6 + q 12 + q 13 + q 1 * q 2 + (q 1) ^ 2 + (q 1) ^ 3

def row_w_7 (q : ℕ → F) : F := 1 + q 2 + (q 1) ^ 2

def row_w_8 (q : ℕ → F) : F := 1 + q 1 + q 6 + q 8 + q 12 + q 13 + q 1 * q 2 + (q 1) ^ 2 + (q 2) ^ 2

def row_w_9 (q : ℕ → F) : F := 1 + q 2

def row_w_10 (q : ℕ → F) : F := q 1

noncomputable def wire_w (a : ℕ → F) : F[X] := (X + wire_y a + wire_z a + C (a 8)) * (wire_y a + wire_v a + C (a 9))

noncomputable def normal_w (q : ℕ → F) : F[X] :=
  C (row_w_0 q) +
    C (row_w_1 q) * X ^ 1 +
    C (row_w_2 q) * X ^ 2 +
    C (row_w_3 q) * X ^ 3 +
    C (row_w_4 q) * X ^ 4 +
    C (row_w_5 q) * X ^ 5 +
    C (row_w_6 q) * X ^ 6 +
    C (row_w_7 q) * X ^ 7 +
    C (row_w_8 q) * X ^ 8 +
    C (row_w_9 q) * X ^ 9 +
    C (row_w_10 q) * X ^ 10 +
    X ^ 11 +
    X ^ 12

theorem normal_w_degree (q : ℕ → F) : (normal_w q).natDegree ≤ 12 := by
  unfold normal_w
  exact (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (by simp only [natDegree_C]; omega) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_X_pow_le _) (by omega))) (le_trans (natDegree_X_pow_le _) (by omega)))

theorem wire_w_offsets (q : ℕ → F) : wire_w (offsets q) = normal_w q := by
  rw [wire_w, wire_y_offsets, wire_z_offsets, wire_v_offsets]
  apply bounded_ext (d := 12)
  · exact le_trans natDegree_mul_le (Nat.add_le_add
      (show _ ≤ 4 from (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (by simp only [natDegree_X]; omega) (le_trans (normal_y_degree q) (by omega))) (le_trans (normal_z_degree q) (by omega))) (by simp only [natDegree_C]; omega)))
      (show _ ≤ 8 from (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (le_trans (normal_y_degree q) (by omega)) (le_trans (normal_v_degree q) (by omega))) (by simp only [natDegree_C]; omega))))
  · exact normal_w_degree q
  · intro k hk
    interval_cases k <;>
      rw [coeff_mul] <;>
        (try simp only [Finset.Nat.sum_antidiagonal_eq_sum_range_succ_mk,
          Finset.sum_range_succ, Finset.sum_range_zero]) <;>
        norm_num only [normal_w, normal_y, normal_z, normal_v,
          coeff_add, coeff_C_mul_X_pow, coeff_X_pow, coeff_X, coeff_C,
          ite_true, ite_false, zero_add, add_zero, zero_mul, mul_zero, one_mul, mul_one] <;>
        (try simp only [offsets, row_w_0, row_w_1, row_w_2, row_w_3, row_w_4, row_w_5, row_w_6, row_w_7, row_w_8, row_w_9, row_w_10, row_z_0, row_z_1, row_z_2, row_v_0, row_v_1, row_v_2, row_v_3, row_v_4, offset_8, offset_9]) <;>
        ring_char2

def row_s_0 (q : ℕ → F) : F := (q 10 * q 12 + q 10 * q 13 + q 12 * q 13 + (q 13) ^ 2 + (q 2) ^ 2 * q 10 + (q 2) ^ 2 * q 13 + q 8 * q 11 * q 12 + q 8 * q 11 * q 13 + (q 11) ^ 2 * q 12 + (q 11) ^ 2 * q 13 + (q 2) ^ 2 * q 8 * q 11 + (q 2) ^ 2 * q 8 * q 12 + (q 2) ^ 2 * q 8 * q 13 + (q 2) ^ 2 * (q 11) ^ 2 + (q 2) ^ 4 * q 8 + (q 2) ^ 4 * q 12 + (q 2) ^ 4 * q 13 + (q 2) ^ 6) + ((q 2 * q 10 + q 2 * q 13 + q 2 * q 8 * q 11 + q 2 * q 8 * q 12 + q 2 * q 8 * q 13 + q 2 * (q 11) ^ 2 + (q 2) ^ 5) * q 1) + (((q 2) ^ 2 * q 8 + (q 2) ^ 2 * q 12 + (q 2) ^ 2 * q 13 + (q 2) ^ 4) * (q 1) ^ 2) + (((q 2) ^ 3) * (q 1) ^ 3)

def row_s_1 (q : ℕ → F) : F := q 2 * q 10 + q 2 * q 13 + q 11 * q 12 + q 11 * q 13 + q 1 * q 2 * q 11 + q 1 * q 2 * q 12 + q 1 * q 2 * q 13 + q 2 * q 8 * q 11 + q 2 * q 8 * q 12 + q 2 * q 8 * q 13 + q 2 * (q 11) ^ 2 + (q 2) ^ 2 * q 11 + (q 2) ^ 2 * q 12 + (q 2) ^ 2 * q 13 + (q 1) ^ 2 * (q 2) ^ 2 + (q 2) ^ 4 + (q 1) ^ 2 * (q 2) ^ 3 + (q 2) ^ 5

def row_s_2 (q : ℕ → F) : F := q 1 * q 10 + q 1 * q 13 + q 2 * q 11 + q 2 * q 12 + q 2 * q 13 + q 1 * q 8 * q 11 + q 1 * q 8 * q 12 + q 1 * q 8 * q 13 + q 1 * (q 11) ^ 2 + (q 2) ^ 2 * q 8 + (q 2) ^ 2 * q 12 + (q 2) ^ 2 * q 13 + q 1 * (q 2) ^ 3 + (q 2) ^ 4 + q 1 * (q 2) ^ 4 + (q 1) ^ 3 * (q 2) ^ 2

def row_s_3 (q : ℕ → F) : F := q 10 + q 13 + q 1 * q 11 + q 1 * q 12 + q 1 * q 13 + (q 2) ^ 2 + q 8 * q 11 + q 8 * q 12 + q 8 * q 13 + (q 11) ^ 2 + (q 2) ^ 3 + (q 1) ^ 2 * (q 2) ^ 2 + (q 2) ^ 4

def row_s_4 (q : ℕ → F) : F := q 10 + q 11 + q 12 + q 8 * q 11 + q 8 * q 12 + q 8 * q 13 + (q 11) ^ 2 + q 1 * (q 2) ^ 2 + (q 1) ^ 2 * q 8 + (q 1) ^ 2 * q 12 + (q 1) ^ 2 * q 13 + (q 1) ^ 3 * q 2 + (q 2) ^ 4

def row_s_5 (q : ℕ → F) : F := q 11 + q 12 + q 13 + (q 1) ^ 2 + (q 2) ^ 2 + (q 1) ^ 2 * q 2

def row_s_6 (q : ℕ → F) : F := q 8 + q 12 + q 13 + q 1 * q 2 + (q 1) ^ 3

def row_s_7 (q : ℕ → F) : F := 1 + q 2 + (q 1) ^ 2

def row_s_8 (q : ℕ → F) : F := q 1 + q 8 + q 12 + q 13 + q 1 * q 2 + (q 1) ^ 2 + (q 2) ^ 2

def row_s_9 (q : ℕ → F) : F := q 2

def row_s_10 (q : ℕ → F) : F := 1 + q 1

noncomputable def wire_s (a : ℕ → F) : F[X] := (wire_z a + C (a 10)) * (wire_v a + C (a 11))

noncomputable def normal_s (q : ℕ → F) : F[X] :=
  C (row_s_0 q) +
    C (row_s_1 q) * X ^ 1 +
    C (row_s_2 q) * X ^ 2 +
    C (row_s_3 q) * X ^ 3 +
    C (row_s_4 q) * X ^ 4 +
    C (row_s_5 q) * X ^ 5 +
    C (row_s_6 q) * X ^ 6 +
    C (row_s_7 q) * X ^ 7 +
    C (row_s_8 q) * X ^ 8 +
    C (row_s_9 q) * X ^ 9 +
    C (row_s_10 q) * X ^ 10 +
    X ^ 11 +
    X ^ 12

theorem normal_s_degree (q : ℕ → F) : (normal_s q).natDegree ≤ 12 := by
  unfold normal_s
  exact (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (by simp only [natDegree_C]; omega) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_X_pow_le _) (by omega))) (le_trans (natDegree_X_pow_le _) (by omega)))

theorem wire_s_offsets (q : ℕ → F) : wire_s (offsets q) = normal_s q := by
  rw [wire_s, wire_z_offsets, wire_v_offsets]
  apply bounded_ext (d := 12)
  · exact le_trans natDegree_mul_le (Nat.add_le_add
      (show _ ≤ 4 from (natDegree_add_le_of_degree_le (le_trans (normal_z_degree q) (by omega)) (by simp only [natDegree_C]; omega)))
      (show _ ≤ 8 from (natDegree_add_le_of_degree_le (le_trans (normal_v_degree q) (by omega)) (by simp only [natDegree_C]; omega))))
  · exact normal_s_degree q
  · intro k hk
    interval_cases k <;>
      rw [coeff_mul] <;>
        (try simp only [Finset.Nat.sum_antidiagonal_eq_sum_range_succ_mk,
          Finset.sum_range_succ, Finset.sum_range_zero]) <;>
        norm_num only [normal_s, normal_z, normal_v,
          coeff_add, coeff_C_mul_X_pow, coeff_X_pow, coeff_X, coeff_C,
          ite_true, ite_false, zero_add, add_zero, zero_mul, mul_zero, one_mul, mul_one] <;>
        (try simp only [offsets, row_s_0, row_s_1, row_s_2, row_s_3, row_s_4, row_s_5, row_s_6, row_s_7, row_s_8, row_s_9, row_s_10, row_z_0, row_z_1, row_z_2, row_v_0, row_v_1, row_v_2, row_v_3, row_v_4, offset_10, offset_11]) <;>
        ring_char2

def row_r_0 (q : ℕ → F) : F := (q 7 * q 9 + q 4 * q 5 * q 7 + q 5 * (q 7) ^ 2 + (q 5) ^ 2 * q 7 + q 1 * q 2 * q 4 * q 7 + q 1 * q 2 * q 5 * q 7 + q 1 * q 2 * (q 7) ^ 2 + (q 2) ^ 2 * q 4 * q 7 + (q 2) ^ 2 * q 5 * q 7 + (q 2) ^ 2 * (q 7) ^ 2) + (((q 3 * q 9 + (q 2) ^ 2 * q 9 + q 3 * q 4 * q 5 + q 3 * q 4 * q 7 + q 3 * q 5 * q 7 + q 3 * (q 5) ^ 2 + q 3 * (q 7) ^ 2 + (q 2) ^ 2 * q 3 * q 4 + (q 2) ^ 2 * q 3 * q 5 + (q 2) ^ 2 * q 4 * q 5 + (q 2) ^ 2 * q 4 * q 7 + (q 2) ^ 2 * q 5 * q 7 + (q 2) ^ 2 * (q 5) ^ 2 + (q 2) ^ 2 * (q 7) ^ 2 + (q 2) ^ 4 * q 4 + (q 2) ^ 4 * q 5) + ((q 2 * q 9 + q 2 * q 3 * q 4 + q 2 * q 3 * q 5 + q 2 * q 4 * q 5 + q 2 * q 4 * q 7 + q 2 * q 5 * q 7 + q 2 * (q 5) ^ 2 + q 2 * (q 7) ^ 2) * q 1) + (((q 2) ^ 2 * q 4 + (q 2) ^ 2 * q 5) * (q 1) ^ 2)) * q 0) + (((q 3) ^ 2 * q 4 + q 1 * q 2 * (q 3) ^ 2 + (q 2) ^ 2 * (q 3) ^ 2 + (q 1) ^ 2 * (q 2) ^ 2 * q 4 + (q 2) ^ 4 * q 4 + q 1 * (q 2) ^ 5 + (q 1) ^ 2 * (q 2) ^ 4 + (q 1) ^ 3 * (q 2) ^ 3 + (q 2) ^ 6) * (q 0) ^ 2) + (((q 3) ^ 3 + q 1 * q 2 * (q 3) ^ 2 + (q 2) ^ 2 * (q 3) ^ 2 + (q 1) ^ 2 * (q 2) ^ 2 * q 3 + (q 2) ^ 4 * q 3 + q 1 * (q 2) ^ 5 + (q 1) ^ 2 * (q 2) ^ 4 + (q 1) ^ 3 * (q 2) ^ 3 + (q 2) ^ 6) * (q 0) ^ 3)

def row_r_1 (q : ℕ → F) : F := ((q 3 * q 9 + q 2 * q 4 * q 7 + q 2 * q 5 * q 7 + q 2 * (q 7) ^ 2 + (q 2) ^ 2 * q 9 + q 3 * q 4 * q 5 + q 3 * q 4 * q 7 + q 3 * q 5 * q 7 + q 3 * (q 5) ^ 2 + q 3 * (q 7) ^ 2 + (q 2) ^ 2 * q 3 * q 4 + (q 2) ^ 2 * q 3 * q 5 + (q 2) ^ 2 * q 4 * q 5 + (q 2) ^ 2 * q 4 * q 7 + (q 2) ^ 2 * q 5 * q 7 + (q 2) ^ 2 * (q 5) ^ 2 + (q 2) ^ 2 * (q 7) ^ 2 + (q 2) ^ 4 * q 4 + (q 2) ^ 4 * q 5) + ((q 2 * q 9 + q 2 * q 3 * q 4 + q 2 * q 3 * q 5 + q 2 * q 4 * q 5 + q 2 * q 4 * q 7 + q 2 * q 5 * q 7 + q 2 * (q 5) ^ 2 + q 2 * (q 7) ^ 2) * q 1) + (((q 2) ^ 2 * q 4 + (q 2) ^ 2 * q 5) * (q 1) ^ 2)) + ((q 2 * q 9 + q 2 * q 3 * q 4 + q 2 * q 3 * q 5 + q 2 * q 4 * q 5 + q 2 * q 4 * q 7 + q 2 * q 5 * q 7 + q 2 * (q 5) ^ 2 + q 2 * (q 7) ^ 2) * q 0) + ((q 2 * (q 3) ^ 2 + (q 3) ^ 3 + q 1 * q 2 * (q 3) ^ 2 + (q 2) ^ 2 * (q 3) ^ 2 + (q 1) ^ 2 * (q 2) ^ 2 * q 3 + (q 1) ^ 2 * (q 2) ^ 3 + (q 2) ^ 4 * q 3 + (q 2) ^ 5 + q 1 * (q 2) ^ 5 + (q 1) ^ 2 * (q 2) ^ 4 + (q 1) ^ 3 * (q 2) ^ 3 + (q 2) ^ 6) * (q 0) ^ 2) + ((q 2 * (q 3) ^ 2 + (q 1) ^ 2 * (q 2) ^ 3 + (q 2) ^ 5) * (q 0) ^ 3)

def row_r_2 (q : ℕ → F) : F := (q 2 * q 9 + q 5 * q 7 + q 1 * q 2 * q 7 + q 1 * q 4 * q 7 + q 1 * q 5 * q 7 + q 1 * (q 7) ^ 2 + q 2 * q 3 * q 4 + q 2 * q 3 * q 5 + q 2 * q 4 * q 5 + q 2 * q 4 * q 7 + q 2 * q 5 * q 7 + q 2 * (q 5) ^ 2 + q 2 * (q 7) ^ 2 + (q 2) ^ 2 * q 7 + (q 3) ^ 2 * q 4 + q 1 * q 2 * (q 3) ^ 2 + (q 2) ^ 2 * (q 3) ^ 2 + (q 1) ^ 2 * (q 2) ^ 2 * q 4 + (q 2) ^ 4 * q 4 + q 1 * (q 2) ^ 5 + (q 1) ^ 2 * (q 2) ^ 4 + (q 1) ^ 3 * (q 2) ^ 3 + (q 2) ^ 6) + (((q 3 * q 5 + q 3 * q 7 + (q 2) ^ 2 * q 3 + (q 2) ^ 2 * q 4 + (q 2) ^ 2 * q 7 + (q 3) ^ 3 + (q 2) ^ 2 * (q 3) ^ 2 + (q 2) ^ 4 + (q 2) ^ 4 * q 3 + (q 2) ^ 6) + ((q 9 + q 2 * q 3 + q 2 * q 5 + q 2 * q 7 + q 3 * q 4 + q 3 * q 5 + q 4 * q 5 + q 4 * q 7 + q 5 * q 7 + (q 5) ^ 2 + (q 7) ^ 2 + q 2 * (q 3) ^ 2 + (q 2) ^ 5) * q 1) + (((q 2) ^ 2 + (q 2) ^ 2 * q 3 + (q 2) ^ 4) * (q 1) ^ 2) + (((q 2) ^ 3) * (q 1) ^ 3)) * q 0) + (((q 3) ^ 2 + q 1 * (q 3) ^ 2 + q 2 * (q 3) ^ 2 + (q 2) ^ 2 * q 4 + q 1 * (q 2) ^ 3 + (q 1) ^ 2 * (q 2) ^ 2 + q 1 * (q 2) ^ 4 + (q 1) ^ 2 * (q 2) ^ 3 + (q 1) ^ 3 * (q 2) ^ 2 + (q 2) ^ 5) * (q 0) ^ 2) + ((q 1 * (q 3) ^ 2 + (q 2) ^ 2 * q 3 + q 1 * (q 2) ^ 3 + (q 2) ^ 4 + q 1 * (q 2) ^ 4 + (q 1) ^ 3 * (q 2) ^ 2) * (q 0) ^ 3)

def row_r_3 (q : ℕ → F) : F := ((q 2 * q 7 + q 3 * q 5 + q 3 * q 7 + q 4 * q 7 + q 5 * q 7 + (q 7) ^ 2 + q 2 * (q 3) ^ 2 + (q 2) ^ 2 * q 3 + (q 2) ^ 2 * q 4 + (q 2) ^ 2 * q 7 + (q 3) ^ 3 + (q 2) ^ 2 * (q 3) ^ 2 + (q 2) ^ 4 + (q 2) ^ 4 * q 3 + (q 2) ^ 5 + (q 2) ^ 6) + ((q 9 + q 2 * q 3 + q 2 * q 5 + q 2 * q 7 + q 3 * q 4 + q 3 * q 5 + q 4 * q 5 + q 4 * q 7 + q 5 * q 7 + (q 5) ^ 2 + (q 7) ^ 2 + q 2 * (q 3) ^ 2 + (q 2) ^ 5) * q 1) + (((q 2) ^ 2 + (q 2) ^ 2 * q 3 + (q 2) ^ 3 + (q 2) ^ 4) * (q 1) ^ 2) + (((q 2) ^ 3) * (q 1) ^ 3)) + ((q 9 + q 2 * q 3 + q 2 * q 5 + q 2 * q 7 + q 3 * q 4 + q 3 * q 5 + q 4 * q 5 + q 4 * q 7 + q 5 * q 7 + (q 5) ^ 2 + (q 7) ^ 2 + q 2 * (q 3) ^ 2 + (q 1) ^ 2 * (q 2) ^ 3 + (q 2) ^ 5) * q 0) + (((q 3) ^ 2 + q 1 * (q 3) ^ 2 + (q 2) ^ 2 * q 3 + (q 2) ^ 3 + q 1 * (q 2) ^ 3 + (q 1) ^ 2 * (q 2) ^ 2 + q 1 * (q 2) ^ 4 + (q 1) ^ 3 * (q 2) ^ 2) * (q 0) ^ 2) + (((q 3) ^ 2 + (q 2) ^ 3 + (q 1) ^ 2 * (q 2) ^ 2 + (q 2) ^ 4) * (q 0) ^ 3)

def row_r_4 (q : ℕ → F) : F := (q 9 + q 1 * q 7 + q 2 * q 3 + q 2 * q 5 + q 2 * q 7 + q 3 * q 4 + q 3 * q 5 + (q 3) ^ 2 + q 4 * q 5 + (q 5) ^ 2 + q 1 * (q 3) ^ 2 + q 2 * (q 3) ^ 2 + (q 2) ^ 2 * q 4 + q 1 * (q 2) ^ 3 + (q 1) ^ 2 * (q 2) ^ 2 + q 1 * (q 2) ^ 4 + (q 1) ^ 2 * (q 2) ^ 3 + (q 1) ^ 3 * (q 2) ^ 2 + (q 2) ^ 5) + ((q 9 + q 1 * q 3 + q 1 * q 5 + q 1 * q 7 + (q 2) ^ 2 + q 3 * q 4 + q 3 * q 5 + q 4 * q 5 + q 4 * q 7 + q 5 * q 7 + (q 5) ^ 2 + (q 7) ^ 2 + q 1 * (q 3) ^ 2 + (q 1) ^ 2 * q 4 + (q 1) ^ 2 * q 5 + (q 2) ^ 2 * q 3 + q 1 * (q 2) ^ 3 + (q 2) ^ 4 + q 1 * (q 2) ^ 4 + (q 1) ^ 3 * (q 2) ^ 2) * q 0) + (((q 2) ^ 2 + q 1 * (q 2) ^ 2 + (q 1) ^ 2 * q 4 + (q 2) ^ 3 + (q 1) ^ 2 * (q 2) ^ 2 + (q 1) ^ 3 * q 2) * (q 0) ^ 2) + (((q 3) ^ 2 + q 1 * (q 2) ^ 2 + (q 1) ^ 2 * q 3 + (q 1) ^ 3 * q 2 + (q 2) ^ 4) * (q 0) ^ 3)

def row_r_5 (q : ℕ → F) : F := (q 7 + q 9 + q 1 * q 3 + q 1 * q 5 + q 1 * q 7 + (q 2) ^ 2 + q 3 * q 4 + q 3 * q 5 + (q 3) ^ 2 + q 4 * q 5 + q 4 * q 7 + q 5 * q 7 + (q 5) ^ 2 + (q 7) ^ 2 + q 1 * (q 3) ^ 2 + (q 1) ^ 2 * q 4 + (q 1) ^ 2 * q 5 + (q 2) ^ 2 * q 3 + (q 2) ^ 3 + q 1 * (q 2) ^ 3 + (q 1) ^ 2 * (q 2) ^ 2 + q 1 * (q 2) ^ 4 + (q 1) ^ 3 * (q 2) ^ 2) + ((q 3 + q 5 + q 7 + (q 3) ^ 2 + (q 2) ^ 3 + (q 1) ^ 2 * (q 2) ^ 2 + (q 2) ^ 4) * q 0) + (((q 2) ^ 2 + (q 3) ^ 2 + q 1 * (q 2) ^ 2 + (q 1) ^ 2 * q 2 + (q 1) ^ 2 * q 3 + (q 1) ^ 3 * q 2 + (q 2) ^ 4) * (q 0) ^ 2) + (((q 2) ^ 2 + (q 1) ^ 2 * q 2) * (q 0) ^ 3)

def row_r_6 (q : ℕ → F) : F := (q 3 + q 5 + (q 2) ^ 2 + q 1 * (q 2) ^ 2 + (q 1) ^ 2 * q 4 + (q 2) ^ 3 + (q 1) ^ 2 * (q 2) ^ 2 + (q 1) ^ 3 * q 2) + ((q 3 + q 4 + q 7 + (q 1) ^ 2 + (q 3) ^ 2 + q 1 * (q 2) ^ 2 + (q 1) ^ 2 * q 3 + (q 1) ^ 3 * q 2 + (q 2) ^ 4) * q 0) + ((q 4 + q 1 * q 2 + (q 1) ^ 2 + (q 2) ^ 2 + (q 1) ^ 2 * q 2 + (q 1) ^ 3) * (q 0) ^ 2) + ((q 3 + q 1 * q 2 + (q 1) ^ 3) * (q 0) ^ 3)

def row_r_7 (q : ℕ → F) : F := q 3 + q 4 + q 7 + (q 1) ^ 2 + (q 2) ^ 2 + (q 3) ^ 2 + q 0 * (q 2) ^ 2 + (q 0) ^ 2 * q 2 + (q 0) ^ 2 * q 3 + q 1 * (q 2) ^ 2 + (q 1) ^ 2 * q 2 + (q 1) ^ 2 * q 3 + q 0 * (q 1) ^ 2 * q 2 + (q 0) ^ 2 * q 1 * q 2 + (q 0) ^ 2 * (q 1) ^ 2 + (q 0) ^ 3 * q 2 + (q 1) ^ 3 * q 2 + (q 2) ^ 4 + (q 0) ^ 2 * (q 1) ^ 3 + (q 0) ^ 3 * (q 1) ^ 2

def row_r_8 (q : ℕ → F) : F := q 0 + q 4 + q 0 * q 3 + q 0 * q 4 + q 0 * q 5 + (q 0) ^ 2 + q 1 * q 2 + (q 1) ^ 2 + (q 2) ^ 2 + q 0 * q 1 * q 2 + (q 0) ^ 2 * q 1 + (q 0) ^ 2 * q 2 + (q 0) ^ 2 * q 4 + (q 1) ^ 2 * q 2 + (q 1) ^ 3 + q 0 * (q 1) ^ 3 + (q 0) ^ 2 * q 1 * q 2 + (q 0) ^ 2 * (q 2) ^ 2 + (q 0) ^ 3 * q 1 + (q 0) ^ 3 * q 3 + (q 0) ^ 3 * q 1 * q 2 + (q 0) ^ 3 * (q 1) ^ 2 + (q 0) ^ 3 * (q 2) ^ 2

def row_r_9 (q : ℕ → F) : F := 1 + q 2 + q 3 + q 4 + q 5 + q 0 * q 2 + (q 0) ^ 2 + q 1 * q 2 + (q 1) ^ 2 + q 0 * (q 1) ^ 2 + (q 0) ^ 2 * q 1 + (q 0) ^ 2 * q 2 + (q 0) ^ 2 * q 3 + (q 0) ^ 3 + (q 1) ^ 3 + (q 0) ^ 2 * q 1 * q 2 + (q 0) ^ 2 * (q 1) ^ 2 + (q 0) ^ 2 * (q 2) ^ 2 + (q 0) ^ 3 * q 2

def row_r_10 (q : ℕ → F) : F := 1 + q 0 + q 1 + q 2 + q 4 + q 0 * q 1 + q 0 * q 3 + (q 0) ^ 2 + q 1 * q 2 + (q 2) ^ 2 + q 0 * q 1 * q 2 + q 0 * (q 1) ^ 2 + q 0 * (q 2) ^ 2 + (q 0) ^ 2 * q 1 + (q 0) ^ 2 * q 2 + (q 0) ^ 3 + (q 0) ^ 3 * q 1

def row_r_11 (q : ℕ → F) : F := q 0 + q 1 + q 2 + q 3 + q 0 * q 2 + q 1 * q 2 + (q 1) ^ 2 + (q 2) ^ 2 + (q 0) ^ 2 * q 1 + (q 0) ^ 3

def row_r_12 (q : ℕ → F) : F := 1 + q 0 + q 1 + q 2 + q 0 * q 1 + (q 0) ^ 3

def row_r_13 (q : ℕ → F) : F := q 0 + q 1 + (q 0) ^ 2

def row_r_14 (q : ℕ → F) : F := q 0

noncomputable def wire_r (a : ℕ → F) : F[X] := (wire_t a + C (a 12)) * (wire_u a + C (a 13))

noncomputable def normal_r (q : ℕ → F) : F[X] :=
  C (row_r_0 q) +
    C (row_r_1 q) * X ^ 1 +
    C (row_r_2 q) * X ^ 2 +
    C (row_r_3 q) * X ^ 3 +
    C (row_r_4 q) * X ^ 4 +
    C (row_r_5 q) * X ^ 5 +
    C (row_r_6 q) * X ^ 6 +
    C (row_r_7 q) * X ^ 7 +
    C (row_r_8 q) * X ^ 8 +
    C (row_r_9 q) * X ^ 9 +
    C (row_r_10 q) * X ^ 10 +
    C (row_r_11 q) * X ^ 11 +
    C (row_r_12 q) * X ^ 12 +
    C (row_r_13 q) * X ^ 13 +
    C (row_r_14 q) * X ^ 14 +
    X ^ 15

theorem normal_r_degree (q : ℕ → F) : (normal_r q).natDegree ≤ 15 := by
  unfold normal_r
  exact (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (by simp only [natDegree_C]; omega) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_X_pow_le _) (by omega)))

theorem wire_r_offsets (q : ℕ → F) : wire_r (offsets q) = normal_r q := by
  rw [wire_r, wire_t_offsets, wire_u_offsets]
  apply bounded_ext (d := 15)
  · exact le_trans natDegree_mul_le (Nat.add_le_add
      (show _ ≤ 5 from (natDegree_add_le_of_degree_le (le_trans (normal_t_degree q) (by omega)) (by simp only [natDegree_C]; omega)))
      (show _ ≤ 10 from (natDegree_add_le_of_degree_le (le_trans (normal_u_degree q) (by omega)) (by simp only [natDegree_C]; omega))))
  · exact normal_r_degree q
  · intro k hk
    interval_cases k <;>
      rw [coeff_mul] <;>
        (try simp only [Finset.Nat.sum_antidiagonal_eq_sum_range_succ_mk,
          Finset.sum_range_succ, Finset.sum_range_zero]) <;>
        norm_num only [normal_r, normal_t, normal_u,
          coeff_add, coeff_C_mul_X_pow, coeff_X_pow, coeff_X, coeff_C,
          ite_true, ite_false, zero_add, add_zero, zero_mul, mul_zero, one_mul, mul_one] <;>
        (try simp only [offsets, row_r_0, row_r_1, row_r_2, row_r_3, row_r_4, row_r_5, row_r_6, row_r_7, row_r_8, row_r_9, row_r_10, row_r_11, row_r_12, row_r_13, row_r_14, row_t_0, row_t_1, row_t_2, row_t_3, row_t_4, row_u_0, row_u_1, row_u_2, row_u_3, row_u_4, row_u_5, row_u_6, row_u_8, offset_12, offset_13]) <;>
        ring_char2

noncomputable def polynomial (a : ℕ → F) : F[X] := wire_w a + wire_s a + wire_r a + C (a 14)

theorem program_eval (a : ℕ → F) :
    (program (F := F)).circuit.eval (fun i => if i = 0 then X else C (a (i-1))) 0 = polynomial a := rfl

def tail_0 (q : ℕ → F) : F := 0

def tail_1 (q : ℕ → F) : F := q 0 + (q 0) ^ 2

def tail_2 (q : ℕ → F) : F := 1 + q 0 + q 1 + q 0 * q 1 + (q 0) ^ 3

def tail_3 (q : ℕ → F) : F := q 0 + q 1 + q 2 + q 0 * q 2 + q 1 * q 2 + (q 1) ^ 2 + (q 2) ^ 2 + (q 0) ^ 2 * q 1 + (q 0) ^ 3

def tail_4 (q : ℕ → F) : F := q 0 + q 1 + q 2 + q 0 * q 1 + q 0 * q 3 + (q 0) ^ 2 + q 1 * q 2 + (q 2) ^ 2 + q 0 * q 1 * q 2 + q 0 * (q 1) ^ 2 + q 0 * (q 2) ^ 2 + (q 0) ^ 2 * q 1 + (q 0) ^ 2 * q 2 + (q 0) ^ 3 + (q 0) ^ 3 * q 1

def tail_5 (q : ℕ → F) : F := q 2 + q 3 + q 4 + q 0 * q 2 + (q 0) ^ 2 + q 1 * q 2 + (q 1) ^ 2 + q 0 * (q 1) ^ 2 + (q 0) ^ 2 * q 1 + (q 0) ^ 2 * q 2 + (q 0) ^ 2 * q 3 + (q 0) ^ 3 + (q 1) ^ 3 + (q 0) ^ 2 * q 1 * q 2 + (q 0) ^ 2 * (q 1) ^ 2 + (q 0) ^ 2 * (q 2) ^ 2 + (q 0) ^ 3 * q 2

def tail_6 (q : ℕ → F) : F := 1 + q 0 + q 4 + q 0 * q 3 + q 0 * q 4 + q 0 * q 5 + (q 0) ^ 2 + q 1 * q 2 + (q 1) ^ 2 + (q 2) ^ 2 + q 0 * q 1 * q 2 + (q 0) ^ 2 * q 1 + (q 0) ^ 2 * q 2 + (q 0) ^ 2 * q 4 + (q 1) ^ 2 * q 2 + (q 1) ^ 3 + q 0 * (q 1) ^ 3 + (q 0) ^ 2 * q 1 * q 2 + (q 0) ^ 2 * (q 2) ^ 2 + (q 0) ^ 3 * q 1 + (q 0) ^ 3 * q 3 + (q 0) ^ 3 * q 1 * q 2 + (q 0) ^ 3 * (q 1) ^ 2 + (q 0) ^ 3 * (q 2) ^ 2

def tail_7 (q : ℕ → F) : F := q 3 + q 4 + (q 1) ^ 2 + (q 2) ^ 2 + (q 3) ^ 2 + q 0 * (q 2) ^ 2 + (q 0) ^ 2 * q 2 + (q 0) ^ 2 * q 3 + q 1 * (q 2) ^ 2 + (q 1) ^ 2 * q 2 + (q 1) ^ 2 * q 3 + q 0 * (q 1) ^ 2 * q 2 + (q 0) ^ 2 * q 1 * q 2 + (q 0) ^ 2 * (q 1) ^ 2 + (q 0) ^ 3 * q 2 + (q 1) ^ 3 * q 2 + (q 2) ^ 4 + (q 0) ^ 2 * (q 1) ^ 3 + (q 0) ^ 3 * (q 1) ^ 2

def tail_8 (q : ℕ → F) : F := (1 + q 3 + q 5 + q 6 + (q 1) ^ 2 + (q 2) ^ 2 + q 1 * (q 2) ^ 2 + (q 1) ^ 2 * q 4 + (q 2) ^ 3 + (q 1) ^ 2 * (q 2) ^ 2 + (q 1) ^ 3 * q 2) + ((q 3 + q 4 + q 7 + (q 1) ^ 2 + (q 3) ^ 2 + q 1 * (q 2) ^ 2 + (q 1) ^ 2 * q 3 + (q 1) ^ 3 * q 2 + (q 2) ^ 4) * q 0) + ((q 4 + q 1 * q 2 + (q 1) ^ 2 + (q 2) ^ 2 + (q 1) ^ 2 * q 2 + (q 1) ^ 3) * (q 0) ^ 2) + ((q 3 + q 1 * q 2 + (q 1) ^ 3) * (q 0) ^ 3)

def tail_9 (q : ℕ → F) : F := ((q 6 + q 7 + (q 2) ^ 2 + q 3 * q 4 + q 3 * q 5 + (q 3) ^ 2 + q 4 * q 5 + q 4 * q 7 + q 5 * q 7 + (q 5) ^ 2 + (q 7) ^ 2 + (q 2) ^ 2 * q 3 + (q 2) ^ 3) + ((1 + q 3 + q 5 + q 7 + (q 3) ^ 2 + (q 2) ^ 3 + (q 2) ^ 4) * q 1) + ((1 + q 4 + q 5 + (q 2) ^ 2) * (q 1) ^ 2) + (((q 2) ^ 2) * (q 1) ^ 3)) + ((q 3 + q 5 + q 7 + (q 3) ^ 2 + (q 2) ^ 3 + (q 1) ^ 2 * (q 2) ^ 2 + (q 2) ^ 4) * q 0) + (((q 2) ^ 2 + (q 3) ^ 2 + q 1 * (q 2) ^ 2 + (q 1) ^ 2 * q 2 + (q 1) ^ 2 * q 3 + (q 1) ^ 3 * q 2 + (q 2) ^ 4) * (q 0) ^ 2) + (((q 2) ^ 2 + (q 1) ^ 2 * q 2) * (q 0) ^ 3)

def tail_10 (q : ℕ → F) : F := ((1 + q 2 + q 6 + q 8 + q 9 + q 2 * q 3 + q 2 * q 5 + q 2 * q 7 + (q 2) ^ 2 + q 3 * q 4 + q 3 * q 5 + (q 3) ^ 2 + q 4 * q 5 + (q 5) ^ 2 + q 6 * q 8 + q 2 * (q 3) ^ 2 + (q 2) ^ 2 * q 4 + (q 2) ^ 5) + ((q 7 + q 8 + (q 3) ^ 2 + (q 2) ^ 3 + (q 2) ^ 4) * q 1) + ((q 6 + (q 2) ^ 2 + (q 2) ^ 3) * (q 1) ^ 2) + (((q 2) ^ 2) * (q 1) ^ 3)) + ((q 9 + q 1 * q 3 + q 1 * q 5 + q 1 * q 7 + (q 2) ^ 2 + q 3 * q 4 + q 3 * q 5 + q 4 * q 5 + q 4 * q 7 + q 5 * q 7 + (q 5) ^ 2 + (q 7) ^ 2 + q 1 * (q 3) ^ 2 + (q 1) ^ 2 * q 4 + (q 1) ^ 2 * q 5 + (q 2) ^ 2 * q 3 + q 1 * (q 2) ^ 3 + (q 2) ^ 4 + q 1 * (q 2) ^ 4 + (q 1) ^ 3 * (q 2) ^ 2) * q 0) + (((q 2) ^ 2 + q 1 * (q 2) ^ 2 + (q 1) ^ 2 * q 4 + (q 2) ^ 3 + (q 1) ^ 2 * (q 2) ^ 2 + (q 1) ^ 3 * q 2) * (q 0) ^ 2) + (((q 3) ^ 2 + q 1 * (q 2) ^ 2 + (q 1) ^ 2 * q 3 + (q 1) ^ 3 * q 2 + (q 2) ^ 4) * (q 0) ^ 3)

def tail_11 (q : ℕ → F) : F := ((1 + q 10 + q 2 * q 7 + q 2 * q 8 + q 3 * q 5 + q 3 * q 7 + q 4 * q 7 + q 5 * q 7 + q 6 * q 8 + (q 7) ^ 2 + q 2 * (q 3) ^ 2 + (q 2) ^ 2 * q 3 + (q 2) ^ 2 * q 4 + (q 2) ^ 2 * q 7 + (q 3) ^ 3 + (q 2) ^ 2 * (q 3) ^ 2 + (q 2) ^ 4 + (q 2) ^ 4 * q 3 + (q 2) ^ 5 + (q 2) ^ 6) + ((q 2 + q 6 + q 8 + q 9 + q 2 * q 3 + q 2 * q 5 + q 2 * q 7 + q 3 * q 4 + q 3 * q 5 + q 4 * q 5 + q 4 * q 7 + q 5 * q 7 + (q 5) ^ 2 + (q 7) ^ 2 + q 2 * (q 3) ^ 2 + (q 2) ^ 5) * q 1) + (((q 2) ^ 2 + (q 2) ^ 2 * q 3 + (q 2) ^ 3 + (q 2) ^ 4) * (q 1) ^ 2) + (((q 2) ^ 3) * (q 1) ^ 3)) + ((q 9 + q 2 * q 3 + q 2 * q 5 + q 2 * q 7 + q 3 * q 4 + q 3 * q 5 + q 4 * q 5 + q 4 * q 7 + q 5 * q 7 + (q 5) ^ 2 + (q 7) ^ 2 + q 2 * (q 3) ^ 2 + (q 1) ^ 2 * (q 2) ^ 3 + (q 2) ^ 5) * q 0) + (((q 3) ^ 2 + q 1 * (q 3) ^ 2 + (q 2) ^ 2 * q 3 + (q 2) ^ 3 + q 1 * (q 2) ^ 3 + (q 1) ^ 2 * (q 2) ^ 2 + q 1 * (q 2) ^ 4 + (q 1) ^ 3 * (q 2) ^ 2) * (q 0) ^ 2) + (((q 3) ^ 2 + (q 2) ^ 3 + (q 1) ^ 2 * (q 2) ^ 2 + (q 2) ^ 4) * (q 0) ^ 3)

def tail_12 (q : ℕ → F) : F := ((q 6 + q 11 + q 2 * q 6 + q 2 * q 8 + q 2 * q 9 + q 5 * q 7 + q 8 * q 11 + (q 11) ^ 2 + q 2 * q 3 * q 4 + q 2 * q 3 * q 5 + q 2 * q 4 * q 5 + q 2 * q 4 * q 7 + q 2 * q 5 * q 7 + q 2 * (q 5) ^ 2 + q 2 * (q 7) ^ 2 + (q 2) ^ 2 * q 6 + (q 2) ^ 2 * q 7 + (q 2) ^ 2 * q 8 + (q 3) ^ 2 * q 4 + (q 2) ^ 2 * (q 3) ^ 2 + (q 2) ^ 4 + (q 2) ^ 4 * q 4 + (q 2) ^ 6) + ((q 10 + q 2 * q 7 + q 2 * q 8 + q 4 * q 7 + q 5 * q 7 + q 6 * q 8 + (q 7) ^ 2 + q 2 * (q 3) ^ 2 + (q 2) ^ 5) * q 1) + (((q 2) ^ 2 + (q 2) ^ 2 * q 4 + (q 2) ^ 4) * (q 1) ^ 2) + (((q 2) ^ 3) * (q 1) ^ 3)) + (((q 3 * q 5 + q 3 * q 7 + (q 2) ^ 2 * q 3 + (q 2) ^ 2 * q 4 + (q 2) ^ 2 * q 7 + (q 3) ^ 3 + (q 2) ^ 2 * (q 3) ^ 2 + (q 2) ^ 4 + (q 2) ^ 4 * q 3 + (q 2) ^ 6) + ((q 9 + q 2 * q 3 + q 2 * q 5 + q 2 * q 7 + q 3 * q 4 + q 3 * q 5 + q 4 * q 5 + q 4 * q 7 + q 5 * q 7 + (q 5) ^ 2 + (q 7) ^ 2 + q 2 * (q 3) ^ 2 + (q 2) ^ 5) * q 1) + (((q 2) ^ 2 + (q 2) ^ 2 * q 3 + (q 2) ^ 4) * (q 1) ^ 2) + (((q 2) ^ 3) * (q 1) ^ 3)) * q 0) + (((q 3) ^ 2 + q 1 * (q 3) ^ 2 + q 2 * (q 3) ^ 2 + (q 2) ^ 2 * q 4 + q 1 * (q 2) ^ 3 + (q 1) ^ 2 * (q 2) ^ 2 + q 1 * (q 2) ^ 4 + (q 1) ^ 2 * (q 2) ^ 3 + (q 1) ^ 3 * (q 2) ^ 2 + (q 2) ^ 5) * (q 0) ^ 2) + ((q 1 * (q 3) ^ 2 + (q 2) ^ 2 * q 3 + q 1 * (q 2) ^ 3 + (q 2) ^ 4 + q 1 * (q 2) ^ 4 + (q 1) ^ 3 * (q 2) ^ 2) * (q 0) ^ 3)

def tail_13 (q : ℕ → F) : F := (((q 3 * q 9 + q 6 * q 11 + q 8 * q 11 + (q 11) ^ 2 + q 3 * q 4 * q 5 + q 3 * q 4 * q 7 + q 3 * q 5 * q 7 + q 3 * (q 5) ^ 2 + q 3 * (q 7) ^ 2) + ((q 10 + q 4 * q 7 + q 5 * q 7 + q 6 * q 8 + (q 7) ^ 2) * q 2) + ((q 6 + q 8 + q 9 + q 3 * q 4 + q 3 * q 5 + q 4 * q 5 + q 4 * q 7 + q 5 * q 7 + (q 5) ^ 2 + (q 7) ^ 2) * (q 2) ^ 2) + ((1 + q 4 + q 5) * (q 2) ^ 4)) + ((q 2 * q 6 + q 2 * q 8 + q 2 * q 9 + q 2 * q 3 * q 4 + q 2 * q 3 * q 5 + q 2 * q 4 * q 5 + q 2 * q 4 * q 7 + q 2 * q 5 * q 7 + q 2 * (q 5) ^ 2 + q 2 * (q 7) ^ 2) * q 1) + (((q 2) ^ 2 + (q 2) ^ 2 * q 4 + (q 2) ^ 2 * q 5) * (q 1) ^ 2)) + ((q 2 * q 9 + q 2 * q 3 * q 4 + q 2 * q 3 * q 5 + q 2 * q 4 * q 5 + q 2 * q 4 * q 7 + q 2 * q 5 * q 7 + q 2 * (q 5) ^ 2 + q 2 * (q 7) ^ 2) * q 0) + ((q 2 * (q 3) ^ 2 + (q 3) ^ 3 + q 1 * q 2 * (q 3) ^ 2 + (q 2) ^ 2 * (q 3) ^ 2 + (q 1) ^ 2 * (q 2) ^ 2 * q 3 + (q 1) ^ 2 * (q 2) ^ 3 + (q 2) ^ 4 * q 3 + (q 2) ^ 5 + q 1 * (q 2) ^ 5 + (q 1) ^ 2 * (q 2) ^ 4 + (q 1) ^ 3 * (q 2) ^ 3 + (q 2) ^ 6) * (q 0) ^ 2) + ((q 2 * (q 3) ^ 2 + (q 1) ^ 2 * (q 2) ^ 3 + (q 2) ^ 5) * (q 0) ^ 3)

def tail_14 (q : ℕ → F) : F := (q 6 * q 13 + q 7 * q 9 + q 10 * q 12 + q 10 * q 13 + q 1 * q 2 * q 10 + (q 2) ^ 2 * q 10 + q 4 * q 5 * q 7 + q 5 * (q 7) ^ 2 + (q 5) ^ 2 * q 7 + q 6 * q 8 * q 11 + q 6 * (q 11) ^ 2 + q 1 * q 2 * q 4 * q 7 + q 1 * q 2 * q 5 * q 7 + q 1 * q 2 * q 6 * q 8 + q 1 * q 2 * (q 7) ^ 2 + (q 2) ^ 2 * q 4 * q 7 + (q 2) ^ 2 * q 5 * q 7 + (q 2) ^ 2 * q 6 * q 8 + (q 2) ^ 2 * (q 7) ^ 2 + (q 1) ^ 2 * (q 2) ^ 2 * q 6 + (q 2) ^ 4 * q 6) + (((q 3 * q 9 + (q 2) ^ 2 * q 9 + q 3 * q 4 * q 5 + q 3 * q 4 * q 7 + q 3 * q 5 * q 7 + q 3 * (q 5) ^ 2 + q 3 * (q 7) ^ 2 + (q 2) ^ 2 * q 3 * q 4 + (q 2) ^ 2 * q 3 * q 5 + (q 2) ^ 2 * q 4 * q 5 + (q 2) ^ 2 * q 4 * q 7 + (q 2) ^ 2 * q 5 * q 7 + (q 2) ^ 2 * (q 5) ^ 2 + (q 2) ^ 2 * (q 7) ^ 2 + (q 2) ^ 4 * q 4 + (q 2) ^ 4 * q 5) + ((q 2 * q 9 + q 2 * q 3 * q 4 + q 2 * q 3 * q 5 + q 2 * q 4 * q 5 + q 2 * q 4 * q 7 + q 2 * q 5 * q 7 + q 2 * (q 5) ^ 2 + q 2 * (q 7) ^ 2) * q 1) + (((q 2) ^ 2 * q 4 + (q 2) ^ 2 * q 5) * (q 1) ^ 2)) * q 0) + (((q 3) ^ 2 * q 4 + q 1 * q 2 * (q 3) ^ 2 + (q 2) ^ 2 * (q 3) ^ 2 + (q 1) ^ 2 * (q 2) ^ 2 * q 4 + (q 2) ^ 4 * q 4 + q 1 * (q 2) ^ 5 + (q 1) ^ 2 * (q 2) ^ 4 + (q 1) ^ 3 * (q 2) ^ 3 + (q 2) ^ 6) * (q 0) ^ 2) + (((q 3) ^ 3 + q 1 * q 2 * (q 3) ^ 2 + (q 2) ^ 2 * (q 3) ^ 2 + (q 1) ^ 2 * (q 2) ^ 2 * q 3 + (q 2) ^ 4 * q 3 + q 1 * (q 2) ^ 5 + (q 1) ^ 2 * (q 2) ^ 4 + (q 1) ^ 3 * (q 2) ^ 3 + (q 2) ^ 6) * (q 0) ^ 3)

def tail (i : ℕ) (q : ℕ → F) : F :=
  match i with
  | 0 => tail_0 q
  | 1 => tail_1 q
  | 2 => tail_2 q
  | 3 => tail_3 q
  | 4 => tail_4 q
  | 5 => tail_5 q
  | 6 => tail_6 q
  | 7 => tail_7 q
  | 8 => tail_8 q
  | 9 => tail_9 q
  | 10 => tail_10 q
  | 11 => tail_11 q
  | 12 => tail_12 q
  | 13 => tail_13 q
  | 14 => tail_14 q
  | _ + 15 => 0

theorem tail_causal : Causal 15 (tail (F := F)) := by
  intro i hi q r h
  interval_cases i
  · simp only [tail, tail_0]
  · simp only [tail, tail_1, h 0 (by omega)]
  · simp only [tail, tail_2, h 0 (by omega), h 1 (by omega)]
  · simp only [tail, tail_3, h 0 (by omega), h 1 (by omega), h 2 (by omega)]
  · simp only [tail, tail_4, h 0 (by omega), h 1 (by omega), h 2 (by omega), h 3 (by omega)]
  · simp only [tail, tail_5, h 0 (by omega), h 1 (by omega), h 2 (by omega), h 3 (by omega), h 4 (by omega)]
  · simp only [tail, tail_6, h 0 (by omega), h 1 (by omega), h 2 (by omega), h 3 (by omega), h 4 (by omega), h 5 (by omega)]
  · simp only [tail, tail_7, h 0 (by omega), h 1 (by omega), h 2 (by omega), h 3 (by omega), h 4 (by omega)]
  · simp only [tail, tail_8, h 0 (by omega), h 1 (by omega), h 2 (by omega), h 3 (by omega), h 4 (by omega), h 5 (by omega), h 6 (by omega), h 7 (by omega)]
  · simp only [tail, tail_9, h 0 (by omega), h 1 (by omega), h 2 (by omega), h 3 (by omega), h 4 (by omega), h 5 (by omega), h 6 (by omega), h 7 (by omega)]
  · simp only [tail, tail_10, h 0 (by omega), h 1 (by omega), h 2 (by omega), h 3 (by omega), h 4 (by omega), h 5 (by omega), h 6 (by omega), h 7 (by omega), h 8 (by omega), h 9 (by omega)]
  · simp only [tail, tail_11, h 0 (by omega), h 1 (by omega), h 2 (by omega), h 3 (by omega), h 4 (by omega), h 5 (by omega), h 6 (by omega), h 7 (by omega), h 8 (by omega), h 9 (by omega), h 10 (by omega)]
  · simp only [tail, tail_12, h 0 (by omega), h 1 (by omega), h 2 (by omega), h 3 (by omega), h 4 (by omega), h 5 (by omega), h 6 (by omega), h 7 (by omega), h 8 (by omega), h 9 (by omega), h 10 (by omega), h 11 (by omega)]
  · simp only [tail, tail_13, h 0 (by omega), h 1 (by omega), h 2 (by omega), h 3 (by omega), h 4 (by omega), h 5 (by omega), h 6 (by omega), h 7 (by omega), h 8 (by omega), h 9 (by omega), h 10 (by omega), h 11 (by omega)]
  · simp only [tail, tail_14, h 0 (by omega), h 1 (by omega), h 2 (by omega), h 3 (by omega), h 4 (by omega), h 5 (by omega), h 6 (by omega), h 7 (by omega), h 8 (by omega), h 9 (by omega), h 10 (by omega), h 11 (by omega), h 12 (by omega), h 13 (by omega)]

noncomputable def pivot (i : ℕ) : F ≃ F :=
  match i with
  | _ => Equiv.refl F


def rows : Fin 15 ≃ Fin 15 where
  toFun := ![14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
  invFun := ![14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
  left_inv i := by fin_cases i <;> rfl
  right_inv i := by fin_cases i <;> rfl

noncomputable def coefficients : (Fin 15 → F) ≃ (Fin 15 → F) :=
  coefficientEquiv pivot tail tail_causal rows

noncomputable def family (q : Fin 15 → F) : F[X] := polynomial (offsets (extendFin q))

theorem family_normal (q : Fin 15 → F) :
    family q = monicOfCoefficients (coefficients q) := by
  rw [family, polynomial, wire_w_offsets, wire_s_offsets, wire_r_offsets]
  simp only [monicOfCoefficients, Finset.sum_range_succ, Finset.sum_range_zero]
  change _ = X ^ 15 + (0 + C (pivot 14 (extendFin q 14) + tail 14 (extendFin q)) * X ^ 0 + C (pivot 13 (extendFin q 13) + tail 13 (extendFin q)) * X ^ 1 + C (pivot 12 (extendFin q 12) + tail 12 (extendFin q)) * X ^ 2 + C (pivot 11 (extendFin q 11) + tail 11 (extendFin q)) * X ^ 3 + C (pivot 10 (extendFin q 10) + tail 10 (extendFin q)) * X ^ 4 + C (pivot 9 (extendFin q 9) + tail 9 (extendFin q)) * X ^ 5 + C (pivot 8 (extendFin q 8) + tail 8 (extendFin q)) * X ^ 6 + C (pivot 7 (extendFin q 7) + tail 7 (extendFin q)) * X ^ 7 + C (pivot 6 (extendFin q 6) + tail 6 (extendFin q)) * X ^ 8 + C (pivot 5 (extendFin q 5) + tail 5 (extendFin q)) * X ^ 9 + C (pivot 4 (extendFin q 4) + tail 4 (extendFin q)) * X ^ 10 + C (pivot 3 (extendFin q 3) + tail 3 (extendFin q)) * X ^ 11 + C (pivot 2 (extendFin q 2) + tail 2 (extendFin q)) * X ^ 12 + C (pivot 1 (extendFin q 1) + tail 1 (extendFin q)) * X ^ 13 + C (pivot 0 (extendFin q 0) + tail 0 (extendFin q)) * X ^ 14)
  apply bounded_ext (d := 15)
  · exact (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (le_trans (normal_w_degree (extendFin q)) (by omega)) (le_trans (normal_s_degree (extendFin q)) (by omega))) (le_trans (normal_r_degree (extendFin q)) (by omega))) (by simp only [natDegree_C]; omega))
  · exact (natDegree_add_le_of_degree_le (le_trans (natDegree_X_pow_le _) (by omega)) (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (by simp only [natDegree_zero]; omega) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))))
  · intro k hk
    interval_cases k <;>
      norm_num only [normal_w, normal_s, normal_r,
        coeff_add, coeff_C_mul_X_pow, coeff_X_pow, coeff_C, coeff_zero,
        ite_true, ite_false, zero_add, add_zero, zero_mul, mul_zero, one_mul, mul_one] <;>
      (try simp only [offsets, offset_14, tail, tail_0, tail_1, tail_2, tail_3, tail_4, tail_5, tail_6, tail_7, tail_8, tail_9, tail_10, tail_11, tail_12, tail_13, tail_14, pivot, Equiv.refl_apply, row_w_0, row_w_1, row_w_2, row_w_3, row_w_4, row_w_5, row_w_6, row_w_7, row_w_8, row_w_9, row_w_10, row_s_0, row_s_1, row_s_2, row_s_3, row_s_4, row_s_5, row_s_6, row_s_7, row_s_8, row_s_9, row_s_10, row_r_0, row_r_1, row_r_2, row_r_3, row_r_4, row_r_5, row_r_6, row_r_7, row_r_8, row_r_9, row_r_10, row_r_11, row_r_12, row_r_13, row_r_14]) <;>
      ring_char2

theorem evaluation_bijective (x : Fin 15 → F) (hx : Function.Injective x) :
    Function.Bijective (fun q => fun i => (family q).eval (x i)) :=
  Char2Certificate.evaluation_bijective (by omega) _ tail tail_causal rows family family_normal x hx

/-- Preprocessed gate offsets for any requested monic polynomial. -/
noncomputable def decode (c : Fin 15 → F) : ℕ → F := offsets (extendFin (coefficients.symm c))

theorem decode_correct (c : Fin 15 → F) :
    polynomial (decode c) = monicOfCoefficients c := by
  have h := family_normal (coefficients.symm c)
  simpa only [family, decode, Equiv.apply_symm_apply] using h

/-- The same literal counted circuit realizes every prescribed coefficient vector. -/
theorem program_decode_correct (c : Fin 15 → F) :
    (program (F := F)).circuit.eval
      (fun i => if i = 0 then X else C (decode c (i-1))) 0 = monicOfCoefficients c :=
  (program_eval (decode c)).trans (decode_correct c)

end FastPoly.Char2Degree15
