import FastPoly.Examples.Char2Triangular
import FastPoly.Examples.Char2Coefficients
import FastPoly.Examples.Char2Ring
import FastPoly.Cost.MultiplicationProgram
import Mathlib.Tactic.IntervalCases
import Mathlib.Tactic.FinCases

/-! Generated by tools/gen_char2_lean.py. Every identity is checked by Lean.
The website's degree-5 circuit, with explicit normalized coordinates.
Preprocessing is outside the online multiplication count. -/

namespace FastPoly.Char2Degree5
open Polynomial Char2Certificate

set_option maxRecDepth 8192
set_option maxHeartbeats 1000000
set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.unusedSectionVars false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

variable {F : Type*} [Field F] [CharP F 2]

/-- Literal fixed shared circuit; its count is computed from syntax. -/
def circuit : Cost.Circuit F ℕ 1 :=
  .bind (.mul (.input (0)) (.input (0))) (
  .bind (.mul (.add (.input (Sum.inr 0)) (.input (Sum.inl (1)))) (.add (.add (.input (Sum.inl (0))) (.input (Sum.inr 0))) (.input (Sum.inl (2))))) (
  .bind (.mul (.add (.input (Sum.inl (Sum.inl (0)))) (.input (Sum.inl (Sum.inl (3))))) (.add (.input (Sum.inr 0)) (.input (Sum.inl (Sum.inl (4)))))) (
  (.add (.input (Sum.inr 0)) (.input (Sum.inl (Sum.inl (Sum.inl (5)))))))))

theorem multiplication_count : (circuit (F := F)).gates.multiplications = 3 := rfl

def program : Cost.MultiplicationProgram F ℕ 1 3 :=
  ⟨circuit, multiplication_count⟩

def offset_0 (q : ℕ → F) : F := q 1 + q 2

def offset_1 (q : ℕ → F) : F := q 2

def offset_2 (q : ℕ → F) : F := q 0

def offset_3 (q : ℕ → F) : F := q 3

def offset_4 (q : ℕ → F) : F := q 4

def offsets (q : ℕ → F) : ℕ → F
  | 0 => offset_0 q
  | 1 => offset_1 q
  | 2 => offset_2 q
  | 3 => offset_3 q
  | 4 => offset_4 q
  | _ + 5 => 0

noncomputable def wire_y (a : ℕ → F) : F[X] := (X) * (X)

noncomputable def normal_y (q : ℕ → F) : F[X] :=
  X ^ 2

theorem normal_y_degree (q : ℕ → F) : (normal_y q).natDegree ≤ 2 := by
  unfold normal_y
  exact (le_trans (natDegree_X_pow_le _) (by omega))

theorem wire_y_offsets (q : ℕ → F) : wire_y (offsets q) = normal_y q := by
  rw [wire_y]
  apply bounded_ext (d := 2)
  · exact le_trans natDegree_mul_le (Nat.add_le_add
      (show _ ≤ 1 from (by simp only [natDegree_X]; omega))
      (show _ ≤ 1 from (by simp only [natDegree_X]; omega)))
  · exact normal_y_degree q
  · intro k hk
    interval_cases k <;>
      rw [coeff_mul] <;>
        (try simp only [Finset.Nat.sum_antidiagonal_eq_sum_range_succ_mk,
          Finset.sum_range_succ, Finset.sum_range_zero]) <;>
        norm_num only [normal_y,
          coeff_add, coeff_C_mul_X_pow, coeff_X_pow, coeff_X, coeff_C,
          ite_true, ite_false, zero_add, add_zero, zero_mul, mul_zero, one_mul, mul_one] <;>
        (try simp only [offsets]) <;>
        ring_char2

def row_z_0 (q : ℕ → F) : F := q 1 * q 2 + (q 2) ^ 2

def row_z_1 (q : ℕ → F) : F := q 1 + q 2

def row_z_2 (q : ℕ → F) : F := q 1

noncomputable def wire_z (a : ℕ → F) : F[X] := (wire_y a + C (a 0)) * (X + wire_y a + C (a 1))

noncomputable def normal_z (q : ℕ → F) : F[X] :=
  C (row_z_0 q) +
    C (row_z_1 q) * X ^ 1 +
    C (row_z_2 q) * X ^ 2 +
    X ^ 3 +
    X ^ 4

theorem normal_z_degree (q : ℕ → F) : (normal_z q).natDegree ≤ 4 := by
  unfold normal_z
  exact (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (by simp only [natDegree_C]; omega) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_X_pow_le _) (by omega))) (le_trans (natDegree_X_pow_le _) (by omega)))

theorem wire_z_offsets (q : ℕ → F) : wire_z (offsets q) = normal_z q := by
  rw [wire_z, wire_y_offsets]
  apply bounded_ext (d := 4)
  · exact le_trans natDegree_mul_le (Nat.add_le_add
      (show _ ≤ 2 from (natDegree_add_le_of_degree_le (le_trans (normal_y_degree q) (by omega)) (by simp only [natDegree_C]; omega)))
      (show _ ≤ 2 from (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (by simp only [natDegree_X]; omega) (le_trans (normal_y_degree q) (by omega))) (by simp only [natDegree_C]; omega))))
  · exact normal_z_degree q
  · intro k hk
    interval_cases k <;>
      rw [coeff_mul] <;>
        (try simp only [Finset.Nat.sum_antidiagonal_eq_sum_range_succ_mk,
          Finset.sum_range_succ, Finset.sum_range_zero]) <;>
        norm_num only [normal_z, normal_y,
          coeff_add, coeff_C_mul_X_pow, coeff_X_pow, coeff_X, coeff_C,
          ite_true, ite_false, zero_add, add_zero, zero_mul, mul_zero, one_mul, mul_one] <;>
        (try simp only [offsets, row_z_0, row_z_1, row_z_2, offset_0, offset_1]) <;>
        ring_char2

def row_t_0 (q : ℕ → F) : F := q 0 * q 3 + q 0 * q 1 * q 2 + q 0 * (q 2) ^ 2

def row_t_1 (q : ℕ → F) : F := q 3 + q 0 * q 1 + q 0 * q 2 + q 1 * q 2 + (q 2) ^ 2

def row_t_2 (q : ℕ → F) : F := q 1 + q 2 + q 0 * q 1

def row_t_3 (q : ℕ → F) : F := q 0 + q 1

def row_t_4 (q : ℕ → F) : F := 1 + q 0

noncomputable def wire_t (a : ℕ → F) : F[X] := (X + C (a 2)) * (wire_z a + C (a 3))

noncomputable def normal_t (q : ℕ → F) : F[X] :=
  C (row_t_0 q) +
    C (row_t_1 q) * X ^ 1 +
    C (row_t_2 q) * X ^ 2 +
    C (row_t_3 q) * X ^ 3 +
    C (row_t_4 q) * X ^ 4 +
    X ^ 5

theorem normal_t_degree (q : ℕ → F) : (normal_t q).natDegree ≤ 5 := by
  unfold normal_t
  exact (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (by simp only [natDegree_C]; omega) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_X_pow_le _) (by omega)))

theorem wire_t_offsets (q : ℕ → F) : wire_t (offsets q) = normal_t q := by
  rw [wire_t, wire_z_offsets]
  apply bounded_ext (d := 5)
  · exact le_trans natDegree_mul_le (Nat.add_le_add
      (show _ ≤ 1 from (natDegree_add_le_of_degree_le (by simp only [natDegree_X]; omega) (by simp only [natDegree_C]; omega)))
      (show _ ≤ 4 from (natDegree_add_le_of_degree_le (le_trans (normal_z_degree q) (by omega)) (by simp only [natDegree_C]; omega))))
  · exact normal_t_degree q
  · intro k hk
    interval_cases k <;>
      rw [coeff_mul] <;>
        (try simp only [Finset.Nat.sum_antidiagonal_eq_sum_range_succ_mk,
          Finset.sum_range_succ, Finset.sum_range_zero]) <;>
        norm_num only [normal_t, normal_z,
          coeff_add, coeff_C_mul_X_pow, coeff_X_pow, coeff_X, coeff_C,
          ite_true, ite_false, zero_add, add_zero, zero_mul, mul_zero, one_mul, mul_one] <;>
        (try simp only [offsets, row_t_0, row_t_1, row_t_2, row_t_3, row_t_4, row_z_0, row_z_1, row_z_2, offset_2, offset_3]) <;>
        ring_char2

noncomputable def polynomial (a : ℕ → F) : F[X] := wire_t a + C (a 4)

theorem program_eval (a : ℕ → F) :
    (program (F := F)).circuit.eval (fun i => if i = 0 then X else C (a (i-1))) 0 = polynomial a := rfl

def tail_0 (q : ℕ → F) : F := 1

def tail_1 (q : ℕ → F) : F := q 0

def tail_2 (q : ℕ → F) : F := q 1 + q 0 * q 1

def tail_3 (q : ℕ → F) : F := q 0 * q 1 + q 0 * q 2 + q 1 * q 2 + (q 2) ^ 2

def tail_4 (q : ℕ → F) : F := q 0 * q 3 + q 0 * q 1 * q 2 + q 0 * (q 2) ^ 2

def tail (i : ℕ) (q : ℕ → F) : F :=
  match i with
  | 0 => tail_0 q
  | 1 => tail_1 q
  | 2 => tail_2 q
  | 3 => tail_3 q
  | 4 => tail_4 q
  | _ + 5 => 0

theorem tail_causal : Causal 5 (tail (F := F)) := by
  intro i hi q r h
  interval_cases i
  · simp only [tail, tail_0]
  · simp only [tail, tail_1, h 0 (by omega)]
  · simp only [tail, tail_2, h 0 (by omega), h 1 (by omega)]
  · simp only [tail, tail_3, h 0 (by omega), h 1 (by omega), h 2 (by omega)]
  · simp only [tail, tail_4, h 0 (by omega), h 1 (by omega), h 2 (by omega), h 3 (by omega)]

noncomputable def pivot (i : ℕ) : F ≃ F :=
  match i with
  | _ => Equiv.refl F


def rows : Fin 5 ≃ Fin 5 where
  toFun := ![4, 3, 2, 1, 0]
  invFun := ![4, 3, 2, 1, 0]
  left_inv i := by fin_cases i <;> rfl
  right_inv i := by fin_cases i <;> rfl

noncomputable def coefficients : (Fin 5 → F) ≃ (Fin 5 → F) :=
  coefficientEquiv pivot tail tail_causal rows

noncomputable def family (q : Fin 5 → F) : F[X] := polynomial (offsets (extendFin q))

theorem family_normal (q : Fin 5 → F) :
    family q = monicOfCoefficients (coefficients q) := by
  rw [family, polynomial, wire_t_offsets]
  simp only [monicOfCoefficients, Finset.sum_range_succ, Finset.sum_range_zero]
  change _ = X ^ 5 + (0 + C (pivot 4 (extendFin q 4) + tail 4 (extendFin q)) * X ^ 0 + C (pivot 3 (extendFin q 3) + tail 3 (extendFin q)) * X ^ 1 + C (pivot 2 (extendFin q 2) + tail 2 (extendFin q)) * X ^ 2 + C (pivot 1 (extendFin q 1) + tail 1 (extendFin q)) * X ^ 3 + C (pivot 0 (extendFin q 0) + tail 0 (extendFin q)) * X ^ 4)
  apply bounded_ext (d := 5)
  · exact (natDegree_add_le_of_degree_le (le_trans (normal_t_degree (extendFin q)) (by omega)) (by simp only [natDegree_C]; omega))
  · exact (natDegree_add_le_of_degree_le (le_trans (natDegree_X_pow_le _) (by omega)) (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (natDegree_add_le_of_degree_le (by simp only [natDegree_zero]; omega) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))) (le_trans (natDegree_C_mul_X_pow_le _ _) (by omega))))
  · intro k hk
    interval_cases k <;>
      norm_num only [normal_t,
        coeff_add, coeff_C_mul_X_pow, coeff_X_pow, coeff_C, coeff_zero,
        ite_true, ite_false, zero_add, add_zero, zero_mul, mul_zero, one_mul, mul_one] <;>
      (try simp only [offsets, offset_4, tail, tail_0, tail_1, tail_2, tail_3, tail_4, pivot, Equiv.refl_apply, row_t_0, row_t_1, row_t_2, row_t_3, row_t_4]) <;>
      ring_char2

theorem evaluation_bijective (x : Fin 5 → F) (hx : Function.Injective x) :
    Function.Bijective (fun q => fun i => (family q).eval (x i)) :=
  Char2Certificate.evaluation_bijective (by omega) _ tail tail_causal rows family family_normal x hx

/-- Preprocessed gate offsets for any requested monic polynomial. -/
noncomputable def decode (c : Fin 5 → F) : ℕ → F := offsets (extendFin (coefficients.symm c))

theorem decode_correct (c : Fin 5 → F) :
    polynomial (decode c) = monicOfCoefficients c := by
  have h := family_normal (coefficients.symm c)
  simpa only [family, decode, Equiv.apply_symm_apply] using h

/-- The same literal counted circuit realizes every prescribed coefficient vector. -/
theorem program_decode_correct (c : Fin 5 → F) :
    (program (F := F)).circuit.eval
      (fun i => if i = 0 then X else C (decode c (i-1))) 0 = monicOfCoefficients c :=
  (program_eval (decode c)).trans (decode_correct c)

end FastPoly.Char2Degree5
