import FastPoly.Section5.PerturbedT

/-!
# `lem:4k+1-splittable`: the crown construction

The `4k+1` pair is the shared `T_{k,4}` call over the explicit quadratic/quartic
tower `H₂ = (x+b)x + c`, `H₄ = H₂² - (x+a)² + e`, `H̃₄ = H₄ + ρ`.  The five outer
parameters decode from the top five rows with slopes `2k, 2k, -2k, k, k`
(`fourk_param_vis`), and the pair is compatible on the full window with no auxiliary
data (`fourk_crown_compatible`).  The generic engines `coeff_pow_window` and
`pow_coeff_crown` (top-window expansion of a monic power) live here.
-/

namespace FastPoly

open Polynomial Algebra

variable {R A : Type*} [CommRing R] [CommRing A] [Algebra R A]

/-- Windowed power coefficients: if the base's coefficients at indices `≥ c` lie in
`K`, then the `q`-th power's coefficients at indices `≥ (q-1)·D' + c` lie in `K`. -/
theorem coeff_pow_window {K : Subalgebra R A} {U : A[X]} {D' c : ℕ}
    (hUd : U.natDegree ≤ D') (hUK : ∀ a, c ≤ a → U.coeff a ∈ K) :
    ∀ q b, 1 ≤ q → (q - 1) * D' + c ≤ b → (U ^ q).coeff b ∈ K := by
  intro q
  induction q with
  | zero => omega
  | succ q ih =>
    intro b h1 hb
    rcases Nat.eq_zero_or_pos q with hq0 | hqpos
    · subst hq0
      rw [pow_one]
      exact hUK b (by omega)
    · have hqq : (q - 1) * D' + D' = q * D' := by
        have h1' : q - 1 + 1 = q := by omega
        calc (q - 1) * D' + D' = (q - 1 + 1) * D' := by ring
          _ = q * D' := by rw [h1']
      have hq1 : (q + 1 - 1) * D' = q * D' := by
        have h1' : q + 1 - 1 = q := by omega
        rw [h1']
      rw [pow_succ, coeff_mul]
      refine Subalgebra.sum_mem _ fun x hx => ?_
      have hxa : x.1 + x.2 = b := Finset.mem_antidiagonal.1 hx
      rcases Nat.lt_or_ge D' x.2 with hg2 | hl2
      · rw [show U.coeff x.2 = 0 from coeff_eq_zero_of_natDegree_lt (by omega),
          mul_zero]
        exact Subalgebra.zero_mem _
      · rcases Nat.lt_or_ge (q * D') x.1 with hg1 | hl1
        · rw [show (U ^ q).coeff x.1 = 0 from coeff_eq_zero_of_natDegree_lt (by
            have hd : (U ^ q).natDegree ≤ q * D' :=
              le_trans natDegree_pow_le (Nat.mul_le_mul_left _ hUd)
            omega), zero_mul]
          exact Subalgebra.zero_mem _
        · exact Subalgebra.mul_mem _ (ih x.1 hqpos (by omega))
            (hUK x.2 (by omega))

/-- **Crown expansion of a monic power** (the top-window pivot): the coefficient of
`H^n` at `n·D - t` is `n·H.coeff (D - t)` up to elements generated by the strictly
higher coefficients of `H`. -/
theorem pow_coeff_crown {S : Subalgebra R A} {H : A[X]} {D t : ℕ}
    (hH : H.Monic) (hD : H.natDegree = D) (h1 : 1 ≤ t) (htD : t ≤ D)
    (hS : ∀ j, D - t < j → H.coeff j ∈ S) :
    ∀ n, 1 ≤ n → (H ^ n).coeff (n * D - t)
      - ((n : ℕ) : A) * H.coeff (D - t) ∈ S := by
  intro n hn
  have hD1 : 1 ≤ D := by omega
  have hDn : D * n = n * D := Nat.mul_comm D n
  have hDn1 : D * (n - 1) + D = D * n := by
    have h1' : n - 1 + 1 = n := by omega
    calc D * (n - 1) + D = D * (n - 1 + 1) := by ring
      _ = D * n := by rw [h1']
  have hGd : (H - X ^ D).natDegree ≤ D - 1 := by
    have hcoeffz : ∀ m, D - 1 < m → (H - X ^ D).coeff m = 0 := by
      intro m hm
      rcases eq_or_lt_of_le (show D ≤ m from by omega) with heq | hlt
      · rw [coeff_sub, coeff_X_pow, if_pos heq.symm, ← heq, ← hD,
          hH.coeff_natDegree, sub_self]
      · rw [coeff_sub, coeff_X_pow, if_neg (by omega),
          coeff_eq_zero_of_natDegree_lt (by omega), sub_zero]
    exact natDegree_le_iff_coeff_eq_zero.2 (fun m hm => hcoeffz m (by omega))
  have hGS : ∀ a, D - t + 1 ≤ a → (H - X ^ D).coeff a ∈ S := by
    intro a ha
    rw [coeff_sub, coeff_X_pow]
    refine Subalgebra.sub_mem _ (hS a (by omega)) ?_
    split
    · exact Subalgebra.one_mem _
    · exact Subalgebra.zero_mem _
  have hHeq : H = X ^ D + (H - X ^ D) := by ring
  have hpow := pow_add_eq (X ^ D) (H - X ^ D) (m := n) hn
  have hXn : ((X : A[X]) ^ D) ^ n = X ^ (D * n) := by
    rw [← pow_mul]
  have hXn1 : ((X : A[X]) ^ D) ^ (n - 1) = X ^ (D * (n - 1)) := by
    rw [← pow_mul]
  have hkey : (H ^ n).coeff (n * D - t)
      = (X ^ (D * n) : A[X]).coeff (n * D - t)
        + n • ((H - X ^ D) * X ^ (D * (n - 1))).coeff (n * D - t)
        + (binTail (X ^ D) (H - X ^ D) n).coeff (n * D - t) := by
    conv_lhs => rw [hHeq]
    rw [hpow, hXn, hXn1, coeff_add, coeff_add, coeff_smul]
  have hXz : (X ^ (D * n) : A[X]).coeff (n * D - t) = 0 := by
    rw [coeff_X_pow, if_neg (by omega)]
  have hGX : ((H - X ^ D) * X ^ (D * (n - 1))).coeff (n * D - t)
      = (H - X ^ D).coeff (D - t) := by
    have hidx : n * D - t = (D - t) + D * (n - 1) := by
      have hnd : D * (n - 1) + D = D * n := by
        have h1' : n - 1 + 1 = n := by omega
        calc D * (n - 1) + D = D * (n - 1 + 1) := by ring
          _ = D * n := by rw [h1']
      omega
    rw [hidx, coeff_mul_X_pow]
  have hGpivot : (H - X ^ D).coeff (D - t) = H.coeff (D - t) := by
    rw [coeff_sub, coeff_X_pow, if_neg (by omega), sub_zero]
  have hbinS : (binTail (X ^ D) (H - X ^ D) n).coeff (n * D - t) ∈ S := by
    show (∑ q ∈ Finset.Icc 2 n,
      (H - X ^ D) ^ q * (X ^ D) ^ (n - q) * ((n.choose q : ℕ) : A[X])).coeff
        (n * D - t) ∈ S
    rw [finset_sum_coeff]
    refine Subalgebra.sum_mem _ fun q hq => ?_
    obtain ⟨hq2, hqn⟩ := Finset.mem_Icc.1 hq
    have hXq : ((X : A[X]) ^ D) ^ (n - q) = X ^ (D * (n - q)) := by
      rw [← pow_mul]
    rw [show ((n.choose q : ℕ) : A[X]) = C ((n.choose q : ℕ) : A) from by
        rw [Polynomial.C_eq_natCast],
      mul_comm ((H - X ^ D) ^ q * (X ^ D) ^ (n - q)) _, coeff_C_mul, hXq]
    refine Subalgebra.mul_mem _ (Subalgebra.natCast_mem _ _) ?_
    rcases Nat.lt_or_ge (n * D - t) (D * (n - q)) with hlo | hge
    · -- below the monomial shift: the coefficient vanishes
      rw [coeff_mul]
      refine Subalgebra.sum_mem _ fun x hx => ?_
      have hxa : x.1 + x.2 = n * D - t := Finset.mem_antidiagonal.1 hx
      rw [coeff_X_pow]
      split
      · omega
      · rw [mul_zero]
        exact Subalgebra.zero_mem _
    · have hidx : n * D - t = (n * D - t - D * (n - q)) + D * (n - q) := by omega
      rw [hidx, coeff_mul_X_pow]
      refine coeff_pow_window hGd hGS q _ (by omega) ?_
      -- (q-1)(D-1) + (D-t+1) ≤ qD - t + (extra), where the target index is
      -- n·D - t - D(n-q) = q·D - t
      have hqd : n * D - t - D * (n - q) = q * D - t := by
        have hnq : D * (n - q) + q * D = n * D := by
          have h' : (n - q) + q = n := by omega
          calc D * (n - q) + q * D = D * ((n - q) + q) := by ring
            _ = D * n := by rw [h']
            _ = n * D := by ring
        omega
      rw [hqd]
      have hexp : (q - 1) * (D - 1) + (D - t + 1) ≤ q * D - t := by
        have h1' : q - 1 + 1 = q := by omega
        have hq1D : (q - 1) * (D - 1) + (D - 1) = q * (D - 1) := by
          calc (q - 1) * (D - 1) + (D - 1) = (q - 1 + 1) * (D - 1) := by ring
            _ = q * (D - 1) := by rw [h1']
        have hqDD : q * (D - 1) + q = q * D := by
          calc q * (D - 1) + q = q * ((D - 1) + 1) := by ring
            _ = q * D := by rw [show D - 1 + 1 = D from by omega]
        omega
      exact hexp
  have hfin : (H ^ n).coeff (n * D - t) - ((n : ℕ) : A) * H.coeff (D - t)
      = (binTail (X ^ D) (H - X ^ D) n).coeff (n * D - t) := by
    rw [hkey, hXz, hGX, hGpivot]
    simp only [nsmul_eq_mul]
    ring
  rw [hfin]
  exact hbinS


section fourK

variable [Nontrivial A] {b c a e ρ : A}

/-- The quadratic base of the `4k+1` construction. -/
noncomputable def crownH2 (b c : A) : A[X] := (X + C b) * X + C c

/-- The quartic power of the `4k+1` construction. -/
noncomputable def crownH4 (b c a e : A) : A[X] :=
  crownH2 b c ^ 2 - (X + C a) ^ 2 + C e

/-- The two-level tower of the `4k+1` construction. -/
noncomputable def crownHp (b c a e : A) : ℕ → A[X] :=
  fun i => if i = 1 then crownH2 b c else if i = 2 then crownH4 b c a e else X

omit [Nontrivial A] in
theorem crownHp_one : crownHp b c a e 1 = crownH2 b c := rfl

omit [Nontrivial A] in
theorem crownHp_two : crownHp b c a e 2 = crownH4 b c a e := rfl

omit [Nontrivial A] in
theorem crownH2_coeff_zero : (crownH2 b c).coeff 0 = c := by
  unfold crownH2
  rw [coeff_add, mul_coeff_zero, coeff_X_zero, mul_zero, coeff_C, if_pos rfl,
    zero_add]

omit [Nontrivial A] in
theorem crownH2_coeff_one : (crownH2 b c).coeff 1 = b := by
  unfold crownH2
  rw [coeff_add, mul_comm, coeff_X_mul, coeff_add, coeff_X_zero, coeff_C,
    if_pos rfl, coeff_C, if_neg (by omega), zero_add, add_zero]

omit [Nontrivial A] in
theorem crownH2_coeff_two : (crownH2 b c).coeff 2 = 1 := by
  unfold crownH2
  rw [coeff_add, mul_comm, coeff_X_mul, coeff_add, coeff_X_one, coeff_C,
    if_neg (by omega), coeff_C, if_neg (by omega), add_zero, add_zero]

theorem crownH2_monic : (crownH2 b c).Monic ∧ (crownH2 b c).natDegree = 2 := by
  have hm : ((X + C b) * X : A[X]).Monic := (monic_X_add_C b).mul monic_X
  have hd : ((X + C b) * X : A[X]).natDegree = 2 := by
    rw [(monic_X_add_C b).natDegree_mul monic_X, natDegree_X_add_C, natDegree_X]
  obtain ⟨hm', hd'⟩ := monic_add_low (e := C c) hm
    (Or.inr (by rw [natDegree_C, hd]; omega))
  exact ⟨hm', hd'.trans hd⟩

omit [Nontrivial A] in
/-- Normal form of the quartic. -/
theorem crownH4_eq : crownH4 b c a e
    = X ^ 4 + C (b + b) * X ^ 3 + C (b * b + (c + c) - 1) * X ^ 2
      + C (b * c + b * c - (a + a)) * X + C (c * c - a * a + e) := by
  unfold crownH4 crownH2
  simp only [map_add, map_mul, map_sub, map_one]
  ring

omit [Nontrivial A] in
theorem crownH4_coeff_three : (crownH4 b c a e).coeff 3 = b + b := by
  rw [crownH4_eq]
  simp only [coeff_add, coeff_C_mul, coeff_X_pow, Polynomial.coeff_X, coeff_C]
  norm_num

omit [Nontrivial A] in
theorem crownH4_coeff_two :
    (crownH4 b c a e).coeff 2 = b * b + (c + c) - 1 := by
  rw [crownH4_eq]
  simp only [coeff_add, coeff_C_mul, coeff_X_pow, Polynomial.coeff_X, coeff_C]
  norm_num

omit [Nontrivial A] in
theorem crownH4_coeff_one :
    (crownH4 b c a e).coeff 1 = b * c + b * c - (a + a) := by
  rw [crownH4_eq]
  simp only [coeff_add, coeff_C_mul, coeff_X_pow, Polynomial.coeff_X, coeff_C]
  norm_num

omit [Nontrivial A] in
theorem crownH4_coeff_zero :
    (crownH4 b c a e).coeff 0 = c * c - a * a + e := by
  rw [crownH4_eq]
  simp only [coeff_add, coeff_C_mul, coeff_X_pow, Polynomial.coeff_X, coeff_C]
  norm_num

theorem crownH4_monic : (crownH4 b c a e).Monic ∧ (crownH4 b c a e).natDegree = 4 := by
  rw [crownH4_eq]
  have hrest : (C (b + b) * X ^ 3 + C (b * b + (c + c) - 1) * X ^ 2
      + C (b * c + b * c - (a + a)) * X + C (c * c - a * a + e)).natDegree ≤ 3 := by
    refine le_trans (natDegree_add_le _ _) ?_
    simp only [natDegree_C, max_le_iff]
    refine ⟨le_trans (natDegree_add_le _ _) ?_, by omega⟩
    simp only [max_le_iff]
    refine ⟨le_trans (natDegree_add_le _ _) ?_, ?_⟩
    · simp only [max_le_iff]
      constructor
      · exact le_trans (natDegree_C_mul_le _ _) (by
          rw [natDegree_X_pow])
      · exact le_trans (natDegree_C_mul_le _ _) (by
          rw [natDegree_X_pow]
          omega)
    · exact le_trans (natDegree_C_mul_le _ _) (by
        rw [natDegree_X]
        omega)
  have hXm : ((X : A[X]) ^ 4).Monic := monic_X_pow 4
  have hXd : ((X : A[X]) ^ 4).natDegree = 4 := natDegree_X_pow 4
  have hassoc : (X ^ 4 + C (b + b) * X ^ 3 + C (b * b + (c + c) - 1) * X ^ 2
      + C (b * c + b * c - (a + a)) * X + C (c * c - a * a + e) : A[X])
      = X ^ 4 + (C (b + b) * X ^ 3 + C (b * b + (c + c) - 1) * X ^ 2
        + C (b * c + b * c - (a + a)) * X + C (c * c - a * a + e)) := by
    ring
  rw [hassoc]
  obtain ⟨hm', hd'⟩ := monic_add_low
    (e := C (b + b) * X ^ 3 + C (b * b + (c + c) - 1) * X ^ 2
      + C (b * c + b * c - (a + a)) * X + C (c * c - a * a + e)) hXm
    (Or.inr (by omega))
  exact ⟨hm', hd'.trans hXd⟩

/-- The shifted quartic is monic of degree 4. -/
theorem crownH4t_good (ρ : A) : (crownH4 b c a e + C ρ).Monic ∧
    (crownH4 b c a e + C ρ).natDegree = 4 := by
  obtain ⟨hm, hd⟩ := monic_add_C
    (crownH4_monic (b := b) (c := c) (a := a) (e := e)).1
    (by rw [(crownH4_monic (b := b) (c := c) (a := a) (e := e)).2]; norm_num) ρ
  exact ⟨hm, hd.trans (crownH4_monic (b := b) (c := c) (a := a) (e := e)).2⟩

/-- Goodness of the two-level crown tower. -/
theorem crownHp_good : ∀ i, 1 ≤ i → i ≤ 2 → ((crownHp b c a e) i).Monic ∧
    ((crownHp b c a e) i).natDegree = 2 ^ i := by
  intro i h1 hi
  rcases (show i = 1 ∨ i = 2 from by omega) with rfl | rfl
  · rw [crownHp_one]
    exact ⟨crownH2_monic.1, by rw [crownH2_monic.2]; norm_num⟩
  · rw [crownHp_two]
    exact ⟨crownH4_monic.1, by rw [crownH4_monic.2]; norm_num⟩

/-- The scalar-difference witness of the crown tower. -/
theorem crownHp_sd (ρ : A) :
    crownH4 b c a e + C ρ - crownHp b c a e 2 = C ρ := by
  rw [crownHp_two]
  ring

/-- The crown quadratic's coefficients lie in any subalgebra containing its data. -/
theorem crownH2_coeff_mem {S : Subalgebra R A} {b c : A} (hb : b ∈ S) (hc : c ∈ S) :
    ∀ j, (crownH2 b c).coeff j ∈ S := by
  intro j
  rcases j with _ | _ | _ | m
  · rw [crownH2_coeff_zero]; exact hc
  · rw [crownH2_coeff_one]; exact hb
  · rw [crownH2_coeff_two]; exact one_mem _
  · rw [coeff_eq_zero_of_natDegree_lt (by rw [(crownH2_monic (b := b) (c := c)).2]; omega)]
    exact zero_mem _

/-- The crown quartic's coefficients lie in any subalgebra containing its data. -/
theorem crownH4_coeff_mem {S : Subalgebra R A} {b c a e : A}
    (hb : b ∈ S) (hc : c ∈ S) (ha : a ∈ S) (he : e ∈ S) :
    ∀ j, (crownH4 b c a e).coeff j ∈ S := by
  intro j
  rcases j with _ | _ | _ | _ | _ | m
  · rw [crownH4_coeff_zero]
    exact add_mem (sub_mem (mul_mem hc hc) (mul_mem ha ha)) he
  · rw [crownH4_coeff_one]
    exact sub_mem (add_mem (mul_mem hb hc) (mul_mem hb hc)) (add_mem ha ha)
  · rw [crownH4_coeff_two]
    exact sub_mem (add_mem (mul_mem hb hb) (add_mem hc hc)) (one_mem _)
  · rw [crownH4_coeff_three]
    exact add_mem hb hb
  · have h4 : (crownH4 b c a e).coeff 4 = 1 := by
      rw [← (crownH4_monic (b := b) (c := c) (a := a) (e := e)).2]
      exact (crownH4_monic (b := b) (c := c) (a := a) (e := e)).1.coeff_natDegree
    show (crownH4 b c a e).coeff 4 ∈ S
    rw [h4]
    exact one_mem _
  · rw [coeff_eq_zero_of_natDegree_lt
      (by rw [(crownH4_monic (b := b) (c := c) (a := a) (e := e)).2]; omega)]
    exact zero_mem _

/-- Tower coefficient membership from the four crown data. -/
theorem crownHp_coeff_mem {S : Subalgebra R A} {b c a e : A}
    (hb : b ∈ S) (hc : c ∈ S) (ha : a ∈ S) (he : e ∈ S) :
    ∀ i, 1 ≤ i → i ≤ 2 → ∀ j, ((crownHp b c a e) i).coeff j ∈ S := by
  intro i h1 hi
  rcases (show i = 1 ∨ i = 2 from by omega) with rfl | rfl
  · rw [crownHp_one]
    exact crownH2_coeff_mem hb hc
  · rw [crownHp_two]
    exact crownH4_coeff_mem hb hc ha he

variable {K : Subalgebra R A} {k : ℕ} {α : ℕ → A}

/-- Recovery of the five crown parameters at their causal cutoffs. -/
theorem fourk_param_vis (hk : 1 ≤ k)
    (hadm : ∀ n : ℕ, 1 ≤ n → n ≤ 2 * k → IsUnit (((n : ℕ) : ℤ) : R))
    (b c a e ρ : A) :
    b ∈ Vis R K
      (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
        (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
      (Finset.range (4 * k + 1)) (4 * k)
    ∧ c ∈ Vis R K
      (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
        (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
      (Finset.range (4 * k + 1)) (4 * k - 1)
    ∧ a ∈ Vis R K
      (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
        (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
      (Finset.range (4 * k + 1)) (4 * k - 2)
    ∧ e ∈ Vis R K
      (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
        (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
      (Finset.range (4 * k + 1)) (4 * k - 3)
    ∧ ρ ∈ Vis R K
      (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
        (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
      (Finset.range (4 * k + 1)) (4 * k - 4) := by
  obtain ⟨hH2m, hH2d⟩ := crownH2_monic (A := A) (b := b) (c := c)
  obtain ⟨hH4m, hH4d⟩ := crownH4_monic (A := A) (b := b) (c := c) (a := a) (e := e)
  obtain ⟨hHtm, hHtd⟩ := crownH4t_good (b := b) (c := c) (a := a) (e := e) ρ
  have htower : ∀ i, 1 ≤ i → i ≤ 2 → ((crownHp b c a e) i).Monic ∧
      ((crownHp b c a e) i).natDegree = 2 ^ i := by
    intro i h1 hi
    rcases Nat.lt_or_ge i 2 with h | h
    · have hie : i = 1 := by omega
      subst hie
      rw [crownHp_one]
      exact ⟨hH2m, by rw [hH2d]; norm_num⟩
    · have hie : i = 2 := by omega
      subst hie
      rw [crownHp_two]
      exact ⟨hH4m, by rw [hH4d]; norm_num⟩
  obtain ⟨hsp₁, hsp₂⟩ := Tpair_eq_pow_add_R
    (Hp := crownHp b c a e) (Ht := crownH4 b c a e + C ρ) (k := k) (l := 2)
    (α := α)
  rw [show crownHp b c a e 2 = crownH4 b c a e from crownHp_two] at hsp₁
  obtain ⟨hRd₁, hRd₂⟩ := Rk2l_deg k (by omega) 2 (crownHp b c a e)
    (crownH4 b c a e + C ρ) α (by omega) htower hHtm hHtd
    (fun _ _ _ => ⟨ρ, crownHp_sd ρ⟩)
  obtain ⟨⟨hTm₁, hTd₁⟩, hTm₂, hTd₂⟩ := Tpair_good
    (Hp := crownHp b c a e) (Ht := crownH4 b c a e + C ρ) (α := α)
    (k := k) (l := 2) (by omega) (by omega) (fun _ _ => by omega) htower hHtm hHtd
  have hTd₁' : (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1.natDegree
      = 4 * k := by
    rw [hTd₁]
    ring
  have hTd₂' : (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2.natDegree
      = 4 * k := by
    rw [hTd₂]
    ring
  have hb : b ∈ Vis R K
      (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
        (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
      (Finset.range (4 * k + 1)) (4 * k) := by
    -- the crown expansion at the top row
    have hcrown1 := pow_coeff_crown (S := Vis R K
        (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
          (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
        (Finset.range (4 * k + 1)) (4 * k))
      hH4m hH4d (t := 1) (by omega) (by omega)
      (by
        intro j hj
        rcases Nat.lt_or_ge 4 j with h4 | h4
        · rw [coeff_eq_zero_of_natDegree_lt (by omega)]
          exact Subalgebra.zero_mem _
        · rw [show j = 4 from by omega, ← hH4d, hH4m.coeff_natDegree]
          exact Subalgebra.one_mem _)
      k hk
    rw [show k * 4 - 1 = 4 * k - 1 from by omega, crownH4_coeff_three] at hcrown1
    -- read the top row
    have hrowG : 4 * k ∈ Finset.range (4 * k + 1) := Finset.mem_range.2 (by omega)
    have hΨmem : (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
        (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2).coeff (4 * k)
        ∈ Vis R K
          (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
            (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
          (Finset.range (4 * k + 1)) (4 * k) := coeff_mem_Vis hrowG le_rfl
    have hVtop : (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2.coeff
        (4 * k) = 1 := by
      rw [← hTd₂', hTm₂.coeff_natDegree]
    have hcO : (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
        (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2).coeff (4 * k)
        = (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1.coeff (4 * k - 1)
          + (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2.coeff (4 * k) := by
      rw [show 4 * k = (4 * k - 1) + 1 from by omega, coeff_combined,
        show (4 * k - 1) + 1 = 4 * k from by omega]
    have hUco : (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1.coeff
        (4 * k - 1) = (crownH4 b c a e ^ k).coeff (4 * k - 1)
          + (Rpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1.coeff
            (4 * k - 1) := by
      rw [hsp₁, coeff_add]
    have hAz : (Rpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1.coeff
        (4 * k - 1) = 0 := by
      refine coeff_eq_zero_of_natDegree_lt ?_
      have h : (k - 1) * 2 ^ 2 = 4 * k - 4 := by
        have h2 : (2 : ℕ) ^ 2 = 4 := by norm_num
        rw [h2]
        omega
      omega
    -- solve for b
    obtain ⟨u, hu⟩ := hadm (2 * k) (by omega) le_rfl
    have hMA : algebraMap R A (↑u : R) = ((2 * k : ℕ) : A) := by
      rw [hu, map_intCast, Int.cast_natCast]
    have h2kb : ((2 * k : ℕ) : A) * b ∈ Vis R K
        (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
          (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
        (Finset.range (4 * k + 1)) (4 * k) := by
      have hkey : ((2 * k : ℕ) : A) * b
          = (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
              (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2).coeff (4 * k)
            - ((crownH4 b c a e ^ k).coeff (4 * k - 1) - ((k : ℕ) : A) * (b + b))
            - 1 := by
        rw [hcO, hUco, hAz, hVtop]
        push_cast
        ring
      rw [hkey]
      exact Subalgebra.sub_mem _ (Subalgebra.sub_mem _ hΨmem hcrown1)
        (Subalgebra.one_mem _)
    have hkey2 : b = algebraMap R A (↑u⁻¹ : R) * (((2 * k : ℕ) : A) * b) := by
      rw [← hMA, ← mul_assoc, ← map_mul, Units.inv_mul, map_one, one_mul]
    have hfin := Subalgebra.mul_mem _ (algebraMap_mem_Vis (K := K) (↑u⁻¹ : R)) h2kb
    rw [← hkey2] at hfin
    exact hfin
  -- shared high-row power reads
  have htpow := pow_add_eq (crownH4 b c a e) (C ρ) (m := k) hk
  have htbinz : ∀ m, (k - 2) * 4 < m →
      (binTail (crownH4 b c a e) (C ρ) k).coeff m = 0 := by
    intro m hm
    refine coeff_eq_zero_of_natDegree_lt ?_
    have hbt := natDegree_binTail_le (le_of_eq hH4d)
      (le_of_eq (natDegree_C ρ)) (by omega) k
    omega
  have hCρz : ∀ m, 4 * (k - 1) < m →
      (C ρ * crownH4 b c a e ^ (k - 1)).coeff m = 0 := by
    intro m hm
    rw [coeff_C_mul,
      show (crownH4 b c a e ^ (k - 1)).coeff m = 0 from
        coeff_eq_zero_of_natDegree_lt (by
          rw [hH4m.natDegree_pow, hH4d]
          omega), mul_zero]
  have hVco : ∀ m, 4 * (k - 1) < m →
      (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2.coeff m
      = (crownH4 b c a e ^ k).coeff m := by
    intro m hm
    rw [hsp₂, coeff_add,
      show (Rpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2.coeff m = 0
        from coeff_eq_zero_of_natDegree_lt (by
          have h : (k - 1) * 2 ^ 2 = 4 * (k - 1) := by
            have h2 : (2 : ℕ) ^ 2 = 4 := by norm_num
            rw [h2]
            ring
          omega), add_zero, htpow, coeff_add, coeff_add, coeff_smul,
      hCρz m hm, smul_zero, add_zero, htbinz m (by omega), add_zero]
  have hUAz : ∀ m, 4 * (k - 1) < m →
      (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1.coeff m
      = (crownH4 b c a e ^ k).coeff m := by
    intro m hm
    rw [hsp₁, coeff_add,
      show (Rpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1.coeff m = 0
        from coeff_eq_zero_of_natDegree_lt (by
          have h : (k - 1) * 2 ^ 2 = 4 * (k - 1) := by
            have h2 : (2 : ℕ) ^ 2 = 4 := by norm_num
            rw [h2]
            ring
          omega), add_zero]
  have hc : c ∈ Vis R K
      (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
        (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
      (Finset.range (4 * k + 1)) (4 * k - 1) := by
    have hbV : b ∈ Vis R K
        (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
          (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
        (Finset.range (4 * k + 1)) (4 * k - 1) :=
      Vis_antitone_cutoff (by omega) hb
    have hS1 : ∀ j, 3 < j → (crownH4 b c a e).coeff j ∈ Vis R K
        (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
          (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
        (Finset.range (4 * k + 1)) (4 * k - 1) := by
      intro j hj
      rcases Nat.lt_or_ge 4 j with h4 | h4
      · rw [coeff_eq_zero_of_natDegree_lt (by omega)]
        exact Subalgebra.zero_mem _
      · rw [show j = 4 from by omega, ← hH4d, hH4m.coeff_natDegree]
        exact Subalgebra.one_mem _
    have hS2 : ∀ j, 2 < j → (crownH4 b c a e).coeff j ∈ Vis R K
        (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
          (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
        (Finset.range (4 * k + 1)) (4 * k - 1) := by
      intro j hj
      rcases Nat.lt_or_ge 3 j with h3 | h3
      · exact hS1 j h3
      · rw [show j = 3 from by omega, crownH4_coeff_three]
        exact Subalgebra.add_mem _ hbV hbV
    have hcrown1' := pow_coeff_crown hH4m hH4d (t := 1) (by omega) (by omega)
      hS1 k hk
    have hcrown2 := pow_coeff_crown hH4m hH4d (t := 2) (by omega) (by omega)
      hS2 k hk
    rw [show k * 4 - 1 = 4 * k - 1 from by omega, crownH4_coeff_three] at hcrown1'
    rw [show k * 4 - 2 = 4 * k - 2 from by omega, crownH4_coeff_two] at hcrown2
    have hrowG : 4 * k - 1 ∈ Finset.range (4 * k + 1) := Finset.mem_range.2 (by omega)
    have hΨmem := coeff_mem_Vis (K := K)
      (Φ := combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
        (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
      hrowG le_rfl
    have hcO : (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
        (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2).coeff (4 * k - 1)
        = (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1.coeff
            (4 * k - 2)
          + (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2.coeff
            (4 * k - 1) := by
      rw [show 4 * k - 1 = (4 * k - 2) + 1 from by omega, coeff_combined,
        show (4 * k - 2) + 1 = 4 * k - 1 from by omega]
    obtain ⟨u, hu⟩ := hadm (2 * k) (by omega) le_rfl
    have hMA : algebraMap R A (↑u : R) = ((2 * k : ℕ) : A) := by
      rw [hu, map_intCast, Int.cast_natCast]
    have h2kc : ((2 * k : ℕ) : A) * c ∈ Vis R K
        (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
          (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
        (Finset.range (4 * k + 1)) (4 * k - 1) := by
      have hkey : ((2 * k : ℕ) : A) * c
          = (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
              (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2).coeff
              (4 * k - 1)
            - ((crownH4 b c a e ^ k).coeff (4 * k - 2)
              - ((k : ℕ) : A) * (b * b + (c + c) - 1))
            - ((crownH4 b c a e ^ k).coeff (4 * k - 1)
              - ((k : ℕ) : A) * (b + b))
            - ((k : ℕ) : A) * (b * b) + ((k : ℕ) : A)
            - ((k : ℕ) : A) * (b + b) := by
        rw [hcO, hUAz _ (by omega), hVco _ (by omega)]
        push_cast
        ring
      rw [hkey]
      exact Subalgebra.sub_mem _ (Subalgebra.add_mem _ (Subalgebra.sub_mem _
        (Subalgebra.sub_mem _ (Subalgebra.sub_mem _ hΨmem hcrown2) hcrown1')
        (Subalgebra.mul_mem _ (Subalgebra.natCast_mem _ _)
          (Subalgebra.mul_mem _ hbV hbV)))
        (Subalgebra.natCast_mem _ _))
        (Subalgebra.mul_mem _ (Subalgebra.natCast_mem _ _)
          (Subalgebra.add_mem _ hbV hbV))
    have hkey2 : c = algebraMap R A (↑u⁻¹ : R) * (((2 * k : ℕ) : A) * c) := by
      rw [← hMA, ← mul_assoc, ← map_mul, Units.inv_mul, map_one, one_mul]
    have hfin := Subalgebra.mul_mem _
      (algebraMap_mem_Vis (K := K) (↑u⁻¹ : R)) h2kc
    rw [← hkey2] at hfin
    exact hfin
  have ha : a ∈ Vis R K
      (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
        (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
      (Finset.range (4 * k + 1)) (4 * k - 2) := by
    have hbV : b ∈ Vis R K
        (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
          (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
        (Finset.range (4 * k + 1)) (4 * k - 2) := Vis_antitone_cutoff (by omega) hb
    have hcV : c ∈ Vis R K
        (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
          (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
        (Finset.range (4 * k + 1)) (4 * k - 2) := Vis_antitone_cutoff (by omega) hc
    have hS2 : ∀ j, 1 < j → (crownH4 b c a e).coeff j ∈ Vis R K
        (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
          (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
        (Finset.range (4 * k + 1)) (4 * k - 2) := by
      intro j hj
      rcases Nat.lt_or_ge 4 j with h4 | h4
      · rw [coeff_eq_zero_of_natDegree_lt (by omega)]
        exact Subalgebra.zero_mem _
      · rcases Nat.lt_or_ge j 3 with h3 | h3
        · rw [show j = 2 from by omega, crownH4_coeff_two]
          exact Subalgebra.sub_mem _ (Subalgebra.add_mem _
            (Subalgebra.mul_mem _ hbV hbV)
            (Subalgebra.add_mem _ hcV hcV)) (Subalgebra.one_mem _)
        · rcases Nat.lt_or_ge j 4 with h3' | h4'
          · rw [show j = 3 from by omega, crownH4_coeff_three]
            exact Subalgebra.add_mem _ hbV hbV
          · rw [show j = 4 from by omega, ← hH4d, hH4m.coeff_natDegree]
            exact Subalgebra.one_mem _
    have hcrown2' := pow_coeff_crown hH4m hH4d (t := 2) (by omega) (by omega)
      (fun j hj => hS2 j (by omega)) k hk
    have hcrown3 := pow_coeff_crown hH4m hH4d (t := 3) (by omega) (by omega)
      hS2 k hk
    rw [show k * 4 - 2 = 4 * k - 2 from by omega, crownH4_coeff_two] at hcrown2'
    rw [show k * 4 - 3 = 4 * k - 3 from by omega, crownH4_coeff_one] at hcrown3
    have hrowG : 4 * k - 2 ∈ Finset.range (4 * k + 1) := Finset.mem_range.2 (by omega)
    have hΨmem := coeff_mem_Vis (K := K)
      (Φ := combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
        (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
      hrowG le_rfl
    have hcO : (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
        (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2).coeff (4 * k - 2)
        = (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1.coeff
            (4 * k - 3)
          + (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2.coeff
            (4 * k - 2) := by
      rw [show 4 * k - 2 = (4 * k - 3) + 1 from by omega, coeff_combined,
        show (4 * k - 3) + 1 = 4 * k - 2 from by omega]
    obtain ⟨u, hu⟩ := hadm (2 * k) (by omega) le_rfl
    have hMA : algebraMap R A (↑u : R) = ((2 * k : ℕ) : A) := by
      rw [hu, map_intCast, Int.cast_natCast]
    have h2ka : ((2 * k : ℕ) : A) * a ∈ Vis R K
        (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
          (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
        (Finset.range (4 * k + 1)) (4 * k - 2) := by
      have hkey : ((2 * k : ℕ) : A) * a
          = ((k : ℕ) : A) * (b * c + b * c)
            + ((crownH4 b c a e ^ k).coeff (4 * k - 3)
              - ((k : ℕ) : A) * (b * c + b * c - (a + a)))
            + ((crownH4 b c a e ^ k).coeff (4 * k - 2)
              - ((k : ℕ) : A) * (b * b + (c + c) - 1))
            + ((k : ℕ) : A) * (b * b + (c + c) - 1)
            - (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ)
                k 2 α).1
              (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2).coeff
              (4 * k - 2) := by
        rw [hcO, hUAz _ (by omega), hVco _ (by omega)]
        push_cast
        ring
      rw [hkey]
      exact Subalgebra.sub_mem _ (Subalgebra.add_mem _ (Subalgebra.add_mem _
        (Subalgebra.add_mem _
          (Subalgebra.mul_mem _ (Subalgebra.natCast_mem _ _)
            (Subalgebra.add_mem _ (Subalgebra.mul_mem _ hbV hcV)
              (Subalgebra.mul_mem _ hbV hcV)))
          hcrown3) hcrown2')
        (Subalgebra.mul_mem _ (Subalgebra.natCast_mem _ _)
          (Subalgebra.sub_mem _ (Subalgebra.add_mem _
            (Subalgebra.mul_mem _ hbV hbV) (Subalgebra.add_mem _ hcV hcV))
            (Subalgebra.one_mem _)))) hΨmem
    have hkey2 : a = algebraMap R A (↑u⁻¹ : R) * (((2 * k : ℕ) : A) * a) := by
      rw [← hMA, ← mul_assoc, ← map_mul, Units.inv_mul, map_one, one_mul]
    have hfin := Subalgebra.mul_mem _
      (algebraMap_mem_Vis (K := K) (↑u⁻¹ : R)) h2ka
    rw [← hkey2] at hfin
    exact hfin
  have he : e ∈ Vis R K
      (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
        (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
      (Finset.range (4 * k + 1)) (4 * k - 3) := by
    have hbV : b ∈ Vis R K
        (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
          (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
        (Finset.range (4 * k + 1)) (4 * k - 3) := Vis_antitone_cutoff (by omega) hb
    have hcV : c ∈ Vis R K
        (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
          (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
        (Finset.range (4 * k + 1)) (4 * k - 3) := Vis_antitone_cutoff (by omega) hc
    have haV : a ∈ Vis R K
        (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
          (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
        (Finset.range (4 * k + 1)) (4 * k - 3) := Vis_antitone_cutoff (by omega) ha
    have hS3 : ∀ j, 0 < j → (crownH4 b c a e).coeff j ∈ Vis R K
        (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
          (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
        (Finset.range (4 * k + 1)) (4 * k - 3) := by
      intro j hj
      rcases Nat.lt_or_ge 4 j with h4 | h4
      · rw [coeff_eq_zero_of_natDegree_lt (by omega)]
        exact Subalgebra.zero_mem _
      · rcases Nat.lt_or_ge j 2 with h2 | h2
        · rw [show j = 1 from by omega, crownH4_coeff_one]
          exact Subalgebra.sub_mem _ (Subalgebra.add_mem _
            (Subalgebra.mul_mem _ hbV hcV) (Subalgebra.mul_mem _ hbV hcV))
            (Subalgebra.add_mem _ haV haV)
        · rcases Nat.lt_or_ge j 3 with h3 | h3
          · rw [show j = 2 from by omega, crownH4_coeff_two]
            exact Subalgebra.sub_mem _ (Subalgebra.add_mem _
              (Subalgebra.mul_mem _ hbV hbV)
              (Subalgebra.add_mem _ hcV hcV)) (Subalgebra.one_mem _)
          · rcases Nat.lt_or_ge j 4 with h3' | h4'
            · rw [show j = 3 from by omega, crownH4_coeff_three]
              exact Subalgebra.add_mem _ hbV hbV
            · rw [show j = 4 from by omega, ← hH4d, hH4m.coeff_natDegree]
              exact Subalgebra.one_mem _
    have hcrown3' := pow_coeff_crown hH4m hH4d (t := 3) (by omega) (by omega)
      (fun j hj => hS3 j (by omega)) k hk
    have hcrown4 := pow_coeff_crown hH4m hH4d (t := 4) (by omega) (by omega)
      hS3 k hk
    rw [show k * 4 - 3 = 4 * k - 3 from by omega, crownH4_coeff_one] at hcrown3'
    rw [show k * 4 - 4 = 4 * k - 4 from by omega, crownH4_coeff_zero] at hcrown4
    have hAd : (Rpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1.coeff
        (4 * k - 4) ∈ Vis R K
        (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
          (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
        (Finset.range (4 * k + 1)) (4 * k - 3) := by
      rcases eq_or_lt_of_le hk with hk1 | hk2
      · rw [← hk1, Rpair_one]
        rw [show ((0, 0) : A[X] × A[X]).1 = 0 from rfl, coeff_zero]
        exact Subalgebra.zero_mem _
      · obtain ⟨hRl₁, -⟩ := Rk2l_lead k (by omega) 2 (crownHp b c a e)
          (crownH4 b c a e + C ρ) α (by omega) htower hHtm hHtd
          (fun _ _ _ => ⟨ρ, crownHp_sd ρ⟩)
        rw [show (k - 1) * 2 ^ 2 = 4 * k - 4 from by
          have h2 : (2 : ℕ) ^ 2 = 4 := by norm_num
          rw [h2]
          omega] at hRl₁
        rw [hRl₁]
        exact Subalgebra.neg_mem _ (Subalgebra.natCast_mem _ _)
    have hUco : (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1.coeff
        (4 * k - 4) = (crownH4 b c a e ^ k).coeff (4 * k - 4)
          + (Rpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1.coeff
            (4 * k - 4) := by
      rw [hsp₁, coeff_add]
    have hrowG : 4 * k - 3 ∈ Finset.range (4 * k + 1) := Finset.mem_range.2 (by omega)
    have hΨmem := coeff_mem_Vis (K := K)
      (Φ := combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
        (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
      hrowG le_rfl
    have hcO : (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
        (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2).coeff (4 * k - 3)
        = (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1.coeff
            (4 * k - 4)
          + (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2.coeff
            (4 * k - 3) := by
      rw [show 4 * k - 3 = (4 * k - 4) + 1 from by omega, coeff_combined,
        show (4 * k - 4) + 1 = 4 * k - 3 from by omega]
    obtain ⟨u, hu⟩ := hadm k (by omega) (by omega)
    have hMA : algebraMap R A (↑u : R) = ((k : ℕ) : A) := by
      rw [hu, map_intCast, Int.cast_natCast]
    have hke : ((k : ℕ) : A) * e ∈ Vis R K
        (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
          (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
        (Finset.range (4 * k + 1)) (4 * k - 3) := by
      have hkey : ((k : ℕ) : A) * e
          = (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
              (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2).coeff
              (4 * k - 3)
            - (Rpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1.coeff
              (4 * k - 4)
            - ((crownH4 b c a e ^ k).coeff (4 * k - 4)
              - ((k : ℕ) : A) * (c * c - a * a + e))
            - ((crownH4 b c a e ^ k).coeff (4 * k - 3)
              - ((k : ℕ) : A) * (b * c + b * c - (a + a)))
            - ((k : ℕ) : A) * (b * c + b * c - (a + a))
            - ((k : ℕ) : A) * (c * c) + ((k : ℕ) : A) * (a * a) := by
        rw [hcO, hUco, hVco _ (by omega)]
        ring
      rw [hkey]
      exact Subalgebra.add_mem _ (Subalgebra.sub_mem _ (Subalgebra.sub_mem _
        (Subalgebra.sub_mem _ (Subalgebra.sub_mem _ (Subalgebra.sub_mem _
          hΨmem hAd) hcrown4) hcrown3')
        (Subalgebra.mul_mem _ (Subalgebra.natCast_mem _ _)
          (Subalgebra.sub_mem _ (Subalgebra.add_mem _
            (Subalgebra.mul_mem _ hbV hcV) (Subalgebra.mul_mem _ hbV hcV))
            (Subalgebra.add_mem _ haV haV))))
        (Subalgebra.mul_mem _ (Subalgebra.natCast_mem _ _)
          (Subalgebra.mul_mem _ hcV hcV)))
        (Subalgebra.mul_mem _ (Subalgebra.natCast_mem _ _)
          (Subalgebra.mul_mem _ haV haV))
    have hkey2 : e = algebraMap R A (↑u⁻¹ : R) * (((k : ℕ) : A) * e) := by
      rw [← hMA, ← mul_assoc, ← map_mul, Units.inv_mul, map_one, one_mul]
    have hfin := Subalgebra.mul_mem _
      (algebraMap_mem_Vis (K := K) (↑u⁻¹ : R)) hke
    rw [← hkey2] at hfin
    exact hfin
  have hρ : ρ ∈ Vis R K
      (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
        (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
      (Finset.range (4 * k + 1)) (4 * k - 4) := by
    have hbV : b ∈ Vis R K
        (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
          (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
        (Finset.range (4 * k + 1)) (4 * k - 4) := Vis_antitone_cutoff (by omega) hb
    have hcV : c ∈ Vis R K
        (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
          (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
        (Finset.range (4 * k + 1)) (4 * k - 4) := Vis_antitone_cutoff (by omega) hc
    have haV : a ∈ Vis R K
        (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
          (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
        (Finset.range (4 * k + 1)) (4 * k - 4) := Vis_antitone_cutoff (by omega) ha
    have heV : e ∈ Vis R K
        (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
          (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
        (Finset.range (4 * k + 1)) (4 * k - 4) := Vis_antitone_cutoff (by omega) he
    have hH4V : ∀ j, (crownH4 b c a e).coeff j ∈ Vis R K
        (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
          (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
        (Finset.range (4 * k + 1)) (4 * k - 4) := by
      intro j
      rcases Nat.eq_zero_or_pos j with hj0 | hjpos
      · subst hj0
        rw [crownH4_coeff_zero]
        exact Subalgebra.add_mem _ (Subalgebra.sub_mem _
          (Subalgebra.mul_mem _ hcV hcV) (Subalgebra.mul_mem _ haV haV)) heV
      · rcases Nat.lt_or_ge 4 j with h4 | h4
        · rw [coeff_eq_zero_of_natDegree_lt (by omega)]
          exact Subalgebra.zero_mem _
        · rcases Nat.lt_or_ge j 2 with h2 | h2
          · rw [show j = 1 from by omega, crownH4_coeff_one]
            exact Subalgebra.sub_mem _ (Subalgebra.add_mem _
              (Subalgebra.mul_mem _ hbV hcV) (Subalgebra.mul_mem _ hbV hcV))
              (Subalgebra.add_mem _ haV haV)
          · rcases Nat.lt_or_ge j 3 with h3 | h3
            · rw [show j = 2 from by omega, crownH4_coeff_two]
              exact Subalgebra.sub_mem _ (Subalgebra.add_mem _
                (Subalgebra.mul_mem _ hbV hbV)
                (Subalgebra.add_mem _ hcV hcV)) (Subalgebra.one_mem _)
            · rcases Nat.lt_or_ge j 4 with h3' | h4'
              · rw [show j = 3 from by omega, crownH4_coeff_three]
                exact Subalgebra.add_mem _ hbV hbV
              · rw [show j = 4 from by omega, ← hH4d, hH4m.coeff_natDegree]
                exact Subalgebra.one_mem _
    have hH4kV : ∀ m, (crownH4 b c a e ^ k).coeff m ∈ Vis R K
        (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
          (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
        (Finset.range (4 * k + 1)) (4 * k - 4) :=
      coeff_mem_pow hH4V k
    obtain ⟨u, hu⟩ := hadm k (by omega) (by omega)
    have hMA : algebraMap R A (↑u : R) = ((k : ℕ) : A) := by
      rw [hu, map_intCast, Int.cast_natCast]
    have hlead : (crownH4 b c a e ^ (k - 1)).coeff (4 * (k - 1)) = 1 := by
      have h := (hH4m.pow (k - 1)).coeff_natDegree
      rw [hH4m.natDegree_pow, hH4d, show (k - 1) * 4 = 4 * (k - 1) from by ring]
        at h
      exact h
    have hkρ : ((k : ℕ) : A) * ρ ∈ Vis R K
        (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
          (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
        (Finset.range (4 * k + 1)) (4 * k - 4) := by
      rcases eq_or_lt_of_le hk with hk1 | hk2
      · -- `k = 1`: the bottom row reads `ρ` directly
        have hk1' : k = 1 := hk1.symm
        subst hk1'
        have hrowG : 0 ∈ Finset.range (4 * 1 + 1) := Finset.mem_range.2 (by omega)
        have hΨmem := coeff_mem_Vis (K := K) (t := 4 * 1 - 4)
          (Φ := combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ)
            1 2 α).1
            (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) 1 2 α).2)
          hrowG (by omega)
        have hkey : ((1 : ℕ) : A) * ρ
            = (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ)
                1 2 α).1
                (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) 1 2 α).2).coeff 0
              - (crownH4 b c a e ^ 1).coeff 0 := by
          rw [coeff_combined_zero, hsp₂, coeff_add,
            show (Rpair (crownHp b c a e) (crownH4 b c a e + C ρ) 1 2 α).2 = 0
              from by rw [Rpair_one], coeff_zero, add_zero, pow_one, pow_one,
            coeff_add, coeff_C]
          norm_num
        rw [hkey]
        exact Subalgebra.sub_mem _ hΨmem (hH4kV 0)
      · -- `k ≥ 2`: the boundary row with the parameter-free corrections
        obtain ⟨-, hRs₁, -, -⟩ := Rk2l_top_two
          (K := Vis R K
            (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
              (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
            (Finset.range (4 * k + 1)) (4 * k - 4))
          (α := α) hk2 (by omega) htower hHtm hHtd
          (fun _ _ _ => ⟨ρ, crownHp_sd ρ⟩)
          (by
            rw [show (2 : ℕ) ^ (2 - 1) - 1 = 1 from by norm_num,
              show crownHp b c a e (2 - 1) = crownH2 b c from rfl,
              crownH2_coeff_one]
            exact hbV)
          (by
            rw [show (2 : ℕ) ^ 2 - 1 = 3 from by norm_num, crownHp_two,
              crownH4_coeff_three]
            exact Subalgebra.add_mem _ hbV hbV)
          (by
            rw [show (2 : ℕ) ^ 2 - 1 = 3 from by norm_num, coeff_add,
              crownH4_coeff_three, coeff_C, if_neg (by omega)]
            exact Subalgebra.add_mem _ (Subalgebra.add_mem _ hbV hbV)
              (Subalgebra.zero_mem _))
        rw [show (k - 1) * 2 ^ 2 - 1 = 4 * k - 5 from by
          have h2 : (2 : ℕ) ^ 2 = 4 := by norm_num
          rw [h2]
          omega] at hRs₁
        obtain ⟨-, hRl₂⟩ := Rk2l_lead k (by omega) 2 (crownHp b c a e)
          (crownH4 b c a e + C ρ) α (by omega) htower hHtm hHtd
          (fun _ _ _ => ⟨ρ, crownHp_sd ρ⟩)
        rw [show (k - 1) * 2 ^ 2 = 4 * k - 4 from by
          have h2 : (2 : ℕ) ^ 2 = 4 := by norm_num
          rw [h2]
          omega] at hRl₂
        have hrowG : 4 * k - 4 ∈ Finset.range (4 * k + 1) :=
          Finset.mem_range.2 (by omega)
        have hΨmem := coeff_mem_Vis (K := K)
          (Φ := combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ)
            k 2 α).1
            (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
          hrowG le_rfl
        have hcO : (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ)
            k 2 α).1
            (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2).coeff
            (4 * k - 4)
            = (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1.coeff
                (4 * k - 5)
              + (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2.coeff
                (4 * k - 4) := by
          rw [show 4 * k - 4 = (4 * k - 5) + 1 from by omega, coeff_combined,
            show (4 * k - 5) + 1 = 4 * k - 4 from by omega]
        have hUco : (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ)
            k 2 α).1.coeff (4 * k - 5)
            = (crownH4 b c a e ^ k).coeff (4 * k - 5)
              + (Rpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1.coeff
                (4 * k - 5) := by
          rw [hsp₁, coeff_add]
        have hVco' : (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ)
            k 2 α).2.coeff (4 * k - 4)
            = (crownH4 b c a e ^ k).coeff (4 * k - 4) + ((k : ℕ) : A) * ρ
              + (Rpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2.coeff
                (4 * k - 4) := by
          rw [hsp₂, coeff_add, htpow, coeff_add, coeff_add, coeff_smul,
            htbinz _ (by omega), add_zero, coeff_C_mul,
            show 4 * k - 4 = 4 * (k - 1) from by omega, hlead, mul_one]
          simp only [nsmul_eq_mul]
        have hkey : ((k : ℕ) : A) * ρ
            = (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ)
                k 2 α).1
                (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2).coeff
                (4 * k - 4)
              - (crownH4 b c a e ^ k).coeff (4 * k - 5)
              - (Rpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1.coeff
                (4 * k - 5)
              - (crownH4 b c a e ^ k).coeff (4 * k - 4)
              - (Rpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2.coeff
                (4 * k - 4) := by
          rw [hcO, hUco, hVco']
          ring
        rw [hkey, hRl₂]
        exact Subalgebra.sub_mem _ (Subalgebra.sub_mem _ (Subalgebra.sub_mem _
          (Subalgebra.sub_mem _ hΨmem (hH4kV _)) hRs₁) (hH4kV _))
          (Subalgebra.neg_mem _ (Subalgebra.natCast_mem _ _))
    have hkey2 : ρ = algebraMap R A (↑u⁻¹ : R) * (((k : ℕ) : A) * ρ) := by
      rw [← hMA, ← mul_assoc, ← map_mul, Units.inv_mul, map_one, one_mul]
    have hfin := Subalgebra.mul_mem _
      (algebraMap_mem_Vis (K := K) (↑u⁻¹ : R)) hkρ
    rw [← hkey2] at hfin
    exact hfin
  exact ⟨hb, hc, ha, he, hρ⟩

/-- **`lem:4k+1-splittable`, compatibility core**: the crown pair is a compatible
pair of degree `4k` on the full window, with no auxiliary data. -/
theorem fourk_crown_compatible (hk : 1 ≤ k)
    (hadm : ∀ n : ℕ, 1 ≤ n → n ≤ 2 * k → IsUnit (((n : ℕ) : ℤ) : R))
    (b c a e ρ : A) (α : ℕ → A) :
    CompatiblePair K
      (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
      (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2
      (4 * k) (Finset.range (4 * k + 1)) := by
  obtain ⟨hb, hc, ha, he, hρ⟩ := fourk_param_vis (K := K) (α := α) hk hadm b c a e ρ
  obtain ⟨hH2m, hH2d⟩ := crownH2_monic (A := A) (b := b) (c := c)
  obtain ⟨hH4m, hH4d⟩ := crownH4_monic (A := A) (b := b) (c := c) (a := a) (e := e)
  obtain ⟨hHtm, hHtd⟩ := crownH4t_good (b := b) (c := c) (a := a) (e := e) ρ
  have htower : ∀ i, 1 ≤ i → i ≤ 2 → ((crownHp b c a e) i).Monic ∧
      ((crownHp b c a e) i).natDegree = 2 ^ i := by
    intro i h1 hi
    rcases Nat.lt_or_ge i 2 with h | h
    · have hie : i = 1 := by omega
      subst hie
      rw [crownHp_one]
      exact ⟨hH2m, by rw [hH2d]; norm_num⟩
    · have hie : i = 2 := by omega
      subst hie
      rw [crownHp_two]
      exact ⟨hH4m, by rw [hH4d]; norm_num⟩
  obtain ⟨hsp₁, hsp₂⟩ := Tpair_eq_pow_add_R
    (Hp := crownHp b c a e) (Ht := crownH4 b c a e + C ρ) (k := k) (l := 2)
    (α := α)
  rw [show crownHp b c a e 2 = crownH4 b c a e from crownHp_two] at hsp₁
  obtain ⟨hRd₁, hRd₂⟩ := Rk2l_deg k (by omega) 2 (crownHp b c a e)
    (crownH4 b c a e + C ρ) α (by omega) htower hHtm hHtd
    (fun _ _ _ => ⟨ρ, crownHp_sd ρ⟩)
  obtain ⟨⟨hTm₁, hTd₁⟩, hTm₂, hTd₂⟩ := Tpair_good
    (Hp := crownHp b c a e) (Ht := crownH4 b c a e + C ρ) (α := α)
    (k := k) (l := 2) (by omega) (by omega) (fun _ _ => by omega) htower hHtm hHtd
  have hTd₁' : (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1.natDegree
      = 4 * k := by
    rw [hTd₁]
    ring
  have hTd₂' : (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2.natDegree
      = 4 * k := by
    rw [hTd₂]
    ring
  -- everything lives in the boundary context
  have hbV : b ∈ Vis R K
      (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
        (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
      (Finset.range (4 * k + 1)) (4 * k - 4) := Vis_antitone_cutoff (by omega) hb
  have hcV : c ∈ Vis R K
      (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
        (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
      (Finset.range (4 * k + 1)) (4 * k - 4) := Vis_antitone_cutoff (by omega) hc
  have haV : a ∈ Vis R K
      (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
        (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
      (Finset.range (4 * k + 1)) (4 * k - 4) := Vis_antitone_cutoff (by omega) ha
  have heV : e ∈ Vis R K
      (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
        (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
      (Finset.range (4 * k + 1)) (4 * k - 4) := Vis_antitone_cutoff (by omega) he
  have hH2V : ∀ j, (crownH2 b c).coeff j ∈ Vis R K
      (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
        (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
      (Finset.range (4 * k + 1)) (4 * k - 4) := by
    intro j
    rcases Nat.eq_zero_or_pos j with hj0 | hjpos
    · subst hj0
      rw [crownH2_coeff_zero]
      exact hcV
    · rcases Nat.lt_or_ge j 2 with h2 | h2
      · rw [show j = 1 from by omega, crownH2_coeff_one]
        exact hbV
      · rcases Nat.lt_or_ge 2 j with h2' | h2''
        · rw [coeff_eq_zero_of_natDegree_lt (by omega)]
          exact Subalgebra.zero_mem _
        · rw [show j = 2 from by omega, crownH2_coeff_two]
          exact Subalgebra.one_mem _
  have hH4V : ∀ j, (crownH4 b c a e).coeff j ∈ Vis R K
      (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
        (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
      (Finset.range (4 * k + 1)) (4 * k - 4) := by
    intro j
    rcases Nat.eq_zero_or_pos j with hj0 | hjpos
    · subst hj0
      rw [crownH4_coeff_zero]
      exact Subalgebra.add_mem _ (Subalgebra.sub_mem _
        (Subalgebra.mul_mem _ hcV hcV) (Subalgebra.mul_mem _ haV haV)) heV
    · rcases Nat.lt_or_ge 4 j with h4 | h4
      · rw [coeff_eq_zero_of_natDegree_lt (by omega)]
        exact Subalgebra.zero_mem _
      · rcases Nat.lt_or_ge j 2 with h2 | h2
        · rw [show j = 1 from by omega, crownH4_coeff_one]
          exact Subalgebra.sub_mem _ (Subalgebra.add_mem _
            (Subalgebra.mul_mem _ hbV hcV) (Subalgebra.mul_mem _ hbV hcV))
            (Subalgebra.add_mem _ haV haV)
        · rcases Nat.lt_or_ge j 3 with h3 | h3
          · rw [show j = 2 from by omega, crownH4_coeff_two]
            exact Subalgebra.sub_mem _ (Subalgebra.add_mem _
              (Subalgebra.mul_mem _ hbV hbV)
              (Subalgebra.add_mem _ hcV hcV)) (Subalgebra.one_mem _)
          · rcases Nat.lt_or_ge j 4 with h3' | h4'
            · rw [show j = 3 from by omega, crownH4_coeff_three]
              exact Subalgebra.add_mem _ hbV hbV
            · rw [show j = 4 from by omega, ← hH4d, hH4m.coeff_natDegree]
              exact Subalgebra.one_mem _
  have hHtV : ∀ j, (crownH4 b c a e + C ρ).coeff j ∈ Vis R K
      (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
        (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
      (Finset.range (4 * k + 1)) (4 * k - 4) := by
    intro j
    rw [coeff_add, coeff_C]
    refine Subalgebra.add_mem _ (hH4V j) ?_
    split
    · exact hρ
    · exact Subalgebra.zero_mem _
  have htowerVd : ∀ i, 1 ≤ i → i ≤ 2 → ((crownHp b c a e) i).Monic ∧
      ((crownHp b c a e) i).natDegree = 2 ^ i ∧
      (∀ j, ((crownHp b c a e) i).coeff j ∈ Vis R K
      (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
        (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
      (Finset.range (4 * k + 1)) (4 * k - 4)) := by
    intro i h1 hi
    obtain ⟨hm, hd⟩ := htower i h1 hi
    refine ⟨hm, hd, ?_⟩
    rcases Nat.lt_or_ge i 2 with h | h
    · have hie : i = 1 := by omega
      subst hie
      rw [crownHp_one]
      exact hH2V
    · have hie : i = 2 := by omega
      subst hie
      rw [crownHp_two]
      exact hH4V
  have hcert := Rk2l_triangular k (by omega) 2 (crownHp b c a e)
    (crownH4 b c a e + C ρ) α
    (Vis R K
      (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
        (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
      (Finset.range (4 * k + 1)) (4 * k - 4))
    (by omega) htowerVd hHtm hHtd hHtV
    (fun _ _ _ => ⟨ρ, crownHp_sd ρ⟩)
    (fun n h1 h2 => hadm n h1 (by omega))
  have hcompatVd := hcert.toCompatiblePair
    (N := 4 * k)
    (by
      intro j
      have hdiff : (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ)
            k 2 α).1.coeff j
          - (Rpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1.coeff j
          = (crownH4 b c a e ^ k).coeff j := by
        show _ - ((Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
            - (crownHp b c a e) 2 ^ k).coeff j = _
        rw [coeff_sub, show crownHp b c a e 2 = crownH4 b c a e from crownHp_two]
        ring
      rw [hdiff]
      exact coeff_mem_pow hH4V k j)
    (by
      intro j
      have hdiff : (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ)
            k 2 α).2.coeff j
          - (Rpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2.coeff j
          = ((crownH4 b c a e + C ρ) ^ k).coeff j := by
        show _ - ((Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2
            - (crownH4 b c a e + C ρ) ^ k).coeff j = _
        rw [coeff_sub]
        ring
      rw [hdiff]
      exact coeff_mem_pow hHtV k j)
    hTm₁ hTd₁' hTm₂ hTd₂'
    (by
      have h2 : (2 : ℕ) ^ 2 = 4 := by norm_num
      have h := Nat.mul_le_mul_right (2 ^ 2) (show k - 1 ≤ k from by omega)
      omega)
  -- upgrade to the honest context and window
  have hVdle : ∀ t, t ≤ 4 * k - 4 →
      Vis R (Vis R K
      (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
        (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
      (Finset.range (4 * k + 1)) (4 * k - 4))
        (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
          (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
        (Finset.range ((k - 1) * 2 ^ 2)) t
      ≤ Vis R K
          (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
            (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
          (Finset.range (4 * k + 1)) t := by
    intro t ht
    refine Vis_le ?_ ?_
    · exact Vis_antitone_cutoff ht
    · intro i hi hti
      refine coeff_mem_Vis ?_ hti
      refine Finset.mem_range.2 ?_
      have h := Finset.mem_range.1 hi
      have h2 : (2 : ℕ) ^ 2 = 4 := by norm_num
      omega
  -- the crown rows of the powers, with their causal cutoffs
  have hH4kfine : ∀ j, 4 * k - 4 ≤ j → (crownH4 b c a e ^ k).coeff j
      ∈ Vis R K
        (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1
          (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
        (Finset.range (4 * k + 1)) (j + 1) := by
    intro j hj
    rcases Nat.lt_or_ge (4 * k) j with hhi | hle
    · rw [coeff_eq_zero_of_natDegree_lt (by
        rw [hH4m.natDegree_pow, hH4d]
        omega)]
      exact Subalgebra.zero_mem _
    · rcases eq_or_lt_of_le hle with heq | hlt
      · rw [heq, show 4 * k = k * 4 from by ring, ← show (crownH4 b c a e ^ k).natDegree
            = k * 4 from by rw [hH4m.natDegree_pow, hH4d],
          (hH4m.pow k).coeff_natDegree]
        exact Subalgebra.one_mem _
      · -- j = 4k - t for t ∈ {1,2,3,4}
        set t := 4 * k - j with hts
        have ht14 : 1 ≤ t ∧ t ≤ 4 := by omega
        have hjt : j = 4 * k - t := by omega
        have hSfin : ∀ i, 4 - t < i → (crownH4 b c a e).coeff i
            ∈ Vis R K
              (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ)
                k 2 α).1
                (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
              (Finset.range (4 * k + 1)) (j + 1) := by
          intro i hi
          rcases Nat.lt_or_ge 4 i with h4 | h4
          · rw [coeff_eq_zero_of_natDegree_lt (by omega)]
            exact Subalgebra.zero_mem _
          · rcases Nat.lt_or_ge i 1 with h0 | h1
            · omega
            · rcases Nat.lt_or_ge i 2 with h2 | h2
              · rw [show i = 1 from by omega, crownH4_coeff_one]
                have hbi : b ∈ _ := Vis_antitone_cutoff
                  (show j + 1 ≤ 4 * k from by omega) hb
                have hci : c ∈ _ := Vis_antitone_cutoff
                  (show j + 1 ≤ 4 * k - 1 from by omega) hc
                have hai : a ∈ _ := Vis_antitone_cutoff
                  (show j + 1 ≤ 4 * k - 2 from by omega) ha
                exact Subalgebra.sub_mem _ (Subalgebra.add_mem _
                  (Subalgebra.mul_mem _ hbi hci) (Subalgebra.mul_mem _ hbi hci))
                  (Subalgebra.add_mem _ hai hai)
              · rcases Nat.lt_or_ge i 3 with h3 | h3
                · rw [show i = 2 from by omega, crownH4_coeff_two]
                  have hbi : b ∈ _ := Vis_antitone_cutoff
                    (show j + 1 ≤ 4 * k from by omega) hb
                  have hci : c ∈ _ := Vis_antitone_cutoff
                    (show j + 1 ≤ 4 * k - 1 from by omega) hc
                  exact Subalgebra.sub_mem _ (Subalgebra.add_mem _
                    (Subalgebra.mul_mem _ hbi hbi)
                    (Subalgebra.add_mem _ hci hci)) (Subalgebra.one_mem _)
                · rcases Nat.lt_or_ge i 4 with h3' | h4'
                  · rw [show i = 3 from by omega, crownH4_coeff_three]
                    have hbi : b ∈ _ := Vis_antitone_cutoff
                      (show j + 1 ≤ 4 * k from by omega) hb
                    exact Subalgebra.add_mem _ hbi hbi
                  · rw [show i = 4 from by omega, ← hH4d, hH4m.coeff_natDegree]
                    exact Subalgebra.one_mem _
        have hcrown := pow_coeff_crown hH4m hH4d (t := t)
          (by omega) (by omega) hSfin k hk
        rw [show k * 4 - t = j from by omega] at hcrown
        have hpiv : (crownH4 b c a e).coeff (4 - t)
            ∈ Vis R K
              (combined (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ)
                k 2 α).1
                (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).2)
              (Finset.range (4 * k + 1)) (j + 1) := by
          rcases Nat.lt_or_ge (4 - t) 1 with h0 | h1
          · rw [show 4 - t = 0 from by omega, crownH4_coeff_zero]
            have hci : c ∈ _ := Vis_antitone_cutoff
              (show j + 1 ≤ 4 * k - 1 from by omega) hc
            have hai : a ∈ _ := Vis_antitone_cutoff
              (show j + 1 ≤ 4 * k - 2 from by omega) ha
            have hei : e ∈ _ := Vis_antitone_cutoff
              (show j + 1 ≤ 4 * k - 3 from by omega) he
            exact Subalgebra.add_mem _ (Subalgebra.sub_mem _
              (Subalgebra.mul_mem _ hci hci) (Subalgebra.mul_mem _ hai hai)) hei
          · rcases Nat.lt_or_ge (4 - t) 2 with h2 | h2
            · rw [show 4 - t = 1 from by omega, crownH4_coeff_one]
              have hbi : b ∈ _ := Vis_antitone_cutoff
                (show j + 1 ≤ 4 * k from by omega) hb
              have hci : c ∈ _ := Vis_antitone_cutoff
                (show j + 1 ≤ 4 * k - 1 from by omega) hc
              have hai : a ∈ _ := Vis_antitone_cutoff
                (show j + 1 ≤ 4 * k - 2 from by omega) ha
              exact Subalgebra.sub_mem _ (Subalgebra.add_mem _
                (Subalgebra.mul_mem _ hbi hci) (Subalgebra.mul_mem _ hbi hci))
                (Subalgebra.add_mem _ hai hai)
            · rcases Nat.lt_or_ge (4 - t) 3 with h3 | h3
              · rw [show 4 - t = 2 from by omega, crownH4_coeff_two]
                have hbi : b ∈ _ := Vis_antitone_cutoff
                  (show j + 1 ≤ 4 * k from by omega) hb
                have hci : c ∈ _ := Vis_antitone_cutoff
                  (show j + 1 ≤ 4 * k - 1 from by omega) hc
                exact Subalgebra.sub_mem _ (Subalgebra.add_mem _
                  (Subalgebra.mul_mem _ hbi hbi)
                  (Subalgebra.add_mem _ hci hci)) (Subalgebra.one_mem _)
              · rw [show 4 - t = 3 from by omega, crownH4_coeff_three]
                have hbi : b ∈ _ := Vis_antitone_cutoff
                  (show j + 1 ≤ 4 * k from by omega) hb
                exact Subalgebra.add_mem _ hbi hbi
        have hrecomb : (crownH4 b c a e ^ k).coeff j
            = ((crownH4 b c a e ^ k).coeff j
                - ((k : ℕ) : A) * (crownH4 b c a e).coeff (4 - t))
              + ((k : ℕ) : A) * (crownH4 b c a e).coeff (4 - t) := by
          ring
        rw [hrecomb]
        exact Subalgebra.add_mem _ hcrown
          (Subalgebra.mul_mem _ (Subalgebra.natCast_mem _ _) hpiv)
  -- the tilde-power boundary reads
  have htpow := pow_add_eq (crownH4 b c a e) (C ρ) (m := k) hk
  have htbinz : ∀ m, (k - 2) * 4 < m →
      (binTail (crownH4 b c a e) (C ρ) k).coeff m = 0 := by
    intro m hm
    refine coeff_eq_zero_of_natDegree_lt ?_
    have hbt := natDegree_binTail_le (le_of_eq hH4d)
      (le_of_eq (natDegree_C ρ)) (by omega) k
    omega
  refine
    { mem₁ := ?_
      mem₂ := ?_
      monic₁ := hTm₁
      monic₂ := hTm₂
      natDegree₁ := hTd₁'
      natDegree₂ := hTd₂'
      window := ?_ }
  · intro j
    rcases Nat.lt_or_ge j (4 * k - 4) with hjlt | hjge
    · have h := hcompatVd.mem₁ j
      refine hVdle (j + 1) (by omega) ?_
      have hconv : (k - 1) * 2 ^ 2 = 4 * k - 4 := by
        have h2 : (2 : ℕ) ^ 2 = 4 := by norm_num
        rw [h2]
        omega
      rw [hconv] at h ⊢
      exact h
    · have hTco : (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ)
          k 2 α).1.coeff j
          = (crownH4 b c a e ^ k).coeff j
            + (Rpair (crownHp b c a e) (crownH4 b c a e + C ρ) k 2 α).1.coeff
              j := by
        rw [hsp₁, coeff_add]
      rw [hTco]
      refine Subalgebra.add_mem _ (hH4kfine j hjge) ?_
      rcases eq_or_lt_of_le hjge with heq | hlt
      · rcases eq_or_lt_of_le hk with hk1 | hk2
        · rw [← hk1, Rpair_one]
          rw [show ((0, 0) : A[X] × A[X]).1 = 0 from rfl, coeff_zero]
          exact Subalgebra.zero_mem _
        · obtain ⟨hRl₁, -⟩ := Rk2l_lead k (by omega) 2 (crownHp b c a e)
            (crownH4 b c a e + C ρ) α (by omega) htower hHtm hHtd
            (fun _ _ _ => ⟨ρ, crownHp_sd ρ⟩)
          rw [show (k - 1) * 2 ^ 2 = 4 * k - 4 from by
            have h2 : (2 : ℕ) ^ 2 = 4 := by norm_num
            rw [h2]
            omega] at hRl₁
          rw [← heq, hRl₁]
          exact Subalgebra.neg_mem _ (Subalgebra.natCast_mem _ _)
      · rw [coeff_eq_zero_of_natDegree_lt (by
          have h2 : (2 : ℕ) ^ 2 = 4 := by norm_num
          omega)]
        exact Subalgebra.zero_mem _
  · intro j
    rcases Nat.lt_or_ge j (4 * k - 4) with hjlt | hjge
    · have h := hcompatVd.mem₂ j
      refine hVdle j (by omega) ?_
      have hconv : (k - 1) * 2 ^ 2 = 4 * k - 4 := by
        have h2 : (2 : ℕ) ^ 2 = 4 := by norm_num
        rw [h2]
        omega
      rw [hconv] at h ⊢
      exact h
    · rcases eq_or_lt_of_le hjge with heq | hlt
      · have h := hcompatVd.mem₂ j
        refine hVdle j (by omega) ?_
        have hconv : (k - 1) * 2 ^ 2 = 4 * k - 4 := by
          have h2 : (2 : ℕ) ^ 2 = 4 := by norm_num
          rw [h2]
          omega
        rw [hconv] at h ⊢
        exact h
      · have hTco : (Tpair (crownHp b c a e) (crownH4 b c a e + C ρ)
            k 2 α).2.coeff j = (crownH4 b c a e ^ k).coeff j := by
          rw [hsp₂, coeff_add, htpow, coeff_add, coeff_add, coeff_smul,
            htbinz _ (by omega), add_zero,
            show (C ρ * crownH4 b c a e ^ (k - 1)).coeff j = 0 from by
              rw [coeff_C_mul,
                show (crownH4 b c a e ^ (k - 1)).coeff j = 0 from
                  coeff_eq_zero_of_natDegree_lt (by
                    rw [hH4m.natDegree_pow, hH4d]
                    omega), mul_zero],
            smul_zero, add_zero,
            show (Rpair (crownHp b c a e) (crownH4 b c a e + C ρ)
                k 2 α).2.coeff j = 0 from coeff_eq_zero_of_natDegree_lt (by
              have h2 : (2 : ℕ) ^ 2 = 4 := by norm_num
              omega),
            add_zero]
        rw [hTco]
        exact Vis_antitone_cutoff (by omega) (hH4kfine j hjge)
  · intro x hx
    exact hx

end fourK

end FastPoly
